CREATE TABLE IF NOT EXISTS dim_unidade (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  regional CHAR(2) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
