table fluxo
	lineageTag: fd9795f5-6543-4b5c-bed4-147e954455b2

	column UNIDADE
		dataType: string
		lineageTag: 09433ef8-bc32-4736-911f-a56f5439bc0e
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column NR_ATENDIMENTO
		dataType: int64
		formatString: 0
		lineageTag: bca580dc-4dda-4469-9325-46a1e6ac04f4
		summarizeBy: none
		sourceColumn: NR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column PACIENTE
		dataType: string
		lineageTag: ab3ccc1c-fe3b-4432-8190-2ab8e49ffecf
		summarizeBy: none
		sourceColumn: PACIENTE

		annotation SummarizationSetBy = Automatic

	column DT_ENTRADA
		dataType: dateTime
		formatString: General Date
		lineageTag: b8e66030-5704-460d-8c15-500fee59c51d
		summarizeBy: none
		sourceColumn: DT_ENTRADA

		variation Variation
			isDefault
			relationship: d2f62ba4-ab00-46d6-abe7-6e1b18282ca8
			defaultHierarchy: LocalDateTable_febe5996-d337-4737-ba20-131bd1a46319.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_TRIAGEM
		dataType: dateTime
		formatString: General Date
		lineageTag: 68590c3d-43eb-476a-ba86-948993df0a60
		summarizeBy: none
		sourceColumn: DT_TRIAGEM

		variation Variation
			isDefault
			relationship: d6650db7-29de-4ed0-82d3-a60ed064aec9
			defaultHierarchy: LocalDateTable_fc9eb88e-f3ce-493c-8d2e-a95e06602e56.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_FIM_TRIAGEM
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cdec3f2-88be-451c-aef6-0d1ceb8a448f
		summarizeBy: none
		sourceColumn: DT_FIM_TRIAGEM

		variation Variation
			isDefault
			relationship: 8836d9d7-2a78-4cd2-94a7-1021e5669a9f
			defaultHierarchy: LocalDateTable_70efad8f-b74d-4ec9-ab97-9e31093b5b4d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_ATEND_MEDICO
		dataType: dateTime
		formatString: Short Time
		lineageTag: 109263c6-b492-4d8c-9534-6af63757f7fb
		summarizeBy: none
		sourceColumn: DT_ATEND_MEDICO

		variation Variation
			isDefault
			relationship: 7ceda53f-9ee2-4121-a8f8-cac1f19a7839
			defaultHierarchy: LocalDateTable_fbda6103-0217-46f3-bebd-417a1ebcf9ca.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_ALTA
		dataType: dateTime
		formatString: General Date
		lineageTag: 3f0dc233-80f4-49ef-80c1-91fe77f6c76b
		summarizeBy: none
		sourceColumn: DT_ALTA

		variation Variation
			isDefault
			relationship: 326eedf8-2085-4375-a8cc-1f25c03ae215
			defaultHierarchy: LocalDateTable_d439e39d-2ae8-4f88-a52d-f46b0eab0986.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MIN_ENTRADA_X_TRIAGEM
		dataType: double
		lineageTag: 95fb5067-c97e-4eec-ba6b-b28d128015f7
		summarizeBy: sum
		sourceColumn: MIN_ENTRADA_X_TRIAGEM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MIN_ENTRADA_X_CONSULTA
		dataType: double
		lineageTag: 1a2cd7c9-950f-49c5-99d1-b86e2cbddba4
		summarizeBy: sum
		sourceColumn: MIN_ENTRADA_X_CONSULTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MIN_ENTRADA_X_ALTA
		dataType: double
		lineageTag: 5432b3c4-afb9-435a-a087-5c6e01010c8c
		summarizeBy: sum
		sourceColumn: MIN_ENTRADA_X_ALTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: b80d60d8-fd3b-4866-bce5-33324fa8346e
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HR_ENTRADA = FORMAT([DT_ENTRADA], "HH:00")
		lineageTag: f6d0aa70-79e6-43b8-92f0-90c141e0ae17
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column HR_CONSULTA = FORMAT(fluxo[DT_ATEND_MEDICO], "HH:00")
		lineageTag: 655d46f1-b736-4dd1-be0c-0fd11e428692
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column HR_ALTA = FORMAT(fluxo[DT_ALTA], "HH:00")
		lineageTag: cb921693-8eb1-43b8-9fea-5c09f29fd1ef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IDADE
		dataType: int64
		formatString: 0
		lineageTag: db50b4df-93dc-4ce8-a414-c7cc30cf4601
		summarizeBy: sum
		sourceColumn: IDADE

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: bf283aec-9a81-4157-a309-7f544f3e0e01
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column CIDADE
		dataType: string
		lineageTag: a3b33783-1aa4-4416-bad8-d0907e689540
		summarizeBy: none
		sourceColumn: CIDADE

		annotation SummarizationSetBy = Automatic

	column ESTADO
		dataType: string
		lineageTag: 6fa36028-a76e-4d54-92e9-7fde807ba25d
		summarizeBy: none
		sourceColumn: ESTADO

		annotation SummarizationSetBy = Automatic

	column GRUPO_CID
		dataType: string
		lineageTag: 416ad395-2a87-4e2b-b538-473ac6291ae8
		summarizeBy: none
		sourceColumn: GRUPO_CID

		annotation SummarizationSetBy = Automatic

	column COR
		dataType: string
		lineageTag: f4fed18c-4841-42d9-a04d-172794c43cf2
		summarizeBy: none
		sourceColumn: COR

		annotation SummarizationSetBy = Automatic

	column PRIORIDADE
		dataType: string
		lineageTag: 9010be38-0e0e-436b-b742-194a6ff559f3
		summarizeBy: none
		sourceColumn: PRIORIDADE

		annotation SummarizationSetBy = Automatic

	column MEDICO_ATENDIMENTO
		dataType: string
		lineageTag: 01b63cea-7c65-4c41-bb1f-61d36895d67c
		summarizeBy: none
		sourceColumn: MEDICO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column MEDICO_ALTA
		dataType: string
		lineageTag: 83bbe4d6-e63f-4449-8a0a-5af667131c33
		summarizeBy: none
		sourceColumn: MEDICO_ALTA

		annotation SummarizationSetBy = Automatic

	column ALTA_MEDICA
		dataType: string
		lineageTag: 60cb997a-0ab5-4f8b-9b38-ed93488f07b9
		summarizeBy: none
		sourceColumn: ALTA_MEDICA

		annotation SummarizationSetBy = Automatic

	column ALTA_HOSPITALAR
		dataType: string
		lineageTag: e88c65b1-b06d-400a-b1a2-3bf78c7ab5c9
		summarizeBy: none
		sourceColumn: ALTA_HOSPITALAR

		annotation SummarizationSetBy = Automatic

	column Faixa_Etaria =
			
			SWITCH(
			    TRUE(),
			    VALUE(fluxo[IDADE]) < 0, "Idade inválida",
			    VALUE(fluxo[IDADE]) <= 19, "0-19",
			    VALUE(fluxo[IDADE]) <= 39, "20-39",
			    VALUE(fluxo[IDADE]) <= 59, "40-59",
			    VALUE(fluxo[IDADE]) <= 79, "60-79",
			    VALUE(fluxo[IDADE]) <= 99, "80-99",
			    VALUE(fluxo[IDADE]) <= 119, "100-119",
			    VALUE(fluxo[IDADE]) >= 120, "120+"
			)
		lineageTag: ff938ffe-e23b-4a99-9bf4-9c8c7007bd57
		summarizeBy: none
		sortByColumn: Faixa_Etaria_Ordem

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Faixa_Etaria_Ordem =
			
			SWITCH(
			    TRUE(),
			    VALUE(fluxo[IDADE]) >= 0 && VALUE(fluxo[IDADE]) <= 19, 1,
			    VALUE(fluxo[IDADE]) >= 20 && VALUE(fluxo[IDADE]) <= 39, 2,
			    VALUE(fluxo[IDADE]) >= 40 && VALUE(fluxo[IDADE]) <= 59, 3,
			    VALUE(fluxo[IDADE]) >= 60 && VALUE(fluxo[IDADE]) <= 79, 4,
			    VALUE(fluxo[IDADE]) >= 80 && VALUE(fluxo[IDADE]) <= 99, 5,
			    VALUE(fluxo[IDADE]) >= 100 && VALUE(fluxo[IDADE]) <= 119, 6,
			    VALUE(fluxo[IDADE]) >= 120, 7,
			    0
			)
		formatString: 0
		lineageTag: a971f1be-1714-4ff0-b173-9db4709e41ab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column CD_PESSOA_FISICA
		dataType: string
		lineageTag: 45f03872-8fba-48ef-8b8f-f88df3668b31
		summarizeBy: none
		sourceColumn: CD_PESSOA_FISICA

		annotation SummarizationSetBy = Automatic

	column DT_ALTA_MEDICO
		dataType: dateTime
		formatString: General Date
		lineageTag: 5cd07e49-d6e3-4a99-9d86-d4fe4a0e5c9e
		summarizeBy: none
		sourceColumn: DT_ALTA_MEDICO

		variation Variation
			isDefault
			relationship: a43630dc-d785-43ab-afdd-d71fcbbc9173
			defaultHierarchy: LocalDateTable_3dbd6ec8-185b-4569-9007-ff615f2711d8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Data_Anterior =
			
			CALCULATE(
			    MAX(fluxo[DT_ENTRADA]),
			    FILTER(
			        fluxo,
			        fluxo[CD_PESSOA_FISICA] = EARLIER(fluxo[CD_PESSOA_FISICA]) &&
			        fluxo[DT_ENTRADA] < EARLIER(fluxo[DT_ENTRADA])
			    )
			)
		formatString: General Date
		lineageTag: 687e6d98-89e2-4f37-9667-a5556b384787
		summarizeBy: none

		variation Variation
			isDefault
			relationship: a2d28463-53f1-4e6f-b434-df76c631cdc5
			defaultHierarchy: LocalDateTable_e1e1fe90-7ed1-4aa0-a064-d3ea2e648e64.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Dias_Entre_Atendimentos =
			
			DATEDIFF(
			    fluxo[Data_Anterior],
			    fluxo[DT_ENTRADA],
			    DAY
			)
		formatString: 0
		lineageTag: 4063559b-b34d-47f6-b5a9-870f9db62008
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Readmissao_Em_Ate_1_Dia =
			
			IF(
			    NOT ISBLANK(fluxo[Data_Anterior]) &&
			    fluxo[Dias_Entre_Atendimentos] <= 1,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 75330265-c491-412e-8d66-a65be86fb2ef
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LOCALIZACAO_PAC
		dataType: string
		lineageTag: 423b61da-8cb3-42b8-9d1a-f86e88294f53
		summarizeBy: none
		sourceColumn: LOCALIZACAO_PAC

		annotation SummarizationSetBy = Automatic

	column CD_CID
		dataType: string
		lineageTag: 3d0213c1-8885-4ba1-92d2-41c0764b0809
		summarizeBy: none
		sourceColumn: CD_CID

		annotation SummarizationSetBy = Automatic

	column CID
		dataType: string
		lineageTag: 1583841f-1069-48a1-8270-302df59ad3b9
		summarizeBy: none
		sourceColumn: CID

		annotation SummarizationSetBy = Automatic

	column Readmissao_CID_Igual =
			
			IF (
			    fluxo[Readmissao_Em_Ate_1_Dia] = 1,
			    VAR cidAnterior =
			        CALCULATE (
			            MAX (fluxo[CD_CID]),
			            FILTER (
			                fluxo,
			                fluxo[CD_PESSOA_FISICA] = EARLIER (fluxo[CD_PESSOA_FISICA]) &&
			                fluxo[DT_ENTRADA] = EARLIER (fluxo[Data_Anterior])
			            )
			        )
			    RETURN
			        IF (
			            fluxo[CD_CID] = cidAnterior,
			            "Mesmo CID",
			            "CID diferente"
			        ),
			    BLANK()
			)
		lineageTag: 3d4cf125-a55a-4bb9-ba43-d9674d498653
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DISCRIMINADOR
		dataType: string
		lineageTag: 5a919bb9-59f6-4560-8197-7e5256589a12
		summarizeBy: none
		sourceColumn: DISCRIMINADOR

		annotation SummarizationSetBy = Automatic

	column DT_ALTA_DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4658c444-0732-4f7f-aa2a-5e8c6fda539c
		summarizeBy: none
		sourceColumn: DT_ALTA_DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CD_ESTABELECIMENTO
		dataType: double
		lineageTag: 106c393c-f2b4-4bef-91d4-7c9809f8f3d5
		summarizeBy: none
		sourceColumn: CD_ESTABELECIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESTINO
		dataType: string
		lineageTag: e3f3d9d7-2a14-4ae6-a3e0-7adb592e42b0
		summarizeBy: none
		sourceColumn: DESTINO

		annotation SummarizationSetBy = Automatic

	column DT_INTERNACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: b4d0460c-79ec-451f-a928-4a1c6f6dd32d
		summarizeBy: none
		sourceColumn: DT_INTERNACAO

		variation Variation
			isDefault
			relationship: 7ef1fead-226e-46a1-a861-214c0f7385ef
			defaultHierarchy: LocalDateTable_635e07cf-7b9f-43e5-93cc-eeafcffde169.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column CID_INTERNADO
		dataType: string
		lineageTag: 28c080b9-3bd8-46a1-8e59-6cfedb279a89
		summarizeBy: none
		sourceColumn: CID_INTERNADO

		annotation SummarizationSetBy = Automatic

	column NR_ATENDIMENTO_INT
		dataType: int64
		lineageTag: 50582d0e-5cd6-4d7b-a79e-031ff5ec55b6
		summarizeBy: sum
		sourceColumn: NR_ATENDIMENTO_INT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DT_INTERNACAO_DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b422b7f-6c72-40a4-9359-d530fbf27ff2
		summarizeBy: none
		sourceColumn: DT_INTERNACAO_DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MEDICO_ALTA_AJUSTADO =
			
			IF (
			    ISBLANK ( fluxo[MEDICO_ALTA] ),
			    "Sem alta médica",
			    fluxo[MEDICO_ALTA]
			)
		lineageTag: b206dc7d-4034-4b3c-bdc7-d06282fcabab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DESFECHO
		dataType: string
		lineageTag: 03235cf8-52cd-43ac-ba9f-63e856b51ae4
		summarizeBy: none
		sourceColumn: DESFECHO

		annotation SummarizationSetBy = Automatic

	column DT_DESFECHO
		dataType: dateTime
		formatString: General Date
		lineageTag: a33b4f26-d2f6-47f6-ad74-4aae109a0fe5
		summarizeBy: none
		sourceColumn: DT_DESFECHO

		variation Variation
			isDefault
			relationship: eb8182f3-4aab-47c1-8bc2-731aa220e1dc
			defaultHierarchy: LocalDateTable_d8ee344a-de18-47d6-8ede-a1429fc9010c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MEDICO_DESFECHO
		dataType: string
		lineageTag: 3a62cb35-fff7-4a36-86e4-026c15919885
		summarizeBy: none
		sourceColumn: MEDICO_DESFECHO

		annotation SummarizationSetBy = Automatic

	column USU_TRIAGEM
		dataType: string
		lineageTag: c0f69f19-6daa-4b61-94f9-561cd1a92bed
		summarizeBy: none
		sourceColumn: USU_TRIAGEM

		annotation SummarizationSetBy = Automatic

	column DT_AUDITORIA
		dataType: dateTime
		formatString: General Date
		lineageTag: 18cc9302-0a48-4cc4-9fce-aa3a34fb4212
		summarizeBy: none
		sourceColumn: DT_AUDITORIA

		variation Variation
			isDefault
			relationship: 01c45c11-588f-4699-a32f-edc17bee0e25
			defaultHierarchy: LocalDateTable_ae06fed4-5619-4c5f-8dde-07f965b922d5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MEDICO_AUDITORIA
		dataType: string
		lineageTag: bb6b7ca9-c09a-4813-9f41-87d2f2dbd333
		summarizeBy: none
		sourceColumn: MEDICO_AUDITORIA

		annotation SummarizationSetBy = Automatic

	column INTERN_CONFORME_AUDIT
		dataType: string
		lineageTag: 83ee736a-580c-4ce5-b81a-8b5560b69cd6
		summarizeBy: none
		sourceColumn: INTERN_CONFORME_AUDIT

		annotation SummarizationSetBy = Automatic

	column REALIZ_DEVOLUTIVA_AUDIT
		dataType: string
		lineageTag: 215182c6-25bc-4cb5-ada7-9c76cd3ecc48
		summarizeBy: none
		sourceColumn: REALIZ_DEVOLUTIVA_AUDIT

		annotation SummarizationSetBy = Automatic

	column DT_INICIO_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ea4d84c-d9c3-410d-a757-46869cfff0af
		summarizeBy: none
		sourceColumn: DT_INICIO_ATENDIMENTO

		variation Variation
			isDefault
			relationship: d701eb5d-0a45-4bf4-886a-29c7e3c70180
			defaultHierarchy: LocalDateTable_e49b7036-3b9d-4aca-8316-941cad72c2eb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_PA_STATUS
		dataType: int64
		formatString: 0
		lineageTag: 81d0b40b-053a-4b30-83b9-ebd59273290e
		summarizeBy: sum
		sourceColumn: NR_SEQ_PA_STATUS

		annotation SummarizationSetBy = Automatic

	column DT_EVOLUCAO
		dataType: dateTime
		formatString: General Date
		lineageTag: fea7ff4e-2570-48bb-a8bc-217514c7aa58
		summarizeBy: none
		sourceColumn: DT_EVOLUCAO

		variation Variation
			isDefault
			relationship: d43c9171-6323-44d6-8f8e-beb081802252
			defaultHierarchy: LocalDateTable_c115c671-e75b-4dff-a343-abfbdf8379be.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column TURNO_ATENDIMENTO
		dataType: string
		lineageTag: 4d1b65d1-db1b-4a3d-96d6-0f712d0c41d6
		summarizeBy: none
		sourceColumn: TURNO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column TURNO_DESFECHO
		dataType: string
		lineageTag: 2d7ca8bd-b622-45c7-9107-1e4b78cc2e4f
		summarizeBy: none
		sourceColumn: TURNO_DESFECHO

		annotation SummarizationSetBy = Automatic

	column HR_DESFECHO = FORMAT([DT_DESFECHO], "HH:00")
		lineageTag: a0ff812d-e93b-481d-8446-a09f55532374
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DATA_DESFECHO =
			
			DATE ( YEAR ( fluxo[DT_DESFECHO] ), MONTH ( fluxo[DT_DESFECHO] ), DAY ( fluxo[DT_DESFECHO] ) )
		formatString: Short Date
		lineageTag: 1e9e041f-77c4-4633-99f2-09f59933575b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fluxo = m
		mode: import
		source = ```
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_tbl_tempos_entrada_consulta_saida = Fonte{[Schema="cmc_hospital",Item="tbl_tempos_entrada_consulta_saida"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"cmc_hospital_tbl_tempos_entrada_consulta_saida",{{"UNIDADE", type text}, {"NR_ATENDIMENTO", Int64.Type}, {"PACIENTE", type text}, {"DT_ENTRADA", type datetime}, {"DT_TRIAGEM", type datetime}, {"DT_FIM_TRIAGEM", type datetime}, {"DT_ATEND_MEDICO", type datetime}, {"DT_ALTA", type datetime}, {"MIN_ENTRADA_X_TRIAGEM", type number}, {"MIN_ENTRADA_X_CONSULTA", type number}, {"MIN_ENTRADA_X_ALTA", type number}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Tipo Alterado", "DT_ENTRADA", "DT_ENTRADA - Copiar"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Duplicada",{{"DT_ENTRADA - Copiar", type date}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado1",{"UNIDADE", "NR_ATENDIMENTO", "PACIENTE", "DT_ENTRADA - Copiar", "DT_ENTRADA", "DT_TRIAGEM", "DT_FIM_TRIAGEM", "DT_ATEND_MEDICO", "DT_ALTA", "MIN_ENTRADA_X_TRIAGEM", "MIN_ENTRADA_X_CONSULTA", "MIN_ENTRADA_X_ALTA"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Reordenadas","Medsenior ","",Replacer.ReplaceText,{"UNIDADE"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído",{{"DATA", type date}, {"IDADE", Int64.Type}}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Tipo Alterado2",null,"NÃO INFORMADO",Replacer.ReplaceValue,{"PRIORIDADE"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",null,"NÃO INFORMADO",Replacer.ReplaceValue,{"COR"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Valor Substituído2",{"DT_ENTRADA - Copiar"}),
				    #"Coluna Duplicada1" = Table.DuplicateColumn(#"Colunas Removidas", "DT_ALTA", "DT_ALTA - Copiar"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Duplicada1",{{"DT_ALTA - Copiar", "DT_ALTA_DATA"}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"DT_ALTA_DATA", type date}}),
				    #"Coluna Duplicada2" = Table.DuplicateColumn(#"Tipo Alterado3", "DT_INTERNACAO", "DT_INTERNACAO - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada2",{{"DT_INTERNACAO - Copiar", "DT_INTERNACAO_DATA"}}),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Renomeadas1",{"UNIDADE", "CD_ESTABELECIMENTO", "CD_PESSOA_FISICA", "NR_ATENDIMENTO", "PACIENTE", "IDADE", "SEXO", "CIDADE", "ESTADO", "LOCALIZACAO_PAC", "CD_CID", "CID", "GRUPO_CID", "COR", "PRIORIDADE", "DISCRIMINADOR", "DATA", "DT_ENTRADA", "DT_TRIAGEM", "DT_FIM_TRIAGEM", "MEDICO_ATENDIMENTO", "MEDICO_ALTA", "DT_ALTA_MEDICO", "ALTA_MEDICA", "DT_ATEND_MEDICO", "ALTA_HOSPITALAR", "DT_ALTA", "MIN_ENTRADA_X_TRIAGEM", "MIN_ENTRADA_X_CONSULTA", "DESTINO", "DT_INTERNACAO", "DT_INTERNACAO_DATA", "CID_INTERNADO", "NR_ATENDIMENTO_INT", "MIN_ENTRADA_X_ALTA", "DT_ALTA_DATA"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Reordenadas1",{{"DT_INTERNACAO_DATA", type date}, {"NR_ATENDIMENTO_INT", Int64.Type}}),
				    #"Linhas Filtradas" =
				    Table.SelectRows(
				        #"Tipo Alterado4",
				        each (try [DT_TRIAGEM] otherwise null) <> null
				          or (try [DT_INICIO_ATENDIMENTO] otherwise null) <> null
				    ),
				    #"desfecho-null-não informado" = Table.ReplaceValue(#"Linhas Filtradas",null,"Não Informado",Replacer.ReplaceValue,{"DESFECHO"}),
				    #"altahost-null- não informado" = Table.ReplaceValue(#"desfecho-null-não informado",null,"Não Informado",Replacer.ReplaceValue,{"ALTA_HOSPITALAR"})
				  
				
				in
				    #"altahost-null- não informado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

