table 'Meta dinâm volume media desfechos 10-16h'
	lineageTag: 9c1af85f-0490-4494-b6d4-deb170c20214

	measure 'Valor Meta dinâm volume media desfechos 10-16h' = SELECTEDVALUE('Meta dinâm volume media desfechos 10-16h'[Meta dinâm volume media desfechos 10-16h])
		lineageTag: 2c4f05eb-62d3-4d7f-86a5-498950870800

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta dinâm volume media desfechos 10-16h'
		formatString: 0.0
		lineageTag: d5ed5979-a274-4137-919b-505df807997b
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta dinâm volume media desfechos 10-16h' = calculated
		mode: import
		source = GENERATESERIES(0, 20, 0.1)

	annotation PBI_Id = 0f767452e0944b84b2987adae585be1f

