table 'Metas tipo_TC_US'
	lineageTag: a2a00448-3080-41b9-a338-dc50e2b6f99d

	measure 'Valor Meta_TC_US' = SELECTEDVALUE('Metas tipo_TC_US'[Tempo minutos])
		formatString: 0
		lineageTag: 3a1d9470-d937-4947-8c68-37856e4da8db

	column 'Tempo minutos'
		formatString: 0
		lineageTag: 1a49df82-dd9e-4898-bcd0-82f613757eed
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Metas tipo_TC_US' = calculated
		mode: import
		source = GENERATESERIES(0, 300, 1)

	annotation PBI_Id = f311b911780d47a0bb2bf059bc207243

