table 'Meta dinâm volume medicações por pac'
	lineageTag: 13bee02f-0d74-45d1-8b82-bcf9a4b2d527

	measure 'Valor Meta dinâm volume medicações por pac' = SELECTEDVALUE('Meta dinâm volume medicações por pac'[Meta dinâm volume medicações por pac])
		lineageTag: 3419da03-bd6e-4c62-ac80-fa8fac98dd1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta dinâm volume medicações por pac'
		lineageTag: 9b9172f8-7678-4d49-bf7b-f2bfb1fff706
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Meta dinâm volume medicações por pac' = calculated
		mode: import
		source = GENERATESERIES(0, 5.01, 0.001)

	annotation PBI_Id = e7105e62b13d40fe85e1c41422b079f2

