table Meta_ECG_RX
	lineageTag: b590c100-6cd3-4861-b738-e5699a357402

	measure 'Valor Tempo Minutos' = SELECTEDVALUE('Meta_ECG_RX'[Tempo Minutos])
		formatString: 0
		lineageTag: c170a401-c2a0-4074-a431-9ebe7ed29b7a

	column 'Tempo Minutos'
		formatString: 0
		lineageTag: 65e0107e-b4ed-4694-baa3-8437f2317c33
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Meta_ECG_RX = calculated
		mode: import
		source = GENERATESERIES(0, 120, 1)

	annotation PBI_Id = b84190cca77c4d17ab3e610d6cdb72d1

