table reavaliacao
	lineageTag: 085269b6-e731-4c05-b9b9-0384b6766570

	column UNIDADE
		dataType: string
		lineageTag: 6da7759d-6e91-41c0-aaa2-5ea5fd0aab81
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column NR_ATENDIMENTO
		dataType: int64
		formatString: 0
		lineageTag: 26e49eb0-b165-411e-9b7e-f3028e34318a
		summarizeBy: none
		sourceColumn: NR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column PACIENTE
		dataType: string
		lineageTag: 1cd95087-eaa9-431e-a748-269cd8080304
		summarizeBy: none
		sourceColumn: PACIENTE

		annotation SummarizationSetBy = Automatic

	column DT_SOLIC_REAVALIACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: 60f1490e-41c6-4feb-bae6-6b20e801f643
		summarizeBy: none
		sourceColumn: DT_SOLIC_REAVALIACAO

		variation Variation
			isDefault
			relationship: 8515bf79-b2da-4a1a-856d-6028b8252c38
			defaultHierarchy: LocalDateTable_bd9098e4-f3cc-45d2-a1a4-0cc664e368bc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_FIM_REAVALIACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: d593cc1d-6efd-4bdb-9c7f-468c56245218
		summarizeBy: none
		sourceColumn: DT_FIM_REAVALIACAO

		variation Variation
			isDefault
			relationship: b72bf84e-bb42-431d-84ae-65794f00028b
			defaultHierarchy: LocalDateTable_c0aa2862-abd0-4600-a311-929d22f622ee.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MINUTOS
		dataType: double
		lineageTag: 843280b0-92b8-4921-a1be-809c19704352
		summarizeBy: sum
		sourceColumn: MINUTOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HORAS
		dataType: double
		lineageTag: 8b7f6d06-5ab2-459f-a332-5b52a6ccde97
		summarizeBy: sum
		sourceColumn: HORAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad5528fe-cc0e-43f5-a391-afde518af501
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: d7e036ea-8a08-4758-96da-bff89d756e32
			defaultHierarchy: LocalDateTable_21376ba9-98ce-42c5-92a0-d11ee22b5e74.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HR_REAVALIACAO = FORMAT(reavaliacao[DT_SOLIC_REAVALIACAO],"HH:00")
		lineageTag: a782f92e-7606-4a46-a322-3d71a664cba1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MEDICO
		dataType: string
		lineageTag: c65ae849-dbd8-42a1-9745-d7a48f13dec9
		summarizeBy: none
		sourceColumn: MEDICO

		annotation SummarizationSetBy = Automatic

	column MEDICO_ALTA_MEDICA
		dataType: string
		lineageTag: 01293c73-27d7-4ec3-be44-b8b4382a3f18
		summarizeBy: none
		sourceColumn: MEDICO_ALTA_MEDICA

		annotation SummarizationSetBy = Automatic

	column PESSOA_REAVALIACAO
		dataType: string
		lineageTag: 95f5c334-fa9e-48eb-ada0-5840e2d335d6
		summarizeBy: none
		sourceColumn: PESSOA_REAVALIACAO

		annotation SummarizationSetBy = Automatic

	column CD_ESTABELECIMENTO
		dataType: double
		lineageTag: 59827a90-52c5-4eb2-ac90-a456e5f4b391
		summarizeBy: sum
		sourceColumn: CD_ESTABELECIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DT_EVO_PRESC
		dataType: dateTime
		formatString: General Date
		lineageTag: a2042069-8a3d-486a-927f-678e9e2225eb
		summarizeBy: none
		sourceColumn: DT_EVO_PRESC

		variation Variation
			isDefault
			relationship: 5842da30-afe4-4cff-92ac-f35bda7970d4
			defaultHierarchy: LocalDateTable_18e9dfe9-c554-482d-a009-5b492643aa9e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MEDICO_EVO_PRESC
		dataType: string
		lineageTag: d8178da1-361c-4a00-b48c-c1fd15d05df0
		summarizeBy: none
		sourceColumn: MEDICO_EVO_PRESC

		annotation SummarizationSetBy = Automatic

	column Min_evolu_reav =
			
			VAR DtIni = reavaliacao[DT_SOLIC_REAVALIACAO]
			VAR DtEvo = reavaliacao[DT_EVO_PRESC]
			VAR DtFim = reavaliacao[DT_FIM_REAVALIACAO]
			VAR DtRef =
			    SWITCH (
			        TRUE (),
			        ISBLANK ( DtEvo ) && ISBLANK ( DtFim ), BLANK (),
			        ISBLANK ( DtEvo ), DtFim,
			        ISBLANK ( DtFim ), DtEvo,
			        DtEvo <= DtFim, DtEvo,
			        DtFim
			    )
			RETURN
			IF (
			    ISBLANK ( DtIni ) || ISBLANK ( DtRef ),
			    BLANK (),
			    DATEDIFF ( DtIni, DtRef, MINUTE )
			)
		formatString: 0
		lineageTag: 4be8c730-3fbc-4d81-a7f9-923610d52341
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column USU_SOLIC_REAVALIACAO
		dataType: string
		lineageTag: e5114ec8-557f-4c4b-a37c-6c689367438b
		summarizeBy: none
		sourceColumn: USU_SOLIC_REAVALIACAO

		annotation SummarizationSetBy = Automatic

	partition reavaliacao = m
		mode: import
		source = ```
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_tbl_tempos_reavaliacao = 
				        Fonte{[Schema="cmc_hospital", Item="tbl_tempos_reavaliacao"]}[Data],
				
				    #"Tipo Alterado" = 
				        Table.TransformColumnTypes(
				            cmc_hospital_tbl_tempos_reavaliacao,
				            {
				                {"UNIDADE", type text},
				                {"NR_ATENDIMENTO", Int64.Type},
				                {"PACIENTE", type text},
				                {"DT_SOLIC_REAVALIACAO", type datetime},
				                {"DT_FIM_REAVALIACAO", type datetime},
				                {"MINUTOS", type number},
				                {"HORAS", type number},
				                {"DATA", type date},
				                {"PESSOA_REAVALIACAO", type text}
				            }
				        ),
				
				    #"Remove Nulos Pessoa Reavaliacao" =
				        Table.SelectRows(
				            #"Tipo Alterado",
				            each [PESSOA_REAVALIACAO] <> null
				        )
				in
				    #"Remove Nulos Pessoa Reavaliacao"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

