table 'Meta taxa de mortalidade UTI'
	lineageTag: 9280fa87-7655-438d-8146-76eb23f1276c

	measure 'Valor Meta taxa de mortalidade UTI' = SELECTEDVALUE('Meta taxa de mortalidade UTI'[Meta taxa de mortalidade UTI])
		lineageTag: b3df8422-f540-471d-b69a-5801b192e52c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta taxa de mortalidade UTI'
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 11a973c5-255b-489b-a89a-a94211b71fae
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta taxa de mortalidade UTI' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = ee288b2e0f7d46c484f7b90fbd25db4b

