table 'Meta reinternação 30d'
	lineageTag: fe13accc-d503-4637-bc06-c037d36da2d3

	measure 'Valor Meta reinternação 30d' = SELECTEDVALUE('Meta reinternação 30d'[Meta reinternação 30d])
		lineageTag: 57d35524-0ace-4b4e-acf7-c7b8463d42af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta reinternação 30d'
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 40cd6798-6bd7-4bce-a008-60976ebdb233
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta reinternação 30d' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = 9cbfc5335c12491fac0cb6e96a684cea

