table Movimentacao_pac
	lineageTag: 78958a99-8928-48f9-a958-aafff2de0ee6

	column CD_ESTABELECIMENTO
		dataType: double
		lineageTag: 2959ebe1-a744-4415-8a75-a0e9834f16f4
		summarizeBy: sum
		sourceColumn: CD_ESTABELECIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDADE
		dataType: string
		lineageTag: c2d071d4-0060-4275-a399-200b19390e77
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column NR_ATENDIMENTO
		dataType: int64
		lineageTag: b90dda47-02ce-49b3-9bba-e5e8cfef9794
		summarizeBy: none
		sourceColumn: NR_ATENDIMENTO

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NM_ABREVIADO
		dataType: string
		lineageTag: b4e6955d-e6ba-48bc-b24e-ad1780b3b6f3
		summarizeBy: none
		sourceColumn: NM_ABREVIADO

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: a10dcbed-ff4d-460d-ac87-530c0d9c7fe6
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column DT_ENTRADA
		dataType: dateTime
		formatString: General Date
		lineageTag: a17aa1c4-52ea-4ca4-aca8-c9158c1d7b95
		summarizeBy: none
		sourceColumn: DT_ENTRADA

		variation Variation
			isDefault
			relationship: 9b8de2f6-69cc-4e86-b0ad-af528f28a14e
			defaultHierarchy: LocalDateTable_2674d5dd-4532-4da9-bccc-ff7759d53350.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_ALTA
		dataType: dateTime
		formatString: General Date
		lineageTag: 98099dd8-6c9d-4d87-b6b0-fe9a076fdf16
		summarizeBy: none
		sourceColumn: DT_ALTA

		variation Variation
			isDefault
			relationship: d51d30a3-05f4-4b7e-8884-025bca970346
			defaultHierarchy: LocalDateTable_5f6fe630-698e-4e81-819f-7da9ab9218eb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column HR_HISTORICO
		dataType: dateTime
		formatString: General Date
		lineageTag: e86a5369-62fd-47ed-8cd1-342321b7eb69
		summarizeBy: none
		sourceColumn: HR_HISTORICO

		variation Variation
			isDefault
			relationship: 2dfd5242-0a94-4755-809a-ca3a6d900b1e
			defaultHierarchy: LocalDateTable_c6034a3e-9ada-432d-b3ad-beafc130372f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_HISTORICO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 26e55b4f-93ca-4758-8c9b-880c8ecf896f
		summarizeBy: none
		sourceColumn: DT_HISTORICO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HR_FIM_HISTORICO
		dataType: dateTime
		formatString: General Date
		lineageTag: 9629e663-872f-4ae1-991f-6679f83ec6f6
		summarizeBy: none
		sourceColumn: HR_FIM_HISTORICO

		variation Variation
			isDefault
			relationship: 96620dec-71dd-4695-a085-0f0845c382c7
			defaultHierarchy: LocalDateTable_56a8fca1-2021-4f3e-ab61-a2711cc3c940.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_FIM_HISTORICO
		dataType: dateTime
		formatString: Long Date
		lineageTag: a78675f6-c6f9-49ef-b1ff-5a793025ad10
		summarizeBy: none
		sourceColumn: DT_FIM_HISTORICO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CD_SETOR_ATENDIMENTO
		dataType: double
		lineageTag: efbc35a2-6983-4702-b867-232555b76c12
		summarizeBy: sum
		sourceColumn: CD_SETOR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SETOR
		dataType: string
		lineageTag: d7b40220-3c3f-4b2d-9ccd-86079b4e36f7
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column CD_TIPO_ACOMODACAO
		dataType: double
		lineageTag: 4f3585e1-1abe-4dea-9618-837115febd26
		summarizeBy: sum
		sourceColumn: CD_TIPO_ACOMODACAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DT_CARGA
		dataType: dateTime
		formatString: General Date
		lineageTag: fc049605-ef01-4003-bac9-14f2cbf76cb3
		summarizeBy: none
		sourceColumn: DT_CARGA

		variation Variation
			isDefault
			relationship: f962791f-9895-4027-b656-33e9aaabc8eb
			defaultHierarchy: LocalDateTable_a8a5f367-a24e-4acb-869e-0aa7c0254c57.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column TP_ATENDIMENTO
		dataType: string
		lineageTag: db76b7aa-5e03-4995-94b8-37cedbb1afe5
		summarizeBy: none
		sourceColumn: TP_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DS_CLASSIFICACAO
		dataType: string
		lineageTag: 9137cc8a-23e6-44b7-8f69-0ec46acfaad6
		summarizeBy: none
		sourceColumn: DS_CLASSIFICACAO

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: b369e66e-8465-417e-8c0c-1c2999f73e72
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 8f6c7f7d-39ec-419f-afd1-2c41fbef8f03
			defaultHierarchy: LocalDateTable_768f670a-f06c-4a54-8421-3ded0196b25b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CD_UNIDADE_ATENDIMENTO
		dataType: string
		lineageTag: 6b22d7ed-60ba-4aab-be9f-5318becd1cb6
		summarizeBy: none
		sourceColumn: CD_UNIDADE_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column ProxInicioMov = ```
			
			VAR pid = Movimentacao_pac[NR_ATENDIMENTO]
			VAR ini = Movimentacao_pac[HR_HISTORICO]
			RETURN
			CALCULATE(
			    MIN(Movimentacao_pac[HR_HISTORICO]),
			    FILTER(
			        ALL(Movimentacao_pac),
			        Movimentacao_pac[NR_ATENDIMENTO] = pid 
			            && Movimentacao_pac[HR_HISTORICO] > ini 
			    )
			)
			```
		formatString: General Date
		lineageTag: f3552ba7-ea01-4901-9299-22dcba8dbb4f
		summarizeBy: none

		variation Variation
			isDefault
			relationship: b296730a-df0b-45d6-9d3d-03433644c94f
			defaultHierarchy: LocalDateTable_7d5c57a6-c497-4411-b8ba-0d5f67288738.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ProxClassMov =
			
			VAR pid = Movimentacao_pac[NR_ATENDIMENTO]
			VAR proxIni = Movimentacao_pac[ProxInicioMov]
			RETURN
			CALCULATE(
			    SELECTEDVALUE(Movimentacao_pac[CLASSIFICACAO]),
			    FILTER(
			        ALL(Movimentacao_pac),
			        Movimentacao_pac[NR_ATENDIMENTO] = pid
			            && Movimentacao_pac[HR_HISTORICO] = proxIni
			    )
			)
		lineageTag: 1053aaa7-e0fe-4d83-84b9-6565bdbb43f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_BASICA
		dataType: string
		lineageTag: a9b7b220-4a34-43e6-a5a7-5729fb03acfa
		summarizeBy: none
		sourceColumn: CD_UNIDADE_BASICA

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_COMPL
		dataType: string
		lineageTag: 43115934-da59-45f6-8934-c02057cd77e4
		summarizeBy: none
		sourceColumn: CD_UNIDADE_COMPL

		annotation SummarizationSetBy = Automatic

	column LEITO
		dataType: string
		lineageTag: 59206a50-fd89-4a74-bcb0-d1c6a5df1e9c
		summarizeBy: none
		sourceColumn: LEITO

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAO
		dataType: string
		lineageTag: 56bfb597-a3bf-4c59-9241-1d9a47ecf32a
		summarizeBy: none
		sourceColumn: CLASSIFICACAO

		annotation SummarizationSetBy = Automatic

	column UTI_Alta_Evento =
			
			VAR ClassAtual = TRIM(UPPER(Movimentacao_pac[CLASSIFICACAO]))
			VAR ProxClass  = TRIM(UPPER(Movimentacao_pac[ProxClassMov]))
			RETURN
			IF(
			    ClassAtual IN { "UTI", "UPC", "UTI EXTRA" }
			        && (
			            ISBLANK(Movimentacao_pac[ProxInicioMov])
			            || ISBLANK(ProxClass)
			            || NOT ( ProxClass IN { "UTI", "UPC", "UTI EXTRA" } )
			        ),
			    1,
			    0
			)
		formatString: 0
		lineageTag: a1e5a118-5e35-483a-935c-150ce3fff713
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ProxEntradaUTI_AposAlta = ```
			
			VAR pid = Movimentacao_pac[NR_ATENDIMENTO]
			VAR saida = Movimentacao_pac[HR_FIM_HISTORICO]
			RETURN
			IF(
			    Movimentacao_pac[UTI_Alta_Evento] = 1
			        && NOT ISBLANK(saida),
			    CALCULATE(
			        MIN(Movimentacao_pac[HR_HISTORICO]),
			        FILTER(
			            ALL(Movimentacao_pac),
			            Movimentacao_pac[NR_ATENDIMENTO] = pid  
			                && Movimentacao_pac[CLASSIFICACAO] IN {"UTI","UPC","UTI EXTRA"}
			                && Movimentacao_pac[HR_HISTORICO] > saida
			        )
			    )
			)
			```
		formatString: General Date
		lineageTag: 6f920f95-bc45-4adf-9b3e-841a40e86c66
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 843bda75-df6e-4486-8c17-f864d46a3cb6
			defaultHierarchy: LocalDateTable_db04c865-7ebc-4d1f-aee2-57613a31586d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ReinternouUTI_48h =
			
			VAR proxUTI = Movimentacao_pac[ProxEntradaUTI_AposAlta]
			VAR saida   = Movimentacao_pac[HR_FIM_HISTORICO]
			RETURN
			IF(
			    Movimentacao_pac[UTI_Alta_Evento] = 1
			        && NOT ISBLANK(saida)
			        && NOT ISBLANK(proxUTI)
			        && proxUTI <= saida + (48/24),
			    1,
			    0
			)
		formatString: 0
		lineageTag: dc64e95a-ddaf-4900-b9e1-ba020b172960
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column UTI_inicio_permanencia =
			
			VAR pid = Movimentacao_pac[NR_ATENDIMENTO]
			VAR fim = Movimentacao_pac[HR_FIM_HISTORICO]
			VAR fimAnterior =
			    CALCULATE(
			        MAX(Movimentacao_pac[HR_FIM_HISTORICO]),
			        FILTER(
			            ALL(Movimentacao_pac),
			            Movimentacao_pac[NR_ATENDIMENTO] = pid
			                && Movimentacao_pac[UTI_Alta_Evento] = 1
			                && Movimentacao_pac[HR_FIM_HISTORICO] < fim
			        )
			    )
			RETURN
			IF(
			    Movimentacao_pac[UTI_Alta_Evento] = 1 && NOT ISBLANK(fim),
			    CALCULATE(
			        MIN(Movimentacao_pac[HR_HISTORICO]),
			        FILTER(
			            ALL(Movimentacao_pac),
			            Movimentacao_pac[NR_ATENDIMENTO] = pid
			                && TRIM(UPPER(Movimentacao_pac[CLASSIFICACAO])) IN { "UTI", "UPC", "UTI EXTRA" }
			                && Movimentacao_pac[HR_HISTORICO] <= fim
			                && ( ISBLANK(fimAnterior) || Movimentacao_pac[HR_HISTORICO] > fimAnterior )
			        )
			    )
			)
		formatString: General Date
		lineageTag: ff35d593-6602-4160-9671-879202ced322
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 0fc4fc4b-c7e3-41ac-a16a-9b995162d163
			defaultHierarchy: LocalDateTable_4944da9f-030a-4a21-b5f4-a94e11f74d8d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column UTI_tempo_permanencia_horas =
			
			VAR ini = Movimentacao_pac[UTI_inicio_permanencia]
			VAR fim = Movimentacao_pac[HR_FIM_HISTORICO]
			RETURN
			IF(
			    Movimentacao_pac[UTI_Alta_Evento] = 1
			        && NOT ISBLANK(ini)
			        && NOT ISBLANK(fim),
			    DIVIDE( DATEDIFF(ini, fim, MINUTE), 60 )
			)
		lineageTag: a277f4f8-990e-4bf9-bd7e-362152eba82a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UTI_tempo_permanencia_dias =
			
			DIVIDE(Movimentacao_pac[UTI_tempo_permanencia_horas], 24)
		lineageTag: 4122f694-3258-44b4-860d-208857b9ca72
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CD_LEITO
		dataType: double
		lineageTag: 5ee6a88b-cf28-4e50-b2b7-f9183fa8e785
		summarizeBy: sum
		sourceColumn: CD_LEITO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Movimentacao_pac = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_intern_movimentacoes = Fonte{[Schema="cmc_hospital", Item="tbl_intern_movimentacoes"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(cmc_hospital_intern_movimentacoes,{"DATA"}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Colunas Removidas", "DT_ENTRADA", "DT_ENTRADA - Copiar"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Duplicada",{{"DT_ENTRADA - Copiar", "DATA"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"DT_HISTORICO", type date}, {"DT_FIM_HISTORICO", type date}, {"DATA", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

