table Calendario
	lineageTag: af1ccea3-b589-47e3-a4d4-135f73efc74a

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c4c3e04-8347-41e1-afff-7c6f4d48e675
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 8b78513d-1d76-4840-9def-3f34460ee0b6
			defaultHierarchy: LocalDateTable_fe66b504-cae0-4f15-97ee-10c54f00595e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: f88d9345-e1b4-45af-9d37-2d48628c5381
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 80c8d1fa-0be1-401d-8b2f-166a6d095a0a
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome Mês'
		dataType: string
		lineageTag: 0fd73e3e-44c2-4eaa-8027-8ccf65b14253
		summarizeBy: none
		sourceColumn: Nome Mês
		sortByColumn: Mês

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 839d4c61-96a8-44b2-a62e-415e0194cd80
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: e1ededb4-ac60-4d35-bc37-e0c8b29be406
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: int64
		formatString: 0
		lineageTag: 0c382c5d-82b0-4bea-9669-5a27bc412db0
		summarizeBy: sum
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'Nome Dia Semana'
		dataType: string
		lineageTag: c7031fb2-c1cc-4fbc-af19-d7095524f168
		summarizeBy: none
		sourceColumn: Nome Dia Semana
		sortByColumn: 'Dia da Semana'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'É Final de Semana?'
		dataType: string
		lineageTag: bd8e6629-3b00-4469-90fc-3dd0dde9e3d6
		summarizeBy: none
		sourceColumn: É Final de Semana?

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 2a3cda7c-a3e4-4512-a62c-024960f71a30
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Mes e Ano'
		dataType: string
		lineageTag: 0e023730-eb93-4487-8e07-4709ed711cf3
		summarizeBy: none
		sourceColumn: Mes e Ano
		sortByColumn: 'Ano Mes Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Ano Mes Num'
		dataType: int64
		formatString: 0
		lineageTag: 0ddb9d29-41b7-4c40-a56c-7c18ad8d3b55
		summarizeBy: sum
		sourceColumn: Ano Mes Num

		annotation SummarizationSetBy = Automatic

	column 'Nome Feriado'
		dataType: string
		lineageTag: 17ea5aa7-b1d0-45fa-a37b-37c98e93f956
		summarizeBy: none
		sourceColumn: Nome Feriado

		annotation SummarizationSetBy = Automatic

	column 'É Feriado?'
		dataType: string
		lineageTag: a3087dc0-6b32-4b46-89d4-c0571ac489db
		summarizeBy: none
		sourceColumn: É Feriado?

		annotation SummarizationSetBy = Automatic

	column EhMesFechado = ```
			
			VAR PrimeiroDiaMesAtual =
			    DATE ( YEAR ( TODAY() ), MONTH ( TODAY() ), 1 )
			RETURN
			    IF (
			        'Calendario'[Data] < PrimeiroDiaMesAtual,
			        "Sim",    // Se a data for anterior ao primeiro dia do mês atual
			        "Não"     // Caso contrário
			    )
			
			
			```
		lineageTag: 04c3c62a-6042-4580-82b2-239295fc060c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Semana Início' = 'Calendario'[Data] - WEEKDAY('Calendario'[Data], 1) + 1
		formatString: Short Date
		lineageTag: 2a2a9028-b68f-4ca5-bf91-351d375d8193
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 57e2109d-5dfc-49d6-a7f2-54035e0ba8c1
			defaultHierarchy: LocalDateTable_99bc953c-a6f4-430e-a844-e718ad7d2765.'Hierarquia de datas'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Semana Fim' = 'Calendario'[Semana Início] + 6
		formatString: Short Date
		lineageTag: e67479e7-5bc3-4518-bf2b-9c98d079dc56
		summarizeBy: none

		variation Variation
			isDefault
			relationship: d28c9b02-d26b-425b-89f4-2d6bb1592f99
			defaultHierarchy: LocalDateTable_ad9f4c65-42d3-4fd8-93dc-76c960f38e6b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Semana (rótulo)' = ```
			
			    FORMAT('Calendario'[Semana Início], "dd/MM") 
			    & " a " 
			    & FORMAT('Calendario'[Semana Fim], "dd/MM")
			```
		lineageTag: 84b9fd43-13b9-44de-a109-e77fc66bffe9
		summarizeBy: none
		sortByColumn: AnoSemana_Ord

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AnoSemana =
			
			VAR Inicio = 'Calendario'[Semana Início]
			RETURN
			    YEAR(Inicio) * 100 + WEEKNUM(Inicio, 1)   -- 1 = semana começa no domingo
		lineageTag: c08cc3a5-2c31-4f72-9e19-16075269c513
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Semana do Ano' =
			
			WEEKNUM ( 'Calendario'[Semana Início], 1 )   -- 1 = semana começa no domingo
		formatString: 0
		lineageTag: 268fa7fa-5b13-4363-93db-79d9ae27bf84
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column AnoSemana_Ord =
			
			VAR Inicio = 'Calendario'[Semana Início]
			RETURN
			    YEAR(Inicio) * 100 + WEEKNUM(Inicio, 1)   -- 1 = semana começa no domingo
		formatString: 0
		lineageTag: 7db8e0af-e691-4b59-85f5-17f6a91ca53a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column InicioMes = DATE(YEAR('Calendario'[Data]), MONTH('Calendario'[Data]), 1)
		formatString: General Date
		lineageTag: bedb1b58-c18d-4e96-888c-c35bd312aec5
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 3f809bab-1298-4ed1-b6b5-a8474190ecaa
			defaultHierarchy: LocalDateTable_093e9804-aa0a-4554-922b-d50c98cb7434.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source = ```
				let
				    // Datas de início e fim
				    DataInicio = #date(2025, 1, 1),
				    DataFim = #date(Date.Year(DateTime.LocalNow()), 12, 31),
				 
				    // Lista de datas
				    ListaDatas = List.Dates(DataInicio, Duration.Days(Duration.From(DataFim - DataInicio)) + 1, #duration(1, 0, 0, 0)),
				    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				 
				    // Adiciona colunas úteis
				    DatasComAno = Table.AddColumn(TabelaDatas, "Ano", each Date.Year([Data]), Int64.Type),
				    DatasComMes = Table.AddColumn(DatasComAno, "Mês", each Date.Month([Data]), Int64.Type),
				    DatasComNomeMes = Table.AddColumn(DatasComMes, "Nome Mês", each Date.ToText([Data], "MMMM"), type text),
				    DatasComTrimestre = Table.AddColumn(DatasComNomeMes, "Trimestre", each "T" & Number.ToText(Date.QuarterOfYear([Data])), type text),
				    DatasComSemestre = Table.AddColumn(DatasComTrimestre, "Semestre", each "S" & Number.ToText(Number.RoundUp(Date.QuarterOfYear([Data]) / 2)), type text),
				    DatasComDiaSemana = Table.AddColumn(DatasComSemestre, "Dia da Semana", each Date.DayOfWeek([Data]) + 1, Int64.Type),
				    DatasComNomeDiaSemana = Table.AddColumn(DatasComDiaSemana, "Nome Dia Semana", each Text.Proper(Date.ToText([Data], "dddd")), type text),
				    DatasComFinalSemana = Table.AddColumn(DatasComNomeDiaSemana, "É Final de Semana?", each if List.Contains({0, 6}, Date.DayOfWeek([Data])) then "Sim" else "Não", type text),
				    DatasComDia = Table.AddColumn(DatasComFinalSemana, "Dia", each Date.Day([Data]), Int64.Type),
				    DatasComMesAno = Table.AddColumn(DatasComDia, "Mes e Ano", each Text.Combine({Text.Start(Text.Proper([Nome Mês]), 3), " ", Text.From([Ano], "pt-BR")}), type text),
				    DatasComAnoMesNum = Table.AddColumn(DatasComMesAno, "Ano Mes Num", each Text.Combine({Text.From([Ano], "pt-BR"), Text.PadStart(Text.From([Mês], "pt-BR"), 2, "0")}), type text),
				    DatasComAnoMesNumTipo = Table.TransformColumnTypes(DatasComAnoMesNum,{{"Ano Mes Num", Int64.Type}}),
				 
				    // Geração automática dos feriados fixos
				    Anos = {2025..Date.Year(DateTime.LocalNow())},
				    FeriadosFixos = Table.Combine(
				        List.Transform(Anos, each
				            let
				                ano = _,
				                feriados = {
				                    {#date(ano, 1, 1), "Confraternização Universal"},
				                    {#date(ano, 4, 21), "Tiradentes"},
				                    {#date(ano, 5, 1), "Dia do Trabalho"},
				                    {#date(ano, 9, 7), "Independência do Brasil"},
				                    {#date(ano, 10, 12), "Nossa Senhora Aparecida"},
				                    {#date(ano, 11, 2), "Finados"},
				                    {#date(ano, 11, 15), "Proclamação da República"},
				                    {#date(ano, 11, 20), "Dia da Consciência Negra"},
				                    {#date(ano, 12, 25), "Natal"}
				                }
				            in
				                Table.FromRows(feriados, {"Data", "Nome Feriado"})
				        )
				    ),
				 
				    // Feriados móveis
				    CalcularFeriadosMoveis = (ano as number) as table =>
				        let
				            a = Number.Mod(ano, 19),
				            b = Number.IntegerDivide(ano, 100),
				            c = Number.Mod(ano, 100),
				            d = Number.IntegerDivide(b, 4),
				            e = Number.Mod(b, 4),
				            f = Number.IntegerDivide(b + 8, 25),
				            g = Number.IntegerDivide(b - f + 1, 3),
				            h = Number.Mod(19 * a + b - d - g + 15, 30),
				            i = Number.IntegerDivide(c, 4),
				            k = Number.Mod(c, 4),
				            l = Number.Mod(32 + 2 * e + 2 * i - h - k, 7),
				            m = Number.IntegerDivide(a + 11 * h + 22 * l, 451),
				            mesPascoa = Number.IntegerDivide(h + l - 7 * m + 114, 31),
				            diaPascoa = Number.Mod(h + l - 7 * m + 114, 31) + 1,
				            dataPascoa = #date(ano, mesPascoa, diaPascoa),
				            feriadosMoveis = {
				                {Date.AddDays(dataPascoa, -47), "Carnaval"},
				                {Date.AddDays(dataPascoa, -2), "Sexta-feira Santa"},
				                {dataPascoa, "Páscoa"},
				                {Date.AddDays(dataPascoa, 60), "Corpus Christi"}
				            }
				        in
				            Table.FromRows(feriadosMoveis, {"Data", "Nome Feriado"}),
				 
				    FeriadosMoveis = Table.Combine(List.Transform(Anos, each CalcularFeriadosMoveis(_))),
				    TodosFeriados = Table.Combine({FeriadosFixos, FeriadosMoveis}),
				
				    // 1 linha por Data (evita duplicar o calendário)
				    TodosFeriadosAgrupado =
				        Table.Group(
				            TodosFeriados,
				            {"Data"},
				            {{"Nome Feriado", each Text.Combine(List.Distinct([Nome Feriado]), " / "), type text}}
				        ),
				
				    // Join com calendário
				    D_CalendarioFinal = Table.NestedJoin(DatasComAnoMesNumTipo, "Data", TodosFeriadosAgrupado, "Data", "Feriado", JoinKind.LeftOuter),
				    ExpandirFeriados = Table.ExpandTableColumn(D_CalendarioFinal, "Feriado", {"Nome Feriado"}, {"Nome Feriado"}),
				    D_CalendarioCompleta = Table.AddColumn(ExpandirFeriados, "É Feriado?", each if [Nome Feriado] <> null then "Sim" else "Não", type text),
				    #"Tipo Alterado" = Table.TransformColumnTypes(D_CalendarioCompleta, {{"Data", type date}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

