table Medidas
	lineageTag: 65c4e9bc-1159-43f9-8c53-59fe596b717e

	measure 'Qtd Atend > Tempo RX' =
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]            -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			    FILTER (
			        'RX e ECG',
			        'RX e ECG'[Diferença Minutos RX_ECG] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: 4755861d-286f-4a4d-bdef-dea515f22d65

	measure '% Atend > Tempo RX' = ```
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			        FILTER (
			            'RX e ECG',
			            'RX e ECG'[Diferença Minutos RX_ECG] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( 'RX e ECG'[NR_PRESCRICAO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 32433ceb-040b-4c42-addb-55b101f174ba

	measure 'Qtd Atend > Tempo triagem' =
			
			VAR LimiteMinutos = Meta_triagem[Valor Meta_triagem]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( fluxo[NR_ATENDIMENTO] ),
			    FILTER (
			        fluxo,
			        fluxo[MIN_ENTRADA_X_TRIAGEM] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: TRIAGEM
		lineageTag: 06daf33c-cecc-42f5-ae5e-7ad1b82b8af0

	measure '% Atend > Tempo triagem' = ```
			
			VAR LimiteMinutos = Meta_triagem[Valor Meta_triagem]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO]),
			        FILTER (
			            fluxo,
			            fluxo[MIN_ENTRADA_X_TRIAGEM] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( fluxo[NR_ATENDIMENTO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: 6be34776-4938-4314-8d68-f5b8657b4df4

	measure 'Qtd Atend > Tempo consulta' =
			
			VAR LimiteMinutos = Meta_consulta[Valor Meta_consulta]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( fluxo[NR_ATENDIMENTO] ),
			    FILTER (
			        fluxo,
			        fluxo[MIN_ENTRADA_X_CONSULTA] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: CONSULTA
		lineageTag: 8cf5f109-f937-4677-a0ce-6c05c66b6a5e

	measure '% Atend > Tempo consulta' = ```
			
			VAR LimiteMinutos = Meta_consulta[Valor Meta_consulta]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO]),
			        FILTER (
			            fluxo,
			            fluxo[MIN_ENTRADA_X_CONSULTA] > LimiteMinutos
			        )
			    ) 
			VAR TotalAtend =
			    CALCULATE ( COUNT ( fluxo[NR_ATENDIMENTO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONSULTA
		lineageTag: 62aa413d-e0f2-42be-a79c-e8b6c80e2aa6

	measure 'Qtd Atend > Tempo medicacao' =
			
			VAR LimiteMinutos = Meta_medicacao[Valor Meta_medicacao]         -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( medicacao[NR_ATENDIMENTO] ),
			    FILTER (
			        medicacao,
			        medicacao[MINUTOS] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: cb602f9a-a266-4380-bb69-36d9ffff73cb

	measure '% Atend > Tempo medicacao' = ```
			
			VAR LimiteMinutos = Meta_medicacao[Valor Meta_medicacao]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( medicacao[NR_ATENDIMENTO]),
			        FILTER (
			            medicacao,
			            medicacao[MINUTOS] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( medicacao[NR_ATENDIMENTO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 1ff3b17a-59da-473c-992f-79234686bb2d

	measure 'Qtd Atend > Tempo TC' =
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'TC e US'[NR_PRESCRICAO]),
			    FILTER (
			        'TC e US',
			        'TC e US'[Diferença minutos TC_US] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 1c78f131-f31a-4918-a88c-39928f865b32

	measure 'Qtd Atend > Tempo reavaliacao' =
			
			VAR LimiteMinutos = [Valor Meta_reavaliacao]
			RETURN
			CALCULATE (
			    COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			    FILTER (
			        reavaliacao,
			        VAR DtIni = reavaliacao[DT_SOLIC_REAVALIACAO]
			        VAR DtEvo = reavaliacao[DT_EVO_PRESC]
			        VAR DtFim = reavaliacao[DT_FIM_REAVALIACAO]
			        VAR DtRef =
			            SWITCH (
			                TRUE (),
			                ISBLANK ( DtEvo ) && ISBLANK ( DtFim ), BLANK (),
			                ISBLANK ( DtEvo ), DtFim,
			                ISBLANK ( DtFim ), DtEvo,
			                DtEvo <= DtFim, DtEvo,
			                DtFim
			            )
			        VAR Minutos = DATEDIFF ( DtIni, DtRef, MINUTE )
			        RETURN
			            NOT ISBLANK ( DtIni )
			                && NOT ISBLANK ( DtRef )
			                && Minutos > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: REAVALIACAO
		lineageTag: d64dc5e6-1b0b-4fa0-9424-40e1249dcce8

	measure '% Atend > Tempo reavaliacao' =
			
			VAR LimiteMinutos = COALESCE ( [Valor Meta_reavaliacao], 0 )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            VAR DtIni = reavaliacao[DT_SOLIC_REAVALIACAO]
			            VAR DtEvo = reavaliacao[DT_EVO_PRESC]
			            VAR DtFim = reavaliacao[DT_FIM_REAVALIACAO]
			            VAR DtRef =
			                SWITCH (
			                    TRUE (),
			                    ISBLANK ( DtEvo ) && ISBLANK ( DtFim ), BLANK (),
			                    ISBLANK ( DtEvo ), DtFim,
			                    ISBLANK ( DtFim ), DtEvo,
			                    DtEvo <= DtFim, DtEvo,
			                    DtFim
			                )
			            VAR Minutos = DATEDIFF ( DtIni, DtRef, MINUTE )
			            RETURN
			                NOT ISBLANK ( DtIni )
			                    && NOT ISBLANK ( DtRef )
			                    && Minutos > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            NOT ISBLANK ( reavaliacao[DT_SOLIC_REAVALIACAO] )
			                && (
			                    NOT ISBLANK ( reavaliacao[DT_EVO_PRESC] )
			                        || NOT ISBLANK ( reavaliacao[DT_FIM_REAVALIACAO] )
			                )
			        )
			    )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: REAVALIACAO
		lineageTag: 531c30e4-8524-4901-8d58-eb35811dbd4c

	measure 'Qtd Atend > Tempo alta' =
			
			VAR LimiteMinutos = Meta_alta[Valor Meta_alta]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( fluxo[NR_ATENDIMENTO]),
			    FILTER (
			        fluxo,
			        fluxo[MIN_ENTRADA_X_ALTA] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: c4c8c706-ecc6-4e47-8d3d-fab69b135945

	measure '% Atend > Tempo alta' =
			
			VAR LimiteMinutos = Meta_alta[Valor Meta_alta]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO]),
			        FILTER (
			            fluxo,
			            fluxo[MIN_ENTRADA_X_ALTA] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( fluxo[NR_ATENDIMENTO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ALTA
		lineageTag: dd897935-85a3-4384-8ba7-0cfb35af5adb

	measure '% Atend > Tempo TC' = ```
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ),
			        FILTER (
			            'TC e US',
			            'TC e US'[Diferença minutos TC_US] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( 'TC e US'[NR_PRESCRICAO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: b2a3ca9c-12a9-4840-910d-a0040ca4a3b5

	measure Usuario = ```
			
			VAR _email = USERPRINCIPALNAME()
			VAR _nomeCompleto = LEFT ( _email, SEARCH ( "@", _email ) - 1 )  -- "danilo.rosemberg"
			VAR _primeiroNome = LEFT ( _nomeCompleto, SEARCH ( ".", _nomeCompleto ) - 1 )
			RETURN
			UPPER( LEFT( _primeiroNome, 1 ) ) & LOWER( MID( _primeiroNome, 2, LEN( _primeiroNome ) ) )
			
			```
		displayFolder: OUTROS
		lineageTag: 2a45e252-457e-4d8f-975a-02faaad374a8

	measure 'Qtd Atend' = DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])+0
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 86f886e0-bd60-486f-97ce-5823a48f4042

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Qtd RX_ECG' = COUNT('RX e ECG'[NR_ATENDIMENTO])
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: 85c0aca7-bd8b-4c7c-980a-210e04805c9d

	measure 'Qtd TC_US' = COUNT('TC e US'[NR_ATENDIMENTO])
		formatString: 0
		displayFolder: TC/US
		lineageTag: 61438461-27b6-40bd-9d0a-037df280c540

	measure Qtd_Prescricoes_medicamentos = COUNT(medicacao[NR_ATENDIMENTO])
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 7836525d-8991-4dc4-aa9b-4cc6004b0070

	measure 'Qtd Reavaliacoes' = COUNT(reavaliacao[NR_ATENDIMENTO])
		formatString: 0
		displayFolder: REAVALIACAO
		lineageTag: 64e8aeb3-3414-48f1-abea-eb83beb703bc

	measure Titulo = "QUANTIDADE DE " & MAX('Tabela_Parametro_Medidas'[Parametro])
		displayFolder: OUTROS
		lineageTag: 9d337479-57b7-497e-882c-71d6b312d8fa

	measure 'Qtd Triagem >12min' = (CALCULATE(COUNT(fluxo[MIN_ENTRADA_X_TRIAGEM]),fluxo[MIN_ENTRADA_X_TRIAGEM]>12))
		formatString: 0
		displayFolder: TRIAGEM
		lineageTag: 4af893bf-d1af-42ce-b043-d8996347db21

	measure 'Qtd TC_US >2H' = CALCULATE(COUNT('TC e US'[NR_ATENDIMENTO]),(('TC e US'[DT_LAUDO]-'TC e US'[DT_LIBERACAO])*24*60) > 120)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 4963da19-4917-40bf-8d0a-8b8f562e6076

	measure 'Qtd RX_ECG >45min' = CALCULATE(COUNT('RX e ECG'[NR_ATENDIMENTO]),'RX e ECG'[MINUTOS]>45)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: 1c84f2c5-72bf-450c-9880-72b973cdeb30

	measure 'Qtd Reavaliações >45min' = CALCULATE(COUNT(reavaliacao[NR_ATENDIMENTO]),reavaliacao[MINUTOS]>45)
		formatString: 0
		displayFolder: REAVALIACAO
		lineageTag: 6271ac00-5e08-4956-beac-a26338b5d9f0

	measure 'Qtd Medicações >30min' = CALCULATE(COUNT(medicacao[NR_ATENDIMENTO]),medicacao[MINUTOS]>30)
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 26e4bc1f-3937-4b81-9198-76a4abdbe82b

	measure 'Qtd Consulta >1:30h' = CALCULATE(COUNT(fluxo[MIN_ENTRADA_X_CONSULTA]),fluxo[MIN_ENTRADA_X_CONSULTA]>90)
		formatString: 0
		displayFolder: CONSULTA
		lineageTag: 9a137990-796d-4168-b685-46600916a00b

	measure 'Qtd Alta > 3h' = CALCULATE(COUNT(fluxo[NR_ATENDIMENTO]),fluxo[MIN_ENTRADA_X_ALTA]>180)
		formatString: 0
		displayFolder: ALTA
		lineageTag: f3a7763f-675f-44bf-9f7d-0c474053d94c

	measure 'Percentual Dinâmico' = ```
			
			VAR SelecaoParametro = SELECTEDVALUE('Tabela_Parametro_Medidas'[Parametro])
			RETURN
			    SWITCH(
			        SelecaoParametro,
			
			        // --- ATENDIMENTOS ---
			        "ATENDIMENTOS",
			            DIVIDE([Qtd Atend],
			                CALCULATE(
			                    COUNT(Fluxo[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			                )
			            ),
			
			        // --- TRIAGEM >12MIN ---
			        "TRIAGEM >12MIN",
			            DIVIDE(
			                [Qtd Triagem >12min],
			                CALCULATE(
			                    COUNT(Fluxo[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			                )
			            ),
			
			        // --- CONSULTAS >1:30H ---
			        "CONSULTAS >1:30H",
			            DIVIDE(
			                [Qtd Consulta >1:30h],
			                CALCULATE(
			                    COUNT(Fluxo[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(Fluxo[HR_CONSULTA], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_CONSULTA])
			                )
			            ),
			
			        // --- MEDICAÇÕES >45MIN ---
			        "MEDICAÇÕES >45MIN",
			            DIVIDE(
			                [Qtd Medicações >30min],
			                CALCULATE(
			                    COUNT(medicacao[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			                )
			            ),
			
			        // --- RX E ECG >45MIN ---
			        "RX E ECG >45MIN",
			            DIVIDE(
			                [Qtd RX_ECG >45min],
			                CALCULATE(
			                    COUNT('RX e ECG'[NR_ATENDIMENTO]),
			                    USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			                )
			            ),
			
			        // --- TC e US >2H ---
			        "TC e US >2H",
			            DIVIDE(
			                [Qtd TC_US >2H],
			                CALCULATE(
			                    COUNT('TC e US'[NR_ATENDIMENTO]),
			                    USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			                )
			            ),
			
			        // --- REAVALIAÇÕES >45MIN ---
			        "REAVALIAÇÕES >45MIN",
			            DIVIDE(
			                [Qtd Reavaliações >45min],
			                CALCULATE(
			                    COUNT(reavaliacao[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			                )
			            ),
			
			        // --- PERMANÊNCIA >3H ---
			        "PERMANÊNCIA >3H",
			            DIVIDE(
			                [Qtd Alta > 3h],
			                CALCULATE(
			                    COUNT(Fluxo[NR_ATENDIMENTO]),
			                    USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			                    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			                )
			            ),
			
			        // --- Fallback ---
			        BLANK()
			    )
			
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: OUTROS
		lineageTag: 41d7c098-6acc-4524-8f1b-b4eef7916887

		changedProperty = IsHidden

	measure '% Triagem >12min' = (CALCULATE(COUNT('fluxo'[MIN_ENTRADA_X_TRIAGEM]),fluxo[MIN_ENTRADA_X_TRIAGEM] > 12)/ COUNT(fluxo[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: 7536eea9-497e-4ace-b9b9-d24c17b0aae2

	measure '% TC_US >2h' = (CALCULATE(COUNT('TC e US'[NR_ATENDIMENTO]),(('TC e US'[DT_LAUDO]-'TC e US'[DT_LIBERACAO])*24*60) > 120) / COUNT('TC e US'[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 0cb940ee-abfa-46c3-a95a-eb37f4f4b786

	measure '% RX_ECG >45min' = (CALCULATE(COUNT('RX e ECG'[NR_ATENDIMENTO]),'RX e ECG'[MINUTOS]>45) / COUNT('RX e ECG'[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 7dee1c06-a21b-4e76-9e22-d77dced9bc08

	measure '% Reavaliações >45min' = ((CALCULATE(COUNT(reavaliacao[NR_ATENDIMENTO]),reavaliacao[MINUTOS]>45)) / COUNT(reavaliacao[NR_ATENDIMENTO])) + 0
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: REAVALIACAO
		lineageTag: 14486977-ada2-4974-a45c-88bec62fbe2d

	measure '% Medicação >30min' = (CALCULATE(COUNT(medicacao[NR_ATENDIMENTO]),medicacao[MINUTOS]>30) / COUNT(medicacao[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 5e43c862-9c2d-4aea-a6df-68d4e1cf173e

	measure '% Consulta >1:30h' = (CALCULATE(COUNT(fluxo[MIN_ENTRADA_X_CONSULTA]),fluxo[MIN_ENTRADA_X_CONSULTA]>90) / COUNT(fluxo[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONSULTA
		lineageTag: 9335b1cf-7bfe-47aa-9992-d6306608eaa8

	measure '% Alta >3h' = ((CALCULATE(COUNT(fluxo[NR_ATENDIMENTO]),fluxo[MIN_ENTRADA_X_ALTA]>180)) / COUNT(fluxo[NR_ATENDIMENTO])) + 0
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ALTA
		lineageTag: 797e4625-052e-4bfe-963e-09e9cf8f1ba4

	measure 'Dica total de atendimentos' =
			
			CALCULATE(
			    [Qtd Atend],
			    USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			    ) + 0
		formatString: 0
		displayFolder: Dicas
		lineageTag: 277ef274-0ee2-44cd-af73-13508c88b9cc

	measure 'Dica Qtd Triagem >12min' = ```
			
			 CALCULATE(
			        [Qtd Triagem >12min],
			        USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			    ) + 0 
			 
			 & " de " & 
			 CALCULATE(
			    [Qtd Atend],
			    USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			    ) + 0
			```
		displayFolder: TRIAGEM
		lineageTag: 2204fc7f-7fcd-49bc-897e-e8936a58210a

	measure 'Dica Qtd TC_US >2H' = ```
			
			CALCULATE(
			        [Qtd TC_US >2H],
			        USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			    ) + 0
			
			& " de " & 
			
			CALCULATE(
			        COUNT('TC e US'[NR_ATENDIMENTO]),
			        USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			    ) + 0
			```
		displayFolder: TC/US
		lineageTag: d5cee435-7544-47f6-8c17-a57e2c02afa9

	measure 'Dica Qtd RX_ECG >45min' = ```
			
			CALCULATE(
			        [Qtd RX_ECG >45min],
			        USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			    ) + 0
			
			 & " de " & 
			
			CALCULATE(
			        COUNT('RX e ECG'[NR_ATENDIMENTO]),
			        USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			        ) + 0
			
			```
		displayFolder: TC/US
		lineageTag: 1bc4c93e-026f-4735-93fe-df97e228c0a0

	measure 'Dica Qtd Reavaliações >45min' = ```
			
			CALCULATE(
			        [Qtd Reavaliações >45min],
			        USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			        ) + 0
			
			 & " de " & 
			 
			CALCULATE(
			        COUNT(reavaliacao[NR_ATENDIMENTO]),
			        USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			    ) + 0
			```
		displayFolder: REAVALIACAO
		lineageTag: 8a1b0a6a-be13-4d96-a45b-89777dd11447

	measure 'Dica Qtd Medicações >30min' = ```
			
			 CALCULATE(
			        [Qtd Medicações >30min],
			        USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			    ) + 0
			 
			 & " de " & 
			 
			CALCULATE(
			        COUNT(medicacao[NR_ATENDIMENTO]),
			        USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			    ) + 0
			```
		displayFolder: MEDICACOES
		lineageTag: 2fb5475d-9f12-462a-9c4d-91ec198b8e41

	measure 'Dica Qtd Consulta >1:30h' = ```
			
			 CALCULATE(
			        [Qtd Consulta >1:30h],
			        USERELATIONSHIP(fluxo[HR_CONSULTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), fluxo[HR_CONSULTA])
			    ) + 0
			 
			 & " de " & 
			 CALCULATE(
			    [Qtd Atend],
			    USERELATIONSHIP(fluxo[HR_CONSULTA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), fluxo[HR_CONSULTA])
			    ) + 0
			```
		displayFolder: TC/US
		lineageTag: d18c5f88-a0b2-485c-a23b-4736d8196c44

	measure 'Dica Qtd Alta > 3h' = ```
			
			CALCULATE(
			        [Qtd Alta > 3h],
			        USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			    ) + 0  
			    
			& " de " &  
			
			CALCULATE(
			        COUNT(Fluxo[NR_ATENDIMENTO]),
			        USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			    ) + 0
			```
		displayFolder: ALTA
		lineageTag: 1f969e57-0082-4e2a-a016-e11f88c09428

	measure 'Qtd Atend por Hora' = ```
			
			CALCULATE(
			    COUNT(fluxo[NR_ATENDIMENTO]),
			    USERELATIONSHIP(fluxo[HR_ENTRADA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), fluxo[HR_ENTRADA])
			)
			
			```
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 2ca21014-1f40-40e9-b1cb-f2cfd0200bba

	measure 'Percentual Dinâmico por Hora' = ```
			
			DIVIDE(
			    [Medida Dinâmica], 
			    [Medida Total Base Horária] 
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OUTROS
		lineageTag: 731a785e-d4b5-4ade-baef-94a9f96459f9

	measure 'Medida Total Base Horária' = ```
			
			VAR SelecaoParametro = SELECTEDVALUE('Tabela_Parametro_Medidas'[Parametro])
			RETURN
			    SWITCH(
			        SelecaoParametro,
			        "ATENDIMENTOS", CALCULATE(
			            [Qtd Atend],
			            USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			        ),
			        "TRIAGEM >12MIN", CALCULATE(
			            COUNT(Fluxo[NR_ATENDIMENTO]), 
			            USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			        ),
			        "CONSULTAS >1:30H", CALCULATE(
			            COUNT(Fluxo[NR_ATENDIMENTO]), 
			            USERELATIONSHIP(Fluxo[HR_CONSULTA], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_CONSULTA])
			        ),
			        
			        "MEDICAÇÕES >45MIN", CALCULATE(
			            COUNT(medicacao[NR_ATENDIMENTO]),
			            USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			        ),
			
			        "RX E ECG >45MIN", CALCULATE(
			            COUNT('RX e ECG'[NR_ATENDIMENTO]),
			            USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			        ),
			
			        "TC e US >2H", CALCULATE(
			            COUNT('TC e US'[NR_ATENDIMENTO]),
			            USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			        ),
			
			        "REAVALIAÇÕES >45MIN", CALCULATE(
			            COUNT(reavaliacao[NR_ATENDIMENTO]),
			            USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			        ),
			
			        "PERMANÊNCIA >3H", CALCULATE(
			            COUNT(Fluxo[NR_ATENDIMENTO]),
			            USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			            TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			        ),
			
			        BLANK()
			    )
			
			```
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 9ffffaa6-7c74-451a-a83d-c821d2f03c1d

	measure 'Dica % Triagem >12min' = ```
			
			 (CALCULATE(
			        [Qtd Triagem >12min],
			        USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			    )
			 
			 /
			
			 CALCULATE(
			    [Qtd Atend],
			    USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			    )) + 0
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: dbe226f7-4f08-43e5-ab94-f56cd8b053a1

	measure 'Dica % Consulta >1:30h' = ```
			
			 (CALCULATE(
			        [Qtd Consulta >1:30h],
			        USERELATIONSHIP(fluxo[HR_CONSULTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), fluxo[HR_CONSULTA])
			    )
			 
			/
			
			 CALCULATE(
			    [Qtd Atend],
			    USERELATIONSHIP(fluxo[HR_CONSULTA], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), fluxo[HR_CONSULTA])
			    )) + 0
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 5aac25be-156a-4918-9667-25580071307c

	measure 'Dica % Medicação >30min' = ```
			
			 (CALCULATE(
			        [Qtd Medicações >30min],
			        USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			    )
			 
			/
			 
			CALCULATE(
			        COUNT(medicacao[NR_ATENDIMENTO]),
			        USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			    )) + 0
			```
		displayFolder: MEDICACOES
		lineageTag: d96dec11-a0f5-4410-aa0c-10e7dfd20d6f

	measure 'Dica % RX_ECG >45min' =
			
			(CALCULATE(
			    [Qtd RX_ECG >45min],
			    USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			    )
			
			/
			
			CALCULATE(
			    COUNT('RX e ECG'[NR_ATENDIMENTO]),
			    USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			    TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			    )) + 0
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: e53c2b95-5274-478b-8c7c-872710b9ceda

	measure 'Dica % TC_US >2h' =
			
			(CALCULATE(
			        [Qtd TC_US >2H],
			        USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			    )
			
			/
			
			CALCULATE(
			        COUNT('TC e US'[NR_ATENDIMENTO]),
			        USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			    )) + 0
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 3949e797-4f61-484d-81cb-390856a2e8f4

	measure 'Dica % Reavaliações >45min' = ```
			
			(CALCULATE(
			        [Qtd Reavaliações >45min],
			        USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			        )
			
			/
			 
			CALCULATE(
			        COUNT(reavaliacao[NR_ATENDIMENTO]),
			        USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			    )) + 0
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: REAVALIACAO
		lineageTag: aedacb5e-8846-4bec-a374-5e5f12a967ef

	measure 'Dica % Alta >3h' = ```
			
			(CALCULATE(
			        [Qtd Alta > 3h],
			        USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			    )
			    
			/ 
			
			CALCULATE(
			        COUNT(Fluxo[NR_ATENDIMENTO]),
			        USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			        TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			    )) + 0
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ALTA
		lineageTag: 89c6f7ad-2918-4aaa-8796-3f727df6603c

	measure '% medic lenta x total atend' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[velocidade]="Lenta")) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 1f575359-e9dd-4697-9040-d9428503f382

	measure '% medic rapida x total atend' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[velocidade]="Rápida")) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: bffe47bb-97fb-4cc5-9987-93a240d0bd68

	measure '% medic lenta x pac medicados' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Lenta")) / DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: fd26ec52-a4bc-436b-9412-a36813a6b3a9

	measure '% medic rapida x pac medicados' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Rápida")) / DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: ef4b3772-3511-4070-a94c-ec2b7f8021ee

	measure 'qtd medic lentas' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Lenta"))
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 97d18caa-3654-4d40-84a8-06a9b1a3948e

	measure '% pacientes medicados' = ```
			-- Essa medida não traz 0, pq ela é usada no visual metas por volumes, que não pode trazer os zeros
			((DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO])) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 98d0883d-d54d-4f78-896e-3c97b792f22b

	measure 'Medida Dinâmica' = ```
			
			VAR SelecaoParametro = SELECTEDVALUE('Tabela_Parametro_Medidas'[Parametro])
			
			RETURN
			    SWITCH(
			        SelecaoParametro,
			
			        // --- CONSULTAS >1:30H usa Fluxo[HR_CONSULTA] ---
			        "CONSULTAS >1:30H",
			            CALCULATE(
			                [Qtd Consulta >1:30h],
			                USERELATIONSHIP(Fluxo[HR_CONSULTA], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_CONSULTA])
			            ),
			
			        // --- TRIAGEM >12MIN usa Fluxo[HR_ENTRADA] ---
			        "TRIAGEM >12MIN",
			            CALCULATE(
			                [Qtd Triagem >12min],
			                USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			            ),
			
			        // --- MEDICAÇÕES >30MIN usa medicacao[HR_MEDICACAO] ---
			        "MEDICAÇÕES >30MIN",
			            CALCULATE(
			                [Qtd Medicações >30min],
			                USERELATIONSHIP(medicacao[HR_MEDICACAO], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), medicacao[HR_MEDICACAO])
			            ),
			
			        // --- RX E ECG >45MIN usa 'RX e ECG'[HR_RX_ECG] ---
			        "RX E ECG >45MIN",
			            CALCULATE(
			                [Qtd RX_ECG >45min],
			                USERELATIONSHIP('RX e ECG'[HR_RX_ECG], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), 'RX e ECG'[HR_RX_ECG])
			            ),
			
			        // --- TC e US >2H usa 'TC e US'[HR_TC_US] ---
			        "TC e US >2H",
			            CALCULATE(
			                [Qtd TC_US >2H],
			                USERELATIONSHIP('TC e US'[HR_TC_US], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), 'TC e US'[HR_TC_US])
			            ),
			
			        // --- REAVALIAÇÕES >45MIN usa reavaliacao[HR_REAVALIACAO] ---
			        "REAVALIAÇÕES >45MIN",
			            CALCULATE(
			                [Qtd Reavaliações >45min],
			                USERELATIONSHIP(reavaliacao[HR_REAVALIACAO], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), reavaliacao[HR_REAVALIACAO])
			            ),
			
			        // --- PERMANÊNCIA >3H usa Fluxo[HR_ALTA] ---
			        "PERMANÊNCIA >3H",
			            CALCULATE(
			                [Qtd Alta > 3h],
			                USERELATIONSHIP(Fluxo[HR_ALTA], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ALTA])
			            ),
			
			        // --- ATENDIMENTOS usa Fluxo[HR_ENTRADA] ---
			        "ATENDIMENTOS",
			            CALCULATE(
			                [Qtd Atend],
			                USERELATIONSHIP(Fluxo[HR_ENTRADA], HORAS[HORAS]),
			                TREATAS(VALUES(HORAS[HORAS]), Fluxo[HR_ENTRADA])
			            ),
			
			        // --- Fallback caso nada esteja selecionado ---
			        BLANK()
			    )
			
			```
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 9ae348a0-fcef-448d-a69f-05f23bd7aa39

	measure 'Qtd exames lab' = COUNT(laboratorio[NR_ATENDIMENTO])
		formatString: 0
		displayFolder: LABORATORIO
		lineageTag: 687ff51a-5f4b-466a-94e0-b069c2f470bb

	measure 'Total atendimentos medicados' = (DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]))
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 2f7be7cb-dfe1-4577-9fd8-700034ab8b2f

	measure 'qtd medic rápidas' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Rápida"))
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 22b098a8-3d26-4325-9a4d-74c534ce87ec

	measure 'Qtd Altas' =
			
			CALCULATE(
			    COUNTROWS ( fluxo ),
			    NOT ( fluxo[alta_hospitalar] IN {
			        "Óbito",
			        "Evadiu-se",
			        "Transferência Inter-Hospitalar"
			    } ),
			    NOT ( ISBLANK ( fluxo[DT_ALTA_DATA] ) ),
			    USERELATIONSHIP ( fluxo[DT_ALTA_DATA], Calendario[Data] )
			) + 0
		formatString: 0
		displayFolder: ALTA
		lineageTag: 529e6cae-19f1-4272-9384-1207271572ef

	measure 'Qtd Evasao' =
			
			CALCULATE(
			    COUNTROWS ( fluxo ),
			    ( fluxo[alta_hospitalar] = "Evadiu-se"
			     ),
			    NOT ( ISBLANK ( fluxo[DT_ALTA_DATA] ) ),
			    USERELATIONSHIP ( fluxo[DT_ALTA_DATA], Calendario[Data])
			) + 0
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 99800093-3d3c-4123-9d57-2aa511132d04

	measure 'Qtd Transferências' =
			
			CALCULATE(
			    COUNTROWS(fluxo),
			    (fluxo[ALTA_HOSPITALAR] = "Transferência Inter-Hospitalar"),
			    NOT ( ISBLANK ( fluxo[DT_ALTA_DATA] ) ),
			    USERELATIONSHIP ( fluxo[DT_ALTA_DATA], Calendario[Data])
			) + 0
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 1f7b6760-601a-4d80-9c95-a18a2582999f

	measure 'Qtd Óbitos' =
			
			CALCULATE(
			    COUNTROWS(fluxo),
			    (fluxo[alta_hospitalar] = "Óbito"),
			    NOT ( ISBLANK ( fluxo[DT_ALTA_DATA] ) ),
			    USERELATIONSHIP ( fluxo[DT_ALTA_DATA], Calendario[Data])
			) + 0
		formatString: 0
		displayFolder: OUTROS
		lineageTag: d9dba2a6-77c3-4ecf-98ac-7e76ce47be80

	measure '% evasao' = ([Qtd Evasao] / [Qtd Atend]) + 0
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OUTROS
		lineageTag: 4ce4fdc3-9c72-4805-9d6f-bf5fb33af84c

	measure 'Sem desfecho' =
			
			CALCULATE(
			    COUNTROWS(fluxo),
			    ISBLANK(fluxo[DT_DESFECHO])
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 98add076-a2d1-4f3c-93df-4e6d63238399

	measure Percentual_Readmitidos =
			
			DIVIDE(
			    CALCULATE(COUNTROWS(fluxo), fluxo[Readmissao_Em_Ate_1_Dia] = 1),
			    COUNTROWS(fluxo),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: OUTROS
		lineageTag: 3634bbd2-10c6-4b9d-8605-12b54028dc36

	measure 'Qtd Com Alta Médica' =
			
			CALCULATE(
			    COUNTROWS(fluxo),
			    NOT ISBLANK(fluxo[dt_Alta_medico])
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: ab764366-c592-4ac8-a15d-17aff51ce4bc

	measure %Readmitidos_Mesmo_CID =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fluxo),
			        fluxo[Readmissao_CID_Igual] = "Mesmo CID"
			    ),
			    CALCULATE(
			        COUNTROWS(fluxo),
			        fluxo[Readmissao_Em_Ate_1_Dia] = 1
			    ),
			    0
			)
		displayFolder: OUTROS
		lineageTag: b58de079-b2f1-4a43-b5a2-140813b536c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média tempo triagem' =
			
			VAR TotalMinutos = AVERAGE(fluxo[MIN_ENTRADA_X_TRIAGEM])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		displayFolder: TRIAGEM
		lineageTag: 229e37c6-5b2b-4e11-be35-5d665875a880

	measure 'Média tempo consulta' =
			
			VAR TotalMinutos = AVERAGE(fluxo[MIN_ENTRADA_X_CONSULTA])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		displayFolder: CONSULTA
		lineageTag: a0fb396a-954b-41d1-a291-247fe36dfac0

	measure 'Média tempo alta' =
			
			VAR TotalMinutos = AVERAGE(fluxo[MIN_ENTRADA_X_ALTA])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    IF(
			        ISBLANK(TotalMinutos),
			        BLANK(), // Retorna vazio (BLANK) se TotalMinutos for BLANK
			        FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
			    )
		displayFolder: ALTA
		lineageTag: d42bccb0-10f9-44c2-84dd-4bd62f270ced

	measure 'Média tempo exame US' = ```
			
			VAR TotalMinutos = 
			    CALCULATE(
			        AVERAGE('TC e US'[MINUTOS]),
			        'TC e US'[tipo] = "US"
			    )
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
			```
		displayFolder: TC/US
		lineageTag: eae34f2d-4b8f-4666-a853-85bd57e0a1f1

	measure 'Média tempo exame TC' = ```
			
			VAR TotalMinutos = 
			    CALCULATE(
			        AVERAGE('TC e US'[MINUTOS]),
			        'TC e US'[tipo] = "TC"
			    )
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
			```
		displayFolder: TC/US
		lineageTag: 2b8780ee-fa01-4f1f-aaab-d434f8143936

	measure 'Média tempo medicação' =
			
			VAR TotalMinutos = AVERAGE(medicacao[MINUTOS])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		displayFolder: MEDICACOES
		lineageTag: 959249cc-6948-43a4-a766-e2ade34fc087

	measure 'Média tempo reavaliação' =
			
			VAR TotalMinutos = AVERAGE(reavaliacao[MINUTOS])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		displayFolder: REAVALIACAO
		lineageTag: 0616b857-1abe-4b8b-ab50-84ddf0f7b6a0

	measure 'Média tempo exame RX' = ```
			
			VAR TotalMinutos = 
			    CALCULATE(
			        AVERAGE('RX e ECG'[MINUTOS]),
			        'RX e ECG'[tipo] = "RX"
			    )
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
			```
		displayFolder: RX/ECG
		lineageTag: 49ff20d9-1e0a-4414-8dde-a57c30e219ff

	measure 'Média tempo laboratorio' =
			
			VAR TotalMinutos = AVERAGE('RX e ECG'[MINUTOS])
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		displayFolder: LABORATORIO
		lineageTag: 5d4cb348-aa69-4d87-a859-cf88e4db448a

	measure 'Média tempo exame ECG' = ```
			
			VAR TotalMinutos = 
			    CALCULATE(
			        AVERAGE('RX e ECG'[MINUTOS]),
			        'RX e ECG'[tipo] = "ECG"
			    )
			VAR Horas = QUOTIENT(TotalMinutos, 60)
			VAR Minutos = MOD(TotalMinutos, 60)
			VAR Segundos = ROUND(60 * (TotalMinutos - FLOOR(TotalMinutos, 1)), 0)
			RETURN
			    FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
			```
		displayFolder: RX/ECG
		lineageTag: 1cb921c4-b4bd-4286-ad56-bc820f43bcc0

	measure Rank_Discriminador =
			
			VAR UnidadeAtual = SELECTEDVALUE('fluxo'[UNIDADE])
			RETURN
			IF (
			    ISBLANK(UnidadeAtual),
			    BLANK(),
			    RANKX(
			        // Lista de discriminadores apenas da unidade atual
			        SUMMARIZE(
			            FILTER(ALL('fluxo'), 'fluxo'[UNIDADE] = UnidadeAtual),
			            'fluxo'[DISCRIMINADOR]
			        ),
			        [Qtd Atend],
			        ,
			        DESC,
			        DENSE
			    )
			)
		formatString: 0
		displayFolder: OUTROS
		lineageTag: 44486b5e-dbc7-4ebc-85a2-7a265925881d

	measure '% medic lenta x rapida' = (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Lenta")) / (CALCULATE(DISTINCTCOUNT(Vias_medicamentos[NR_ATENDIMENTO]),Vias_medicamentos[Velocidade Maxima]="Rápida"))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 8a2866c8-44a2-46e8-99a3-11a5833e5025

	measure IOSSuperUsuarios_Prontuario =
			
			VAR SuperLista =
			    FILTER(
			        VALUES(fluxo[CD_PESSOA_FISICA]),
			        CALCULATE(COUNTROWS(fluxo), ALLSELECTED(fluxo)) >= 3
			    )
			RETURN
			COUNTROWS(SuperLista)  -- conta as pessoas distintas
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: 62f5e42d-67e2-48fd-bc19-8a669d1866f9

	measure SuperUsuarios_Atendimentos =
			
			VAR SuperLista =
			    FILTER(
			        VALUES( fluxo[CD_PESSOA_FISICA] ),
			        -- testa o "≥ 3" no conjunto SELECIONADO da página
			        -- (respeita slicers/filtros, mas ignora a dimensão do eixo do visual)
			        CALCULATE( COUNTROWS(fluxo), ALLSELECTED( fluxo ) ) >= 3
			    )
			RETURN
			CALCULATE(
			    COUNTROWS( fluxo ),
			    KEEPFILTERS( SuperLista )   -- aplica a lista de "super" e conta na fatia atual (unidade, cor, etc.)
			)
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: c312a2fb-8252-4bcf-bdfa-1932f8b7a1ab

	measure '% Super_usu_retorno' = DIVIDE([SuperUsuarios_Atendimentos],[Qtd Atend])
		displayFolder: SUPER USUARIOS
		lineageTag: abebd7be-707f-45ab-b6b9-a494aa4d6bbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd saidas' = ```
			
			CALCULATE (
			    COUNTROWS ( fluxo ),
			    USERELATIONSHIP ( fluxo[DT_ALTA_DATA], Calendario[Data])
			)
			
			```
		formatString: 0
		displayFolder: OUTROS
		lineageTag: e3100465-8767-49e0-a44c-4b666630a6f5

	measure '% Atend > Tempo triagem (Mês anterior)' = ```
			
			CALCULATE(
			    [% Atend > Tempo triagem],
			    DATEADD('Calendario'[Data], -1, MONTH)
			)
			
			
			```
		displayFolder: TRIAGEM
		lineageTag: bb901c85-aa28-424a-b66e-893c3e267076

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Δ pp % Atend > Tempo triagem' = ```
			
			VAR Atual   = [% Atend > Tempo triagem]
			VAR Anterior = [% Atend > Tempo triagem (Mês anterior)]
			RETURN IF( NOT ISBLANK(Anterior), Atual - Anterior )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: cb8de359-0084-4453-a8d5-4a18480956e6

	measure 'Unidades Selecionadas' = ```
			
			VAR SelUnidades =
			    CONCATENATEX(
			        VALUES(fluxo[UNIDADE]),  // Pega apenas as unidades selecionadas
			        fluxo[UNIDADE],          // Campo a concatenar
			        " | "                     // Separador
			    )
			RETURN
			IF(
			    ISFILTERED(fluxo[UNIDADE]),  // Verifica se existe filtro aplicado
			    SelUnidades,                 // Se sim, retorna as selecionadas concatenadas
			    "Todas as Unidades"          // Se não, retorna "Todas as Unidades"
			)
			
			```
		displayFolder: OUTROS
		lineageTag: 44b32eb4-c240-4376-88d2-3a9b29faf448

	measure 'Dia D-1' = ```
			
			VAR MaxDataAll =
			    CALCULATE ( MAX ( fluxo[DATA] ), ALL (fluxo) )
			VAR DataAnteriorDisponivel =
			    CALCULATE (
			        MAX (fluxo[DATA]),
			        FILTER (ALL(fluxo), fluxo[DATA] < MaxDataAll )
			    )
			RETURN
			    IF (
			        MaxDataAll = TODAY (),
			        DataAnteriorDisponivel,   -- se a última data é hoje, traz o D-1 disponível
			        MaxDataAll                -- se a última data é ontem (ou antes), traz normalmente
			    )
			
			```
		formatString: Short Date
		displayFolder: OUTROS
		lineageTag: b9acdd39-dcbb-4937-af88-9af5661b166b

	measure Dif_min_triagem_consulta = ```
			
			VAR T =
			    FILTER(
			        fluxo,
			        NOT ISBLANK(fluxo[DT_FIM_TRIAGEM]) &&
			        NOT ISBLANK(fluxo[DT_ATEND_MEDICO])
			    )
			RETURN
			IF(
			    ISEMPTY(T),
			    BLANK(),
			    AVERAGEX(
			        T,
			        DATEDIFF(fluxo[DT_FIM_TRIAGEM], fluxo[DT_ATEND_MEDICO], MINUTE)
			    )
			)
			
			
			```
		displayFolder: TRIAGEM
		lineageTag: cbaf7afc-ebb9-4b12-bf6e-ce65c683efc4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_de_triagem = ```
			
			VAR T =
			    FILTER(
			        fluxo,
			        NOT ISBLANK(fluxo[DT_TRIAGEM]) &&
			        NOT ISBLANK(fluxo[DT_FIM_TRIAGEM])
			    )
			RETURN
			IF(
			    ISEMPTY(T),
			    BLANK(),                                    -- sem linhas válidas => nulo
			    AVERAGEX(
			        T,
			        DATEDIFF( fluxo[DT_TRIAGEM], fluxo[DT_FIM_TRIAGEM], MINUTE )
			    )
			)
			
			```
		displayFolder: TRIAGEM
		lineageTag: edd7b5da-e761-4238-9475-94a251a3785d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tempo RX_ECG por Paciente (min)' =
			
			VAR Pacientes = DISTINCT( 'RX e ECG'[NR_ATENDIMENTO] )   // lista de pacientes no contexto
			RETURN
			AVERAGEX(
			    Pacientes,
			    VAR p = 'RX e ECG'[NR_ATENDIMENTO]                   // paciente atual no iterador
			    VAR MinSolic =
			        CALCULATE( MIN( 'RX e ECG'[DT_SOLICITACAO] ),
			                   'RX e ECG'[NR_ATENDIMENTO] = p )      // menor solicitação do paciente
			    VAR MaxExame =
			        CALCULATE( MAX( 'RX e ECG'[DT_EXAME] ),
			                   'RX e ECG'[NR_ATENDIMENTO] = p )      // maior exame do paciente
			    RETURN
			        IF(
			            ISBLANK(MinSolic) || ISBLANK(MaxExame),
			            BLANK(),                                  // se faltar uma das datas, ignora no cálculo
			            INT( ( MaxExame - MinSolic ) * 1440 )     // minutos (1440 = 24*60)
			            // Se quiser evitar negativos por dados invertidos, use:
			            // MAX( 0, INT( ( MaxExame - MinSolic ) * 1440 ) )
			        )
			)
		displayFolder: RX/ECG
		lineageTag: baa0051a-de9d-42cf-b761-917599bb7f8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tempo TC/US por Atendimento (min)' = ```
			
			VAR T =
			    // 1) Agrupa por atendimento e calcula min(DT_REALIZADO) e max(DT_LAUDO)
			    SUMMARIZE(
			        'TC e US',
			        'TC e US'[NR_ATENDIMENTO],
			        "DuracaoMin",
			            VAR MinRealizado = MIN('TC e US'[DT_LIBERACAO])
			            VAR MaxLaudo     = MAX('TC e US'[DT_LAUDO])
			            RETURN
			                // 2) Se faltar qualquer data, retorna BLANK (não entra na média)
			                IF(
			                    NOT ISBLANK(MinRealizado) && NOT ISBLANK(MaxLaudo),
			                    // 3) Diferença em minutos (1440 = 24*60), protegendo contra negativos
			                    MAX(0, INT( (MaxLaudo - MinRealizado) * 1440 ))
			                )
			    )
			RETURN
			// 4) Média dos minutos por atendimento (BLANKs são ignorados pela AVERAGEX)
			AVERAGEX(T, [DuracaoMin])
			
			
			```
		displayFolder: TC/US
		lineageTag: 654e71be-d213-4201-befe-8179e0d16234

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tempo Vias (AGO) por Prescrição (min)' = ```
			
			VAR T =
			    // 1) Mantém filtros externos e restringe às linhas válidas (AGO + datas não nulas)
			    ADDCOLUMNS(
			        SUMMARIZE(
			            FILTER(
			                Vias_medicamentos,
			                Vias_medicamentos[CD_INTERVALO] = "AGO"
			                    && NOT ISBLANK( Vias_medicamentos[DT_LIBERACAO] )
			                    && NOT ISBLANK( Vias_medicamentos[DT_FIM_HORARIO] )
			            ),
			            Vias_medicamentos[NR_PRESCRICAO]        // agrupa por prescrição
			        ),
			        "DuracaoMin",
			            VAR MinLib = CALCULATE( MIN( Vias_medicamentos[DT_LIBERACAO] ) )
			            VAR MaxFim = CALCULATE( MAX( Vias_medicamentos[DT_FIM_HORARIO] ) )
			            RETURN
			                // Diferença em minutos; proteje contra negativos por segurança
			                MAX( 0, INT( ( MaxFim - MinLib ) * 1440 ) )
			    )
			RETURN
			// 2) Média das durações por prescrição (BLANKs/sem linhas => retorna BLANK)
			AVERAGEX( T, [DuracaoMin] )
			
			
			```
		displayFolder: MEDICACOES
		lineageTag: b577309f-139b-48f4-8759-1ba3966e1308

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ID_TRIAGEM_FORA_META =
			IF(
			    Averagex(fluxo, fluxo[MIN_ENTRADA_X_TRIAGEM]) >= Meta_triagem[Valor Meta_triagem], 1,0)
		displayFolder: TRIAGEM
		lineageTag: 19696ab7-ff43-4d59-ae70-9351f44bd46b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eh_SuperUsuario (pac)' = ```
			
			VAR DataRef    = MAXX(ALL(fluxo), fluxo[DATA]) - 1
			VAR Dias       = SELECTEDVALUE(Qtde_dias[Qtde_dias], 30)
			VAR DataInicio = DataRef - Dias
			VAR Limite     = SELECTEDVALUE(Qtde_atd[Qtde_atd], BLANK())
			VAR Paciente   = SELECTEDVALUE(fluxo[CD_PESSOA_FISICA])
			VAR T =
			    SUMMARIZECOLUMNS(
			        fluxo[CD_PESSOA_FISICA],
			        FILTER(
			            ALL(fluxo),
			            fluxo[DATA] >= DataInicio && fluxo[DATA] <= DataRef
			        ),
			        "Qtd", COUNTROWS(fluxo)
			    )
			VAR QtdPaciente =
			    MAXX(
			        FILTER(T, fluxo[CD_PESSOA_FISICA] = Paciente),
			        [Qtd]
			    )
			RETURN
			IF(
			    ISBLANK(Limite),
			    "Normal",
			    IF(QtdPaciente >= Limite, "Superusuário", "Normal")
			)
			
			
			```
		displayFolder: SUPER USUARIOS
		lineageTag: 0fbbaa1f-0292-4f1a-9442-d5d3cd62d9c9

	measure 'Entre datas SU' =
			
			VAR DataRef  = MAXX(ALL(fluxo), fluxo[DATA]) - 1
			VAR Dias     = SELECTEDVALUE(Qtde_dias[Qtde_dias], 30)
			VAR DataIni  = DataRef - Dias
			VAR TotalSemFiltro = CALCULATE( COUNTROWS( calendario ), ALL( calendario ) )
			
			VAR ParamMax =
			    IF(
			        COUNTROWS( VALUES( calendario[data] ) ) = TotalSemFiltro,
			        CALCULATE( MAX( calendario[data] ), ALL( calendario ) ),  -- Todos
			        CALCULATE( MAX( calendario[data] ) )                       -- Filtrado
			    )
			
			RETURN
			"de " & FORMAT(DataIni, "dd/MM/yyyy") &  " a " & FORMAT(DataRef, "dd/MM/yyyy") & " (últimos " & Dias & " dias" & ")"
		displayFolder: SUPER USUARIOS
		lineageTag: f44ac3ed-12fb-4d5b-b4a7-5e6c94e05eeb

	measure 'Qtd Total Pacientes' =
			
			VAR TotalNormais =
			    SUMX(
			        VALUES(fluxo[CD_PESSOA_FISICA]),
			        IF([Eh_SuperUsuario (pac)] = "Normal", 1, 0)
			    )
			VAR TotalSuper =
			    SUMX(
			        VALUES(fluxo[CD_PESSOA_FISICA]),
			        IF([Eh_SuperUsuario (pac)] = "Superusuário", 1, 0)
			    )
			RETURN
			TotalNormais + TotalSuper
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: b75981dd-6685-4d35-924b-bfd6db44a30d

	measure 'Qtd Normal' =
			
			SUMX(
			    VALUES(fluxo[CD_PESSOA_FISICA]),
			    IF([Eh_SuperUsuario (pac)] = "Normal", 1, 0)
			)
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: fe95ae69-7044-4bfd-b94f-cf2139142c7b

	measure 'Qtd Normal_atd' =
			
			SUMX(
			    VALUES(fluxo[NR_ATENDIMENTO]),
			    IF([Eh_SuperUsuario (pac)] = "Normal", 1, 0)
			)
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: 9d945f9b-264c-4d03-ad47-cd8f3fd7a591

	measure 'Qtd Superusuario' =
			
			SUMX(
			    VALUES(fluxo[CD_PESSOA_FISICA]),
			    IF([Eh_SuperUsuario (pac)] = "Superusuário", 1, 0)
			)
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: a44be008-173f-463e-b080-b4eab15a1825

	measure 'Qtd Superusuario_atd' =
			
			SUMX(
			    VALUES(fluxo[NR_ATENDIMENTO]),
			    IF([Eh_SuperUsuario (pac)] = "Superusuário", 1, 0)
			)
		formatString: 0
		displayFolder: SUPER USUARIOS
		lineageTag: 78b6e150-90fd-4cf5-a030-d4f2846adc36

	measure '%Super Usuarios' = DIVIDE(Medidas[Qtd Normal_atd],Medidas[Qtd Atend])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SUPER USUARIOS
		lineageTag: a88be75d-3e22-4d4e-837d-82dfbb8e6235

	measure %superusuario_atd = DIVIDE(Medidas[Qtd Superusuario_atd],[Qtd Atend])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SUPER USUARIOS
		lineageTag: e96d049c-2a33-482a-8f17-03bf875bba97

	measure 'Eh_SuperUsuario (visual)' =
			
			VAR QtdeSU =
			    COUNTROWS(
			        FILTER(
			            VALUES(fluxo[CD_PESSOA_FISICA]),
			            [Eh_SuperUsuario (pac)] = "Superusuário"
			        )
			    )
			RETURN
			IF( QtdeSU > 0, "Superusuário", BLANK() )
		displayFolder: SUPER USUARIOS
		lineageTag: 56784196-4704-40ca-b57a-39776cf470b4

	measure PeriodoInteresse = ```
			
			VAR DataRef   = MAXX(ALL(fluxo), fluxo[DATA]) - 1     -- fim da janela (último dia do registro -1)
			VAR Dias      = SELECTEDVALUE(Qtde_dias[Qtde_dias], 30)
			VAR DataIni   = DataRef - Dias                        -- início da janela
			VAR DataMin   = MIN('Calendario'[Data])               -- menor data no contexto (ano/mês/dia)
			VAR DataMax   = MAX('Calendario'[Data])               -- maior data no contexto
			RETURN
			IF(
			    NOT ISBLANK(DataMin) 
			        && DataMax >= DataIni 
			        && DataMin <= DataRef,                        -- há sobreposição de intervalos?
			    "Dentro",
			    "Fora"
			)
			
			
			
			```
		displayFolder: SUPER USUARIOS
		lineageTag: 73597ff4-05a8-4ca3-aeef-8a87029129b1

	measure 'qtd internados' =
			
			CALCULATE(
			    COUNT(fluxo[NR_ATENDIMENTO]),
			    fluxo[DESTINO] = "Internado",
			    USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA]))
		formatString: 0
		displayFolder: CONVERSAO
		lineageTag: d718c9a2-796d-4416-a79b-b643e19dda4c

	measure 'Média tempo_entrada_x_internacao (hh:mm:ss)' = ```
			
			VAR TotalSec = ROUND([Média tempo_entrada_x_internacao (seg)], 0)
			VAR Horas    = INT( TotalSec / 3600 )
			VAR Minutos  = INT( MOD(TotalSec, 3600) / 60 )
			VAR Segundos = MOD(TotalSec, 60)
			RETURN
			    FORMAT(Horas, "0") & ":"
			    & FORMAT(Minutos, "00") & ":"
			    & FORMAT(Segundos, "00")
			
			```
		displayFolder: CONVERSAO
		lineageTag: 40ed31bc-8888-49ca-840a-3ff0e9521484

	measure 'Média tempo_entrada_x_internacao (seg)' = ```
			
			CALCULATE(
			    AVERAGEX(
			        FILTER(
			            fluxo,
			            NOT ISBLANK(fluxo[dt_entrada]) &&
			            NOT ISBLANK(fluxo[dt_internacao]) &&
			            fluxo[dt_internacao] >= fluxo[dt_entrada]
			        ),
			        DATEDIFF(fluxo[dt_entrada], fluxo[dt_internacao], SECOND)
			    ),
			    USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA])
			)
			
			```
		displayFolder: CONVERSAO
		lineageTag: 3306a92c-2eb5-4eac-a713-92c7bafa9c93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% conversao' =
			
			VAR Numerador =
			    CALCULATE(
			        COUNT(fluxo[NR_ATENDIMENTO]),
			        fluxo[DESTINO] = "Internado",
			        USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA])
			    )
			VAR Denominador =
			    CALCULATE(
			        COUNT(fluxo[NR_ATENDIMENTO]),
			        USERELATIONSHIP('Calendario'[Data], fluxo[DATA])
			    )
			RETURN
			DIVIDE(Numerador, Denominador)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: 8bec6a36-548a-4e83-9597-cc4bd820256d

	measure '% conversao (Global)' = CALCULATE([% conversao], ALL(fluxo[UNIDADE]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: ebccc543-26bb-49d2-b466-40deb8f636b6

	measure '% conversao (Unidade)' = [% conversao]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: e253563e-b441-4845-b595-4ff0988f9940

	measure '% pacientes SU' = DIVIDE([Qtd Superusuario],[Qtd Total Pacientes])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SUPER USUARIOS
		lineageTag: 9bac16cd-a4c1-4cfa-9fc1-67a3f146886e

	measure '% pacientes com ECG' =
			CALCULATE(
			    (DISTINCTCOUNT('RX e ECG'[NR_ATENDIMENTO])), 'RX e ECG'[tipo] = "ECG"
			    ) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 5ee47994-72f8-4b41-864e-2ce21248bc2a

	measure '% pacientes com RX' =
			CALCULATE(
			    (DISTINCTCOUNT('RX e ECG'[NR_ATENDIMENTO])), 'RX e ECG'[tipo] = "RX"
			    ) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 2e78c495-0148-467e-ba86-6cfffd19ed4c

	measure '% pacientes com TC' =
			CALCULATE(
			    (DISTINCTCOUNT('TC e US'[NR_ATENDIMENTO])), 'TC e US'[tipo] = "TC"
			    ) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: f0fd92d3-d15e-4908-8ba5-253b9ed8dc2e

	measure '% pacientes com US' =
			CALCULATE(
			    (DISTINCTCOUNT('TC e US'[NR_ATENDIMENTO])), 'TC e US'[tipo] = "US"
			    ) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 4f809a87-7201-4a65-bac0-fa1534a2d690

	measure '% pacientes com laborat.' = (DISTINCTCOUNT(laboratorio[NR_ATENDIMENTO])) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: LABORATORIO
		lineageTag: 5172c948-1896-4262-bfaa-53a419010100

	measure media_min_triagem =
			
			AVERAGE(fluxo[MIN_ENTRADA_X_TRIAGEM])
		formatString: 0.0
		displayFolder: TRIAGEM
		lineageTag: 2bff677f-5d2e-4f01-a37d-b3aa781c7329

	measure media_min_consulta =
			
			AVERAGE(fluxo[MIN_ENTRADA_X_CONSULTA])
		displayFolder: CONSULTA
		lineageTag: b36ca049-094b-4b07-91f5-169d60b526c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ID_CONSULTA_FORA_META =
			
			VAR MediaMinutos = Averagex(fluxo, fluxo[MIN_ENTRADA_X_CONSULTA])
			VAR Meta = Meta_consulta[Valor Meta_consulta]  // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
		formatString: 0
		displayFolder: CONSULTA
		lineageTag: adf3d051-a30d-4123-9473-8b19ac2dc861

	measure media_min_medicacao =
			
			AVERAGE(medicacao[MINUTOS])
		displayFolder: MEDICACOES
		lineageTag: 7579f412-643c-44a2-93f1-803832c1c903

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ID_MEDICACAO_FORA_META = ```
			
			VAR MediaMinutos = AVERAGEX ( medicacao, medicacao[MINUTOS] )
			VAR Meta = Meta_medicacao[Valor Meta_medicacao]  // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
			
			```
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 1581de92-6347-4660-be85-3a0b026ee868

	measure media_min_RX_ECG =
			
			AVERAGE('RX e ECG'[Diferença Minutos RX_ECG Solic/chec])
		displayFolder: RX/ECG
		lineageTag: 37a254d5-adaf-4066-852f-b3fdf6621bfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure media_min_TC_US =
			
			AVERAGE('TC e US'[Diferença minutos TC_US Solic/chec])
		displayFolder: TC/US
		lineageTag: c8896afe-65fd-4937-8d1d-2d62b8bd505e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure media_min_reavaliacao =
			
			AVERAGE(reavaliacao[Min_evolu_reav])
		displayFolder: REAVALIACAO
		lineageTag: bd3f0850-e468-402f-bb14-dadd795091b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure media_min_alta =
			
			AVERAGE(fluxo[MIN_ENTRADA_X_ALTA])
		displayFolder: ALTA
		lineageTag: 4e200af2-61dd-46eb-b901-8230ace9342a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_TRIAGEM =
			
			[Tempo_triagem_dinamico] / Meta_triagem[Valor Meta_triagem]
		lineageTag: e90314de-2d8c-4331-be4a-440f0efc19c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_CONSULTA =
			
			[Tempo_consulta_dinamico] / Meta_consulta[Valor Meta_consulta]
		lineageTag: 2fcf49fe-4f20-4920-948a-faf5f8eed415

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_MEDICACOES =
			
			[Tempo_medicacao_dinamico] / Meta_medicacao[Valor Meta_medicacao]
		lineageTag: 3f06a4fb-07d8-4029-a471-1a338a236e58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_RX_ECG =
			
			[Tempo_RX_ECG_dinamico] / Meta_ECG_RX[Valor Tempo Minutos]
		lineageTag: 66c068fb-e4a7-4b3f-8f29-e43cd9bff166

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_TC_US =
			
			[Tempo_TC_US_dinamico] / 'Metas tipo_TC_US'[Valor Meta_TC_US]
		lineageTag: 8478c6a6-bcf4-453d-ae5f-d9822d3d8245

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_REAVALIACAO =
			
			[Tempo_reavaliacao_dinamico] / Meta_reavaliacao[Valor Meta_reavaliacao]
		lineageTag: f2b6b4e2-157a-4192-bc78-d72301174a9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_DA_META_ALTA =
			
			[Tempo_alta_dinamico] / Meta_alta[Valor Meta_alta]
		lineageTag: 066cd62b-a803-445b-9cb7-1cf229f393d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Filtro_Simples_ID =
			
			VAR Sel = SELECTEDVALUE(Filtro_IDs[Medida])  // pega a opção escolhida no slicer
			RETURN
			SWITCH(
			    TRUE(),
			    // Sem nada selecionado OU "(Selecionar Tudo)" -> não filtra (passa tudo)
			    ISBLANK(Sel) || Sel = "(Selecionar Tudo)", 1,
			
			    // Mapeamento da opção do slicer -> medida correspondente (que já retorna 1/0/BLANK)
			    Sel = "Permanência Fora Meta", [ID_PERMANENCIA_FORA_META],
			    Sel = "Consulta Fora Meta",    [ID_CONSULTA_FORA_META],
			    Sel = "Medicação Fora Meta",   [ID_MEDICACAO_FORA_META],
			    Sel = "Reavaliação Fora Meta", [ID_REAVALIACAO_FORA_META],
			    Sel = "RX/ECG Fora Meta",      [ID_RX_ECG_FORA_META],
			    Sel = "TC/US Fora Meta",       [ID_TC_US_FORA_META],
			    Sel = "Triagem Fora Meta",     [ID_TRIAGEM_FORA_META],
			
			    // Fallback de segurança (se vier algum texto fora da lista): não filtra
			    1
			) * 1  // garante 0/1 numérico
		lineageTag: cf99e9fa-f5cf-4683-8382-36bd8cf845db

	measure ID_PERMANENCIA_FORA_META =
			
			VAR MediaMinutos = Averagex(fluxo,fluxo[MIN_ENTRADA_X_ALTA])
			VAR Meta = Meta_alta[Valor Meta_alta]  // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
		formatString: 0
		lineageTag: 73bb23de-e062-4933-a860-dff14152f301

	measure ID_REAVALIACAO_FORA_META =
			
			VAR MediaMinutos = Averagex(reavaliacao,reavaliacao[MINUTOS])
			VAR Meta = Meta_reavaliacao[Valor Meta_reavaliacao]  // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
		formatString: 0
		lineageTag: 7ac4fbe2-a012-4b29-9e47-b1a55f3bdd15

	measure ID_RX_ECG_FORA_META =
			
			VAR MediaMinutos = Averagex('RX e ECG', 'RX e ECG'[MINUTOS])
			VAR Meta = Meta_ECG_RX[Valor Tempo Minutos]  // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
		formatString: 0
		lineageTag: f16b41b0-e023-40cb-ac70-82af46102534

	measure ID_TC_US_FORA_META =
			
			VAR MediaMinutos = Averagex('TC e US', 'TC e US'[Diferença minutos TC_US Solic/chec])
			VAR Meta = 'Metas tipo_TC_US'[Valor Meta_TC_US] // pega o valor da meta no contexto
			RETURN
			    IF (
			        ISBLANK ( MediaMinutos ),
			        BLANK(),                                         // se não encontrou, retorna vazio
			        IF ( MediaMinutos >= Meta, 1, 0 )                // senão, faz a comparação
			    )
		formatString: 0
		lineageTag: a90ab0b9-c4dc-4410-8192-42c27c645ab4

	measure mediana_min_triagem = ```
			
			    MEDIAN(fluxo[MIN_ENTRADA_X_TRIAGEM])
			```
		displayFolder: TRIAGEM
		lineageTag: 5507b2ce-0a29-43a0-974e-717ac484046e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_TC_US =
			
			MEDIAN('TC e US'[Diferença minutos TC_US Solic/chec])
		displayFolder: TC/US
		lineageTag: 2fc044fc-f912-40f7-8583-1ba4b5238217

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_RX_ECG =
			
			MEDIAN('RX e ECG'[Diferença Minutos RX_ECG Solic/chec])
		displayFolder: RX/ECG
		lineageTag: a0bc03ec-1eeb-4ab0-9e1a-0e024344c31f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_reavaliacao =
			
			MEDIAN(reavaliacao[Min_evolu_reav])
		displayFolder: REAVALIACAO
		lineageTag: a0b0f57c-393c-4ea5-88dd-9d83e257ca87

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_medicacao =
			
			MEDIAN(medicacao[MINUTOS])
		displayFolder: MEDICACOES
		lineageTag: f92176d8-0f46-4c3d-871c-5700d7ead6d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_consulta =
			
			MEDIAN(fluxo[MIN_ENTRADA_X_CONSULTA])
		displayFolder: CONSULTA
		lineageTag: 8a8cdb86-9e32-4273-bc2f-64705373271e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mediana_min_alta =
			
			MEDIAN(fluxo[MIN_ENTRADA_X_ALTA])
		displayFolder: ALTA
		lineageTag: 5d0d08be-f9ae-439e-8de1-3a822e58d0bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_triagem_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_triagem],
			        "Mediana", [mediana_min_triagem],
			        [media_min_triagem]
			    )
		displayFolder: TRIAGEM
		lineageTag: 67716d19-578c-4f19-8c44-e35b3880bbba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_consulta_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_consulta],
			        "Mediana", [mediana_min_consulta],
			        [media_min_consulta]
			    )
		displayFolder: CONSULTA
		lineageTag: 04307f93-6c97-43ca-9849-06f5cb3947a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_medicacao_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_medicacao],
			        "Mediana", [mediana_min_medicacao],
			        [media_min_medicacao]
			    )
		displayFolder: MEDICACOES
		lineageTag: aebb818d-0ed3-4f89-ae1f-79919ad1e124

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_RX_ECG_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_RX_ECG],
			        "Mediana", [mediana_min_RX_ECG],
			        [media_min_RX_ECG]
			    )
		displayFolder: RX/ECG
		lineageTag: 8f821854-2a35-4342-9eaf-ea757bf1537a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_TC_US_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_TC_US],
			        "Mediana", [mediana_min_TC_US],
			        [media_min_TC_US]
			    )
		displayFolder: TC/US
		lineageTag: 55b3fad5-49ac-4879-a7cd-05ebfcd937a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_reavaliacao_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_reavaliacao],
			        "Mediana", [mediana_min_reavaliacao],
			        [media_min_reavaliacao]
			    )
		displayFolder: REAVALIACAO
		lineageTag: 643227fd-419e-4963-9029-4a3fe3c0e00c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tempo_alta_dinamico =
			-- usado no gráfico de tabela de tempo por mês da página "Resumo gerencial"
			VAR agregacao = SELECTEDVALUE(Media_mediana_resumo[Agregacao], "Média")
			RETURN
			    SWITCH(
			        agregacao,
			        "Média",   [media_min_alta],
			        "Mediana", [mediana_min_alta],
			        [media_min_alta]
			    )
		displayFolder: ALTA
		lineageTag: 0fb0db0e-61a0-41d0-8701-cb53c75cf04e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Atend > Tempo dispensação' =
			
			VAR LimiteMinutos = COALESCE( [Valor Meta_medicacao], 0 )   -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( medicacao[NR_ATENDIMENTO] ),
			    KEEPFILTERS ( medicacao[gera_lote] = "S" ),
			    FILTER (
			        medicacao,
			        NOT ISBLANK ( medicacao[MIN_SOLIC_X_DISPENSACAO] )
			            && medicacao[MIN_SOLIC_X_DISPENSACAO] >= 0
			            && medicacao[MIN_SOLIC_X_DISPENSACAO] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 88a97e82-92c9-4419-9300-6bbbfc6cd884

	measure 'Qtd Atend > Tempo checagem' =
			
			VAR LimiteMinutos = COALESCE( [Valor Meta_medicacao], 0 )   -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( medicacao[NR_ATENDIMENTO] ),
			    KEEPFILTERS ( medicacao[gera_lote] = "S" ),
			    FILTER (
			        medicacao,
			        NOT ISBLANK ( medicacao[MIN_DISP_X_CHECAGEM] )
			            && medicacao[MIN_DISP_X_CHECAGEM] >= 0
			            && medicacao[MIN_DISP_X_CHECAGEM] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: acdd694c-cdfe-4674-b116-176a09f2a7b2

	measure '% Atend > meta medicacoes' = ```
			
			VAR LimiteMinutos = COALESCE ( [Valor Meta_medicacao], 0 )
			VAR Sel = VALUE ( SELECTEDVALUE ( 'Parametro medicacoes fora da meta'[Order], -1 ) )
			
			VAR AtendAcima =
			    SWITCH (
			        Sel,
			        // 0 = Prescr. x dispensação (com lote)
			        0,
			            CALCULATE (
			                COUNT ( medicacao[NR_ATENDIMENTO] ),
			                KEEPFILTERS ( medicacao[gera_lote] = "S" ),
			                KEEPFILTERS ( NOT ISBLANK ( medicacao[MIN_SOLIC_X_DISPENSACAO] ) ),
			                KEEPFILTERS ( medicacao[MIN_SOLIC_X_DISPENSACAO] >= 0 ),
			                KEEPFILTERS ( medicacao[MIN_SOLIC_X_DISPENSACAO] > LimiteMinutos )
			            ),
			        // 1 = Dispens. x checagem (com lote)
			        1,
			            CALCULATE (
			                COUNT ( medicacao[NR_ATENDIMENTO] ),
			                KEEPFILTERS ( medicacao[gera_lote] = "S" ),
			                KEEPFILTERS ( NOT ISBLANK ( medicacao[MIN_DISP_X_CHECAGEM] ) ),
			                KEEPFILTERS ( medicacao[MIN_DISP_X_CHECAGEM] >= 0 ),
			                KEEPFILTERS ( medicacao[MIN_DISP_X_CHECAGEM] > LimiteMinutos )
			            ),
			        // 2 = Prescr. x checagem (sem lote)
			        2,
			            CALCULATE (
			                COUNT ( medicacao[NR_ATENDIMENTO] ),
			                KEEPFILTERS ( medicacao[gera_lote] <> "S" || ISBLANK ( medicacao[gera_lote] ) ),
			                KEEPFILTERS ( NOT ISBLANK ( medicacao[MINUTOS] ) ),
			                KEEPFILTERS ( medicacao[MINUTOS] >= 0 ),
			                KEEPFILTERS ( medicacao[MINUTOS] > LimiteMinutos )
			            ),
			        // 3 = Prescr. x checagem (todos)
			        3,
			            CALCULATE (
			                COUNT ( medicacao[NR_ATENDIMENTO] ),
			                KEEPFILTERS ( NOT ISBLANK ( medicacao[MINUTOS] ) ),
			                KEEPFILTERS ( medicacao[MINUTOS] >= 0 ),
			                KEEPFILTERS ( medicacao[MINUTOS] > LimiteMinutos )
			            ),
			        BLANK ()
			    )
			
			VAR Denom =
			    SWITCH (
			        Sel,
			        0, [Qtd prescrições com lote],
			        1, [Qtd prescrições com lote],
			        2, [Qtd prescrições sem lote],
			        3, [Qtd_Prescricoes_medicamentos],
			        BLANK ()
			    )
			
			RETURN
			IF ( ISBLANK ( Denom ) || Denom = 0, BLANK (), DIVIDE ( AtendAcima, Denom ) )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: 63c42e0b-8c50-4a09-89ac-341e10dc67c0

	measure '% reavaliacao' = DIVIDE((COUNT('reavaliacao'[NR_ATENDIMENTO])), DISTINCTCOUNT(fluxo[NR_ATENDIMENTO]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: REAVALIACAO
		lineageTag: 38d5172b-27ad-4e80-941a-b51ef0c96547

	measure 'Meta volume permanencia > 3h' = 0.10
		displayFolder: ALTA
		lineageTag: ff50f354-1c02-447a-b6ac-c3af02e1ba78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume consultas > 1h30' = 0.01
		displayFolder: CONSULTA
		lineageTag: 68dbd777-59c0-4e37-ba60-267e2f825d45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume conversao' = 0.06
		displayFolder: CONVERSAO
		lineageTag: d98bedd1-c1ce-4421-8ce7-c9ab605caddb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume LAB' = 0.98
		formatString: 0
		displayFolder: LABORATORIO
		lineageTag: ffa887f8-ac81-42c8-a843-c46cf81f996f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Meta volume medicacoes > 30min' = 0.04
		displayFolder: MEDICACOES
		lineageTag: 20ce97f5-4f5a-4ce2-a444-88caa449901d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume reavaliacoes > 45min' = 0.08
		displayFolder: REAVALIACAO
		lineageTag: 0e48b0c1-3bce-4503-b55f-bc838e74013b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume TC' = 0.15
		displayFolder: TC/US
		lineageTag: 967011c3-f65c-4485-b6d9-f884526b451d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume triagens > 12min' = 0.03
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: 2c457b5f-f1f2-4b72-af6a-68fce920af86

	measure '% laboratorio' = COUNT(laboratorio[NR_ATENDIMENTO])/DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: LABORATORIO
		lineageTag: 072d6d3b-b4a6-45aa-be4b-9d7f988b7fc7

	measure '% TC' =
			CALCULATE(
			    (COUNT('TC e US'[NR_ATENDIMENTO])), 'TC e US'[tipo] = "TC"
			    ) / DISTINCTCOUNT(fluxo[NR_ATENDIMENTO])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: c444f21e-19c4-40dd-b651-b74b4b3e7ec0

	measure 'Cor meta volume' = ```
			
			VAR IdSel =
			    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Pedido]) 
			VAR ValorSel =
			    SWITCH(
			        IdSel,
			        0, [% conversao],
			        1, [% pacientes medicados],
			        2, [Media medicacoes por pac],
			     --   3, [% laboratorio],
			        4, [% pacientes com laborat.],
			        5, [Media exames lab por pac],
			     --   6, [% TC],
			        7, [% pacientes com TC],
			        8, [% Triagem >12min],
			        9, [% Consulta >1:30h],
			        10, [% Medicação >30min],
			        11, [% Reavaliações >45min],
			        12, [% Alta >3h],
			        13, [% desfecho do médico do atend. (0)],
			        14, [Media exames TC por pac]
			    )
			VAR MetaSel =
			    SWITCH(
			        IdSel,
			        0, [Valor Meta dinâmica volume conversão],
			        1, [Valor Meta dinâm volume pacs medicados],
			        2, [Valor Meta dinâm volume medicações por pac],
			     --   3, [Valor Meta dinâm volume lab],
			        4, [Valor Meta dinâm volume pacs lab],
			        5, [Valor Meta dinâm volume laboratorio por pac],
			     --   6, [Valor Meta dinâm volume TC],
			        7, [Valor Meta dinâm volume pacs TC],
			        8, [Valor Meta dinâm volume triagem > meta],
			        9, [Valor Meta dinâm volume consulta > meta],
			        10, [Valor Meta dinâm volume medicação> meta],
			        11, [Valor Meta dinâm volume reavaliação > meta],
			        12, [Valor Meta dinâm volume permanência > meta],
			        13, [Valor Meta dinâm volume desfecho do médico do atend.],
			        14, [Valor Valor Meta dinâm volume TC por pac]
			    )
			VAR IsMaiorMelhor = IdSel = 13
			VAR OK =
			    IF(
			        IsMaiorMelhor,
			        ValorSel >= MetaSel,   -- 13: maior é melhor
			        ValorSel <= MetaSel    -- demais: menor é melhor
			    )
			RETURN
			    IF( OK, "#107C10", "#EC6464" )
			
			```
		displayFolder: METAS
		lineageTag: 50323fbf-413d-42c3-95fe-99d3776a3135

	measure 'Meta volume pacs LAB' = 0.30
		formatString: 0
		displayFolder: LABORATORIO
		lineageTag: 5f0b0409-514b-49a6-b6c9-ffaf3c4b3f6b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% Atend > Tempo consulta (0)' =
			
			VAR LimiteMinutos = COALESCE( Meta_consulta[Valor Meta_consulta], 0 )
			VAR TotalAtend    = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        FILTER ( fluxo, fluxo[MIN_ENTRADA_X_CONSULTA] > LimiteMinutos )
			    )
			RETURN
			IF (
			    TotalAtend = 0 || ISBLANK(TotalAtend),
			    BLANK(),                                  -- sem atendimentos: fica em branco
			    DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0     -- com atendimentos: 0%, 25%, etc.
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONSULTA
		lineageTag: 3c9407e8-c9fd-403d-90e2-c99442ce56b3

	measure '% Atend > Tempo alta (0)' =
			
			VAR LimiteMinutos = COALESCE( Meta_alta[Valor Meta_alta], 0 )
			VAR TotalAtend    = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( fluxo[MIN_ENTRADA_X_ALTA] > LimiteMinutos )
			    )
			RETURN
			IF ( TotalAtend = 0, BLANK(), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ALTA
		lineageTag: 58e7b8df-9cc1-44bb-9cef-5a48e0575e46

	measure '% conversao (0)' =
			
			VAR Numerador =
			    CALCULATE(
			        COUNT(fluxo[NR_ATENDIMENTO]),
			        fluxo[DESTINO] = "Internado",
			        USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA])
			    )
			VAR Denominador =
			    CALCULATE(
			        COUNT(fluxo[NR_ATENDIMENTO]),
			        USERELATIONSHIP('Calendario'[Data], fluxo[DATA])
			    )
			RETURN
			IF ( Denominador = 0, BLANK(), DIVIDE ( Numerador, Denominador, 0 ) + 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: 819f81f1-13a3-4949-84a7-33891fa8c3e6

	measure '% laboratorio (0)' = ```
			
			VAR Denom = DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			VAR Num   = COUNT ( laboratorio[NR_ATENDIMENTO] )
			RETURN
			IF ( Denom = 0, BLANK(), DIVIDE ( Num, Denom, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: LABORATORIO
		lineageTag: e98af3d2-817e-4514-bdff-f14e6c62e4dc

	measure '% pacientes com laborat. (0)' = ```
			
			VAR Denom = DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			VAR Num   = DISTINCTCOUNT ( laboratorio[NR_ATENDIMENTO] )
			RETURN
			IF ( Denom = 0, BLANK(), DIVIDE ( Num, Denom, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: LABORATORIO
		lineageTag: 7968a795-39ff-478a-bc74-5d49aeb525e2

	measure '% Atend > Tempo medicacao (0)' = ```
			
			VAR LimiteMinutos = COALESCE( Meta_medicacao[Valor Meta_medicacao], 0 )
			VAR TotalAtend    = COUNT ( medicacao[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( medicacao[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( medicacao[MINUTOS] > LimiteMinutos )
			    )
			RETURN
			IF ( TotalAtend = 0, BLANK(), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MEDICACOES
		lineageTag: bda8bdc8-58ec-4b72-8b0b-4660106006fb

	measure '% Atend > Tempo reavaliacao (0)' = ```
			
			VAR LimiteMinutos =
			    COALESCE ( [Valor Meta_reavaliacao], 0 )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            VAR DtIni = reavaliacao[DT_SOLIC_REAVALIACAO]
			            VAR DtEvo = reavaliacao[DT_EVO_PRESC]
			            VAR DtFim = reavaliacao[DT_FIM_REAVALIACAO]
			            VAR DtRef =
			                SWITCH (
			                    TRUE (),
			                    ISBLANK ( DtEvo ) && ISBLANK ( DtFim ), BLANK (),
			                    ISBLANK ( DtEvo ), DtFim,
			                    ISBLANK ( DtFim ), DtEvo,
			                    DtEvo <= DtFim, DtEvo,
			                    DtFim
			                )
			            VAR Minutos = DATEDIFF ( DtIni, DtRef, MINUTE )
			            RETURN
			                NOT ISBLANK ( DtIni )
			                    && NOT ISBLANK ( DtRef )
			                    && Minutos > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            NOT ISBLANK ( reavaliacao[DT_SOLIC_REAVALIACAO] )
			                && (
			                    NOT ISBLANK ( reavaliacao[DT_EVO_PRESC] )
			                        || NOT ISBLANK ( reavaliacao[DT_FIM_REAVALIACAO] )
			                )
			        )
			    )
			RETURN
			    IF (
			        TotalAtend = 0 || ISBLANK ( TotalAtend ),
			        BLANK (),
			        DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: REAVALIACAO
		lineageTag: 53bd84f5-3141-4fe7-8928-6019f650b98c

	measure '% TC (0)' = ```
			
			VAR Num =
			    CALCULATE (
			        COUNT ( 'TC e US'[NR_ATENDIMENTO] ),
			        'TC e US'[tipo] = "TC"
			    )
			VAR Den = DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			RETURN
			IF ( Den = 0, BLANK(), DIVIDE ( Num, Den, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 03cd9f44-1cfd-4062-a1ea-482e3005b35f

	measure '% pacientes com TC (0)' = ```
			
			VAR Num =
			    CALCULATE (
			        DISTINCTCOUNT ( 'TC e US'[NR_ATENDIMENTO] ),
			        'TC e US'[tipo] = "TC"
			    )
			VAR Den = DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			RETURN
			IF ( Den = 0, BLANK(), DIVIDE ( Num, Den, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 662aed30-945a-4a24-a4fc-e7ef35eea5fe

	measure '% Atend > Tempo triagem (0)' = ```
			
			VAR LimiteMinutos = COALESCE ( Meta_triagem[Valor Meta_triagem], 0 )
			VAR TotalAtend    = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( fluxo[MIN_ENTRADA_X_TRIAGEM] > LimiteMinutos )
			    )
			RETURN
			IF ( TotalAtend = 0, BLANK(), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TRIAGEM
		lineageTag: 78d1aaf6-6047-47f8-99e8-d8c08e250421

	measure 'Qtd Atend > Tempo medicacao (s/ lote)' =
			
			VAR LimiteMinutos = Meta_medicacao[Valor Meta_medicacao]         -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( medicacao[NR_ATENDIMENTO] ),
			    KEEPFILTERS ( medicacao[gera_lote] = "N" ),
			    FILTER (
			        medicacao,
			        medicacao[MINUTOS] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: a59f2014-5f5a-4e9e-92fe-c6feebc06fc1

	measure 'Qtd prescrições com lote' = CALCULATE(COUNT(medicacao[NR_ATENDIMENTO]),medicacao[GERA_LOTE]="S")
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 20cdf401-d1d4-459b-9c78-c7a5d224a83f

	measure 'Qtd prescrições sem lote' = CALCULATE(COUNT(medicacao[NR_ATENDIMENTO]),medicacao[GERA_LOTE]="N")
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: 6233b428-1172-4e95-b125-7d55cd49d0c3

	measure 'Qtd prescric com e sem lote' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Parametro medicacoes fora da meta'[Order] ),
			    0, [Qtd prescrições com lote],
			    1, [Qtd prescrições com lote],
			    2, [Qtd prescrições sem lote],
			    3, [Qtd_Prescricoes_medicamentos], 
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: MEDICACOES
		lineageTag: fb5b0826-40dd-4063-b209-cf3c797655db

	measure '% meta volume conversao (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% conversao] / 'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão]
		displayFolder: CONVERSAO
		lineageTag: c230d3b2-d63a-434a-b2a9-553d3df58e1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume lab (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% laboratorio (0)] / 'Meta dinâm volume lab'[Valor Meta dinâm volume lab]
		displayFolder: LABORATORIO
		lineageTag: e97da1bf-d467-4976-aaf1-317a56607237

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta volume selecionada' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Param metas de volumes'[Param metas de volumes Pedido], -1 ),
			    0, 'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão]*100,
			    1, 'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados]*100,
			    2, 'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac], -- média
			  --  3, 'Meta dinâm volume lab'[Valor Meta dinâm volume lab]*100,
			    4, 'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab]*100,
			    5, 'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac], -- média
			  --  6, 'Meta dinâm volume TC'[Valor Meta dinâm volume TC]*100,
			    6, 'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC]*100,
			    7, 'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac],
			    8, 'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta]*100,
			    9, 'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta]*100,
			    10, 'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta]*100,
			    11, 'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta]*100,
			    12, 'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta]*100,
			    13, 'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.]*100,
			    
			    BLANK()
			)
			```
		displayFolder: METAS
		lineageTag: e5b7c7a9-786d-462a-91dd-57df2810bd4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume pacs c/ lab (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% pacientes com laborat. (0)] / 'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab]
		displayFolder: LABORATORIO
		lineageTag: ad6e1332-9081-4d17-a625-cd3297bd0400

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume TC (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% TC (0)] / 'Meta dinâm volume TC'[Valor Meta dinâm volume TC]
		displayFolder: TC/US
		lineageTag: fc9b730a-b866-4590-9833-abae9dd07451

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume pacs c/ TC (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% pacientes com TC] / 'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC]
		displayFolder: TC/US
		lineageTag: 4ae79595-0b22-4af8-9f32-e25fbd4debb8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume triagem > meta (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% Atend > Tempo triagem (0)] / 'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta]
		displayFolder: TRIAGEM
		lineageTag: 69aa6b61-b896-4e56-9978-458e2284391f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume consulta > meta (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% Atend > Tempo consulta (0)] / 'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta]
		displayFolder: CONSULTA
		lineageTag: 96fc867c-781d-42b2-83ae-07836ee187da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume medicação > meta (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% Atend > Tempo medicacao (0)] / 'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta]
		displayFolder: MEDICACOES
		lineageTag: 108b1eb5-5df9-4cf0-a5f8-9142bc395019

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume reavaliação > meta (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% Atend > Tempo reavaliacao (0)] / 'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta]
		displayFolder: REAVALIACAO
		lineageTag: 0ea8b682-5c2b-42b9-8486-ceb4dc8f202f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume perman > meta (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% Atend > Tempo alta (0)] / 'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta]
		displayFolder: ALTA
		lineageTag: 591ca635-d8bb-4d6b-aaae-6acacb1cb3c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_cor_atendimento =
			
			DIVIDE(
			    DISTINCTCOUNT( Fluxo[nr_atendimento] ),
			    CALCULATE(
			        DISTINCTCOUNT( Fluxo[nr_atendimento] ),
			        ALL( Fluxo[cor] )
			    )
			)
		displayFolder: OUTROS
		lineageTag: 83083fe6-4663-4137-b727-68444c4da57e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Media_Pacientes_Dia =
			
			DIVIDE(
			    COUNTROWS( Fluxo ),
			    DISTINCTCOUNT( fluxo[DT_ENTRADA].[Dia] )
			)
		displayFolder: OUTROS
		lineageTag: f8c1a592-dad7-4874-b13a-c269f35b2fa7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_altas_cid =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT( Fluxo[nr_atendimento] ),
			        NOT ISBLANK( Fluxo[CD_CID] )
			    ),
			    DISTINCTCOUNT( Fluxo[nr_atendimento] )
			)
		displayFolder: ALTA
		lineageTag: 06f79b72-cd77-4c62-abee-5f45275299bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_altas_Semcid =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT( Fluxo[nr_atendimento] ),
			        ISBLANK( Fluxo[CD_CID] )
			    ),
			    DISTINCTCOUNT( Fluxo[nr_atendimento] )
			)
		displayFolder: ALTA
		lineageTag: 1efaecad-fe66-426c-a67d-84a666f1fab0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% meta volume pacs medicados (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% pacientes medicados] / 'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados]
		displayFolder: MEDICACOES
		lineageTag: b42ea004-c543-4afc-a23f-d79134c690bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media tempo alta_hhmmss' =
			
			DIVIDE( [media_min_alta], 24 * 60 )   -- minutos / 1440  -> fração de dia
		formatString: 0.000
		displayFolder: ALTA
		lineageTag: 0e23c5e3-499a-4051-9704-6396b632d9e7

	measure 'Qtd Atend > Tempo imgxlaudo' =
			
			VAR LimiteMinutos = 'Meta TC_US_imgxlaudo'[Valor Meta TC_US_imgxlaudo]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'TC e US'[NR_PRESCRICAO]),
			    FILTER (
			        'TC e US',
			        'TC e US'[Diferença minutos TC_US imagemXlaudo] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 1c070367-c560-4404-80de-57d565864681

	measure '% Atend > tempo (até img)' =
			
			VAR Limite = [Valor Meta TC_US_imagem]
			VAR Escolha = VALUE( SELECTEDVALUE( 'Parametro meta exames imagem'[Value2] ) )
			VAR TotalAtend =
			    CALCULATE( COUNT( 'TC e US'[NR_PRESCRICAO] ) )
			VAR AtendAcima =
			    CALCULATE(
			        COUNT( 'TC e US'[NR_PRESCRICAO] ),
			        FILTER(
			            'TC e US',
			            SWITCH(
			                Escolha,
			                0, 'TC e US'[Diferença minutos TC_US Solic/checXimag],
			                1, 'TC e US'[Diferença minutos TC_US solicXimagem]
			            ) > Limite
			        )
			    )
			RETURN
			DIVIDE( AtendAcima, TotalAtend, 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 18d6588a-c926-4285-a063-8eb5d4e34e14

	measure '% Atend > tempo tc3' =
			
			VAR Limite = [Valor Meta_TC_US]
			VAR Escolha = VALUE( SELECTEDVALUE( 'Parametro meta exames imagem'[Value2] ) )
			VAR TotalAtend =
			    CALCULATE( COUNT( 'TC e US'[NR_PRESCRICAO] ) )
			VAR AtendAcima =
			    CALCULATE(
			        COUNT( 'TC e US'[NR_PRESCRICAO] ),
			        FILTER(
			            'TC e US',
			            SWITCH(
			                Escolha,
			                0, 'TC e US'[Diferença minutos TC_US Solic/chec],
			                1, 'TC e US'[diferença minutos tc_us]
			            ) > Limite
			        )
			    )
			RETURN
			DIVIDE( AtendAcima, TotalAtend, 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 3398ad2e-a058-4ada-8501-dba74c1d8f6d

	measure 'Qtd Atend > checagem_Tempo TC' =
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'TC e US'[NR_PRESCRICAO]),
			    FILTER (
			        'TC e US',
			        'TC e US'[Diferença minutos TC_US Solic/chec] > LimiteMinutos
			    )
			)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 75d518fd-d9c7-41a8-b24f-7e5b23693bbc

	measure '% Atend > Tempo (img x laudo)' =
			
			VAR LimiteMinutos = 'Meta TC_US_imgxlaudo'[Valor Meta TC_US_imgxlaudo]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ),
			        FILTER (
			            'TC e US',
			            'TC e US'[Diferença minutos TC_US imagemXlaudo] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( 'TC e US'[NR_PRESCRICAO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
		displayFolder: TC/US
		lineageTag: bd6aa419-63b0-4ec0-b4f4-d58602b96660

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Atend > Tempo RX_ECG (check)' = ```
			
			VAR Limite =
			    Meta_ECG_RX[Valor Tempo Minutos]   
			VAR Escolha =
			    VALUE( SELECTEDVALUE( 'Parametro meta exames imagem'[Value2] ) )   -- 0 = Checagem / 1 = Solicitação
			RETURN
			CALCULATE (
			    COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			    FILTER (
			        'RX e ECG',
			        SWITCH (
			            Escolha,
			            0, 'RX e ECG'[Diferença Minutos RX_ECG Solic/chec],   -- Checagem
			            1, 'RX e ECG'[Diferença Minutos RX_ECG]             -- Solicitação
			        ) > Limite
			    )
			)
			```
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: c8f7756f-90e6-426c-b1c6-c9be52a85c2b

	measure '% Atend > Tempo RX_ECG (check)' = ```
			
			VAR Limite =
			    Meta_ECG_RX[Valor Tempo Minutos]
			VAR Escolha =
			    VALUE( SELECTEDVALUE( 'Parametro meta exames imagem'[Value2] ) )   -- 0 = Checagem / 1 = Solicitação
			VAR TotalAtend =
			    CALCULATE( COUNT( 'RX e ECG'[NR_PRESCRICAO] ) )
			VAR AtendAcima =
			    CALCULATE(
			        COUNT( 'RX e ECG'[NR_PRESCRICAO] ),
			        FILTER(
			            'RX e ECG',
			            SWITCH(
			                Escolha,
			                0, 'RX e ECG'[Diferença Minutos RX_ECG Solic/chec],   -- Checagem
			                1, 'RX e ECG'[Diferença Minutos RX_ECG]             -- Solicitação
			            ) > Limite
			        )
			    )
			RETURN
			DIVIDE( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 7b7f876a-cafe-444b-9755-9fb007ec0649

	measure '% Atend > Tempo RX (resumo ger)' = ```
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'RX e ECG'[tipo] = "RX" ),
			        FILTER (
			            'RX e ECG',
			            'RX e ECG'[Diferença Minutos RX_ECG Solic/chec] > LimiteMinutos
			        )
			    ) + 0
			VAR TotalAtend =
			    CALCULATE (
			        COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'RX e ECG'[tipo] = "RX" )
			    )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		displayFolder: RX/ECG
		lineageTag: 34144143-7d6f-4791-983f-309e5ad8973c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Atend > Tempo RX (resumo ger)' =
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]            -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			    KEEPFILTERS ( 'RX e ECG'[tipo] = "RX" ),
			    FILTER (
			        'RX e ECG',
			        'RX e ECG'[Diferença Minutos RX_ECG Solic/chec] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: e8c913c1-b48e-43bc-ac98-0f319e203c1a

	measure '% Atend > Tempo TC (resumo ger)' = ```
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'TC e US'[tipo] = "TC" ),
			        FILTER (
			            'TC e US',
			            'TC e US'[Diferença minutos TC_US Solic/chec] > LimiteMinutos
			        )
			    ) + 0
			VAR TotalAtend =
			    CALCULATE ( 
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ) ,
			        KEEPFILTERS ( 'TC e US'[tipo] = "TC" )
			    )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: cd80b3fd-8117-46e5-a027-93ff2bf8f33f

	measure 'Qtd Atend > Tempo TC (resumo ger)' =
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'TC e US'[NR_PRESCRICAO]),
			    KEEPFILTERS ( 'TC e US'[tipo] = "TC" ),
			    FILTER (
			        'TC e US',
			        'TC e US'[Diferença minutos TC_US Solic/chec] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: TC/US
		lineageTag: e825c407-4f1d-435d-85fa-e5f3f6b03ea4

	measure 'Tempo TC/US(sol/chec) por Atendim. (min)' = ```
			
			VAR T =
			    // 1) Agrupa por atendimento
			    SUMMARIZE(
			        'TC e US',
			        'TC e US'[NR_ATENDIMENTO],
			        "DuracaoMin",
			            VAR MinBase =
			                // menor data entre Checagem/Solicitação dentro do atendimento
			                MINX(
			                    'TC e US',
			                    VAR Chec  = 'TC e US'[DT_CHECAGEM]
			                    VAR Solic = 'TC e US'[DT_LIBERACAO]
			                    RETURN
			                        IF(
			                            ISBLANK(Chec),
			                            Solic,   // se não tem checagem, usa solicitação
			                            Chec     // senão, usa checagem
			                        )
			                )
			            VAR MaxLaudo =
			                // maior data de laudo dentro do atendimento
			                MAX('TC e US'[DT_LAUDO])
			            RETURN
			                // 2) Se faltar qualquer data, retorna BLANK (não entra na média)
			                IF(
			                    NOT ISBLANK(MinBase) && NOT ISBLANK(MaxLaudo),
			                    // 3) Diferença em minutos (1440 = 24*60), protegendo contra negativos
			                    MAX(0, INT( (MaxLaudo - MinBase) * 1440 ))
			                )
			    )
			RETURN
			// 4) Média dos minutos por atendimento (BLANKs são ignorados pela AVERAGEX)
			AVERAGEX(T, [DuracaoMin])
			
			```
		displayFolder: TC/US
		lineageTag: 3e644be8-8947-4f45-ae6a-88542cc294e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tempo RX_ECG(solic/chec) por Paciente (min)' = ```
			
			VAR Pacientes =
			    DISTINCT( 'RX e ECG'[NR_ATENDIMENTO] )   // lista de atendimentos no contexto
			RETURN
			AVERAGEX(
			    Pacientes,
			    VAR p = 'RX e ECG'[NR_ATENDIMENTO]       // atendimento atual no iterador
			
			    // menor data entre Checagem/Solicitação dentro do atendimento
			    VAR MinBase =
			        MINX(
			            FILTER( 'RX e ECG', 'RX e ECG'[NR_ATENDIMENTO] = p ),
			            VAR Chec  = 'RX e ECG'[DT_CHECAGEM]
			            VAR Solic = 'RX e ECG'[DT_SOLICITACAO]
			            RETURN
			                IF(
			                    ISBLANK(Chec),
			                    Solic,   // se não tem checagem, usa solicitação
			                    Chec     // senão, usa checagem
			                )
			        )
			
			    // maior data de exame dentro do atendimento
			    VAR MaxExame =
			        CALCULATE(
			            MAX( 'RX e ECG'[DT_EXAME] ),
			            'RX e ECG'[NR_ATENDIMENTO] = p
			        )
			
			    RETURN
			        IF(
			            ISBLANK(MinBase) || ISBLANK(MaxExame),
			            BLANK(),  // se faltar uma das datas, ignora no cálculo
			            MAX( 0, INT( ( MaxExame - MinBase ) * 1440 ) )   // minutos, protegendo contra negativos
			        )
			)
			
			```
		displayFolder: RX/ECG
		lineageTag: 502c1b0f-ef8d-4e4f-a620-dcf9ee35abbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '%Metas Batidas' = ```
			
			VAR _MetasSel =
			    VALUES ( 'Param metas de volumes'[Param metas de volumes Pedido] )
			
			VAR _Base =
			    ADDCOLUMNS(
			        _MetasSel,
			        "Real",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Medidas'[% conversao (0)],
			                1, 'Medidas'[% pacientes medicados],
			                2, 'Medidas'[Media medicacoes por pac],
			             --   3, 'Medidas'[% laboratorio (0)],
			                4, 'Medidas'[% pacientes com laborat. (0)],
			                5, 'Medidas'[Media exames lab por pac],
			             --   6, 'Medidas'[% TC (0)],
			                6, 'Medidas'[% pacientes com TC (0)],
			                7, 'Medidas'[Media exames TC por pac],
			                8, 'Medidas'[% Atend > Tempo triagem (0)],
			                9, 'Medidas'[% Atend > Tempo consulta (0)],
			                10, 'Medidas'[% Atend > Tempo medicacao (0)],
			                11, 'Medidas'[% Atend > Tempo reavaliacao (0)],
			                12, 'Medidas'[% Atend > Tempo alta (0)],
			                13, 'Medidas'[% desfecho do médico do atend. (0)]
			                
			
			            ),
			        "Meta",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão],
			                1, 'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados],
			                2, 'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac],
			             --   3, 'Meta dinâm volume lab'[Valor Meta dinâm volume lab],
			                4, 'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab],
			                5, 'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac],
			             --   6, 'Meta dinâm volume TC'[Valor Meta dinâm volume TC],
			                6, 'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC],
			                7, 'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac],
			                8, 'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta],
			                9, 'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta],
			                10, 'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta],
			                11, 'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta],
			                12, 'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta],
			                13, 'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.]
			                
			            )
			    )
			
			VAR _Validas =
			    FILTER ( _Base, NOT ISBLANK([Real]) && NOT ISBLANK([Meta]) && [Meta] <> 0 )
			
			VAR _Batidas =
			    SUMX(
			        _Validas,
			        VAR _Id = 'Param metas de volumes'[Param metas de volumes Pedido]
			        RETURN
			            IF(
			                _Id = 13,
			                IF( [Real] >= [Meta], 1, 0 ),   -- 13: maior é melhor
			                IF( [Real] <= [Meta], 1, 0 )    -- demais: menor é melhor
			            )
			    )
			
			RETURN
			DIVIDE( _Batidas, COUNTROWS(_Validas) )
			
			```
		displayFolder: METAS
		lineageTag: 85ac10e5-8b01-4a47-9576-6be3034cf870

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Atend > Tempo ECG (resumo ger)' = ```
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]
			RETURN
			CALCULATE (
			    COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			    KEEPFILTERS ( 'RX e ECG'[tipo] = "ECG" ),
			    FILTER (
			        'RX e ECG',
			        'RX e ECG'[Diferença Minutos RX_ECG Solic/chec] > LimiteMinutos
			    )
			) + 0
			
			```
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: 77180a87-20f2-4043-a595-90ad084c96ef

	measure '% Atend > Tempo ECG (resumo ger)' = ```
			
			VAR LimiteMinutos = Meta_ECG_RX[Valor Tempo Minutos]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'RX e ECG'[tipo] = "ECG" ),
			        FILTER (
			            'RX e ECG',
			            'RX e ECG'[Diferença Minutos RX_ECG Solic/chec] > LimiteMinutos
			        )
			    ) +0
			VAR TotalAtend =
			    CALCULATE (
			        COUNT ( 'RX e ECG'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'RX e ECG'[tipo] = "ECG" )
			    )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 1681f689-04b7-4813-9983-d2c9fc2f3499

	measure 'Qtd Atend > Tempo US (resumo ger)' =
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]          -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( 'TC e US'[NR_PRESCRICAO]),
			    KEEPFILTERS ( 'TC e US'[tipo] = "US" ),
			    FILTER (
			        'TC e US',
			        'TC e US'[Diferença minutos TC_US Solic/chec] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: TC/US
		lineageTag: 95f83c8e-4c3c-413b-8cf3-b600bb1ce07e

	measure '% Atend > Tempo US (resumo ger)' = ```
			
			VAR LimiteMinutos = 'Metas tipo_TC_US'[Valor Meta_TC_US]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ),
			        KEEPFILTERS ( 'TC e US'[tipo] = "US" ),
			        FILTER (
			            'TC e US',
			            'TC e US'[Diferença minutos TC_US Solic/chec] > LimiteMinutos
			        )
			    ) + 0
			VAR TotalAtend =
			    CALCULATE ( 
			        COUNT ( 'TC e US'[NR_PRESCRICAO] ) ,
			        KEEPFILTERS ( 'TC e US'[tipo] = "US" )
			    )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 20657a99-eed5-4626-98d9-c3f0284c4f9b

	measure 'Qtd Metas Batidas' = ```
			
			VAR _MetasSel =
			    VALUES ( 'Param metas de volumes'[Param metas de volumes Pedido] )
			
			VAR _Base =
			    ADDCOLUMNS(
			        _MetasSel,
			        "Real",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Medidas'[% conversao (0)],
			                1, 'Medidas'[% pacientes medicados],
			                2, 'Medidas'[Media medicacoes por pac],
			             --   3, 'Medidas'[% laboratorio (0)],
			                4, 'Medidas'[% pacientes com laborat. (0)],
			                5, 'Medidas'[Media exames lab por pac],
			             --   6, 'Medidas'[% TC (0)],
			                7, 'Medidas'[% pacientes com TC (0)],
			                8, 'Medidas'[% Atend > Tempo triagem (0)],
			                9, 'Medidas'[% Atend > Tempo consulta (0)],
			                10, 'Medidas'[% Atend > Tempo medicacao (0)],
			                11, 'Medidas'[% Atend > Tempo reavaliacao (0)],
			                12, 'Medidas'[% Atend > Tempo alta (0)],
			                13, 'Medidas'[% desfecho do médico do atend. (0)],
			                14, 'Medidas'[Média diária desfechos do médico (10-16)],
			                15, 'Medidas'[Media exames TC por pac]
			
			            ),
			        "Meta",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão],
			                1, 'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados],
			                2, 'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac],
			             --   3, 'Meta dinâm volume lab'[Valor Meta dinâm volume lab],
			                4, 'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab],
			                5, 'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac],
			             --   6, 'Meta dinâm volume TC'[Valor Meta dinâm volume TC],
			                7, 'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC],
			                8, 'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta],
			                9, 'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta],
			                10, 'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta],
			                11, 'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta],
			                12, 'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta],
			                13, 'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.],
			                14, 'Meta dinâm volume media desfechos 10-16h'[Valor Meta dinâm volume media desfechos 10-16h],
			                15, 'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac]
			
			            )
			    )
			
			VAR _Validas =
			    FILTER ( _Base, NOT ISBLANK([Real]) && NOT ISBLANK([Meta]) && [Meta] <> 0 )
			
			RETURN
			SUMX( _Validas, IF( [Real] <= [Meta], 1, 0 ) )
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: 8e3d6a56-dd2f-4005-aa0d-8406b9a4d6ac

	measure 'Qtd Metas Consideradas' = ```
			
			VAR _MetasSel =
			    VALUES ( 'Param metas de volumes'[Param metas de volumes Pedido] )
			
			VAR _Base =
			    ADDCOLUMNS(
			        _MetasSel,
			        "Real",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Medidas'[% conversao (0)],
			                1, 'Medidas'[% pacientes medicados],
			                2, 'Medidas'[Media medicacoes por pac],
			              --  3, 'Medidas'[% laboratorio (0)],
			                4, 'Medidas'[% pacientes com laborat. (0)],
			                5, 'Medidas'[Media exames lab por pac],
			             --   6, 'Medidas'[% TC (0)],
			                7, 'Medidas'[% pacientes com TC (0)],
			                8, 'Medidas'[% Atend > Tempo triagem (0)],
			                9, 'Medidas'[% Atend > Tempo consulta (0)],
			                10, 'Medidas'[% Atend > Tempo medicacao (0)],
			                11, 'Medidas'[% Atend > Tempo reavaliacao (0)],
			                12, 'Medidas'[% Atend > Tempo alta (0)],
			                13, 'Medidas'[% desfecho do médico do atend. (0)],
			                14, 'Medidas'[Media exames TC por pac]
			
			            ),
			        "Meta",
			            SWITCH(
			                'Param metas de volumes'[Param metas de volumes Pedido],
			                0, 'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão],
			                1, 'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados],
			                2, 'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac],
			             --   3, 'Meta dinâm volume lab'[Valor Meta dinâm volume lab],
			                4, 'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab],
			                5, 'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac],
			             --   6, 'Meta dinâm volume TC'[Valor Meta dinâm volume TC],
			                7, 'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC],
			                8, 'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta],
			                9, 'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta],
			                10, 'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta],
			                11, 'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta],
			                12, 'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta],
			                13, 'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.],
			                14, 'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac]
			
			            )
			    )
			
			RETURN
			COUNTROWS( FILTER ( _Base, NOT ISBLANK([Real]) && NOT ISBLANK([Meta]) && [Meta] <> 0 ) )
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: a0133ced-9ab1-4364-8a11-8f6b8e02d007

	measure 'Tooltip Metas Batidas' = ```
			
			VAR b = [Qtd Metas Batidas]
			VAR t = [Qtd Metas Consideradas]
			RETURN
			FORMAT(b,"0") & " de " & FORMAT(t,"0")
			
			```
		displayFolder: METAS
		lineageTag: 5f16a6cb-67ab-4392-828f-355bdcb88b09

	measure 'qtd atend (conversao)' =
			-- muda o relacionamento da tabela de calendário para a página de conversão
			VAR DatasSel = VALUES('Calendario'[Data])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(fluxo[NR_ATENDIMENTO]),
			    REMOVEFILTERS('Calendario_conversao'),
			    TREATAS(DatasSel, 'Calendario'[Data])
			)
		formatString: 0
		displayFolder: CONVERSAO
		lineageTag: eb67364e-171b-48e8-8427-e81053e167b6

	measure '% conversao (conversao)' =
			-- usado na página de conversão, pois muda o relacionamento da tabela de calendário
			[qtd internados] / [qtd atend (conversao)]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: ebd2ec57-613f-489b-88a7-8035dceff30c

	measure '% auditorias de conversao' =
			
			[qtd auditoria de conversao] / [qtd internados]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: b9c730d6-45a2-4e6d-9a90-92db68d5738f

	measure 'qtd auditoria de conversao' =
			
			CALCULATE(
			    COUNT(fluxo[NR_ATENDIMENTO_INT]),
			    fluxo[DT_AUDITORIA] <> BLANK(),
			    USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA]))
		formatString: 0
		displayFolder: CONVERSAO
		lineageTag: 7c30a764-ea4b-439e-9206-442159ab2741

	measure 'qtd auditorias até 72h' =
			
			CALCULATE(
			    COUNT(fluxo[NR_ATENDIMENTO_INT]),
			    fluxo[dt_auditoria] <> BLANK(),
			    FILTER(
			        fluxo,
			        -- garante que a auditoria não é antes da internação
			        fluxo[dt_auditoria] >= fluxo[dt_internacao]
			            && (fluxo[dt_auditoria] - fluxo[dt_internacao]) <= 3
			    )
			)
		formatString: 0
		displayFolder: CONVERSAO
		lineageTag: 7d80a749-e231-4321-b6df-39444b179dd2

	measure '% auditorias até 72h' =
			
			DIVIDE(
			    [qtd auditorias até 72h],
			    [qtd internados]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: 062f51ea-92e4-451d-aef8-e881a1a1e12c

	measure 'qtd auditorias internação conforme' = ```
			
			CALCULATE(
			    COUNT(fluxo[NR_ATENDIMENTO_INT]),
			    fluxo[dt_auditoria] <> BLANK(),
			    fluxo[intern_conforme_audit] = "Sim",
			    USERELATIONSHIP('Calendario'[Data], fluxo[DT_INTERNACAO_DATA])
			)
			
			```
		displayFolder: CONVERSAO
		lineageTag: 98249f76-2082-4090-abae-56000e263115

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% auditorias internação conforme' = ```
			
			DIVIDE(
			    [qtd auditorias internação conforme],
			    [qtd auditoria de conversao]
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CONVERSAO
		lineageTag: 079179f3-2731-4691-aef6-1f33caf35c36

	measure 'Qtd Atend > Tempo procedimento' =
			
			VAR LimiteMinutos = Meta_procedimento[Valor Meta_procedimento]        -- medida do parâmetro
			RETURN
			CALCULATE (
			    COUNT ( procedimento[NR_ATENDIMENTO] ),
			    FILTER (
			        procedimento,
			        procedimento[MINUTOS] > LimiteMinutos
			    )
			) + 0
		formatString: 0
		displayFolder: PROCEDIMENTO
		lineageTag: ca7527c4-4ef2-492b-ae2c-079f0f6f3192

	measure '% Atend > Tempo procedimento' =
			
			VAR LimiteMinutos = Meta_procedimento[Valor Meta_procedimento]
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( procedimento[NR_ATENDIMENTO]),
			        FILTER (
			            procedimento,
			            procedimento[MINUTOS] > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE ( COUNT ( procedimento[NR_ATENDIMENTO] ) )
			RETURN
			DIVIDE ( AtendAcima, TotalAtend, 0 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PROCEDIMENTO
		lineageTag: eaa04a57-0842-498c-9753-1eac6f1033ff

	measure 'Qtd RX' =
			
			CALCULATE(
			    COUNT('RX e ECG'[NR_ATENDIMENTO]),
			    'RX e ECG'[tipo] = "RX"
			)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: d5a1db2f-baa5-4bbe-8345-c792a225eedd

	measure 'Qtd ECG' =
			
			CALCULATE(
			    COUNT('RX e ECG'[NR_ATENDIMENTO]),
			    'RX e ECG'[tipo] = "ECG"
			)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: e036f8bb-6a17-4a60-b6b1-237b7498d58b

	measure 'Qtd TC' =
			
			CALCULATE(
			    COUNT('TC e US'[NR_ATENDIMENTO]),
			    'TC e US'[tipo] = "TC"
			)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 8b9361bd-ea3e-43a5-b84b-21f74c1042d2

	measure 'Qtd US' =
			
			CALCULATE(
			    COUNT('TC e US'[NR_ATENDIMENTO]),
			    'TC e US'[tipo] = "US"
			)
		formatString: 0
		displayFolder: TC/US
		lineageTag: 3c8adbe1-da01-45e5-9002-95a5c4b970cd

	measure 'Meta % (P25 entre unidades)' = ```
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),  
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.25
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: METAS
		lineageTag: fccd9d20-492d-48e8-9c3c-1001188a9b5e

	measure 'KPI Valor (por unidade)' =
			
			VAR IdSel =
			    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Pedido])
			RETURN
			SWITCH(
			    IdSel,
			    0, [% conversao],
			    1, [% pacientes medicados],
			    2, [Media medicacoes por pac],
			   -- 3, [% laboratorio],
			    4, [% pacientes com laborat.],
			    5, [Media exames lab por pac],
			   -- 6, [% TC],
			    6, [% pacientes com TC],
			    8, [% Atend > Tempo triagem (0)],
			    9, [% Atend > Tempo consulta (0)],
			    10, [% Atend > Tempo medicacao (0)],
			    11, [% Atend > Tempo reavaliacao (0)],
			    12, [% Atend > Tempo alta (0)],
			    13, [% desfecho do médico do atend. (0)],
			    14, [Média diária desfechos (10-16)],
			    7, [Media exames TC por pac],
			
			    BLANK()
			)
		displayFolder: METAS
		lineageTag: 0e8899db-fdb8-400d-8293-a94ab1ae52ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta % (P50 entre unidades)' =
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),        -- <<< troque pelo seu campo de unidade
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.5
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: METAS
		lineageTag: 09c9ebf2-db2d-4094-948f-5b7c0523c247

	measure 'Meta % (P75 entre unidades)' =
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),        -- <<< troque pelo seu campo de unidade
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.75
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: METAS
		lineageTag: ebf0d574-a157-4626-97af-6befb15974e8

	measure 'Data última atualização' = ```
			
			    CALCULATE ( MAX ( fluxo[DT_ENTRADA] ), ALL (fluxo) )
			
			```
		formatString: General Date
		displayFolder: OUTROS
		lineageTag: 97bae188-f43e-4a0f-9bec-58a98cefd41c

	measure 'Valor metas volumes (Últimos 12M)' = ```
			
			VAR Idx =
			    SELECTEDVALUE ( 'Param metas de volumes'[Param metas de volumes Pedido] )
			
			-- último dia selecionado no slicer (respeita a seleção do calendário)
			VAR DataFim =
			    MAXX ( ALLSELECTED ( 'Calendario'[Data] ), 'Calendario'[Data] )
			
			VAR MesFim =
			    DATE ( YEAR ( DataFim ), MONTH ( DataFim ), 1 )
			
			VAR MesIni =
			    EDATE ( MesFim, -11 )
			
			VAR MesEixo =
			    SELECTEDVALUE ( 'EixoMes'[InicioMes] )
			
			VAR FimMesEixo =
			    MIN ( EOMONTH ( MesEixo, 0 ), DataFim )
			
			RETURN
			IF (
			    ISBLANK ( DataFim )
			        || ISBLANK ( MesEixo )
			        || MesEixo < MesIni
			        || MesEixo > MesFim,
			    BLANK (),
			    CALCULATE (
			        SWITCH (
			            Idx,
			            0, 'Medidas'[% conversao (0)],
			            1, 'Medidas'[% pacientes medicados],
			            2, 'Medidas'[Media medicacoes por pac],
			           -- 3, 'Medidas'[% laboratorio (0)],
			            4, 'Medidas'[% pacientes com laborat. (0)],
			            5, 'Medidas'[Media exames lab por pac],
			           -- 6, 'Medidas'[% TC (0)],
			            7, 'Medidas'[% pacientes com TC (0)],
			            8, 'Medidas'[% Atend > Tempo triagem (0)],
			            9, 'Medidas'[% Atend > Tempo consulta (0)],
			            10, 'Medidas'[% Atend > Tempo medicacao (0)],
			            11, 'Medidas'[% Atend > Tempo reavaliacao],
			            12, 'Medidas'[% Atend > Tempo alta (0)],
			            13, 'Medidas'[% desfecho do médico do atend.],
			            14, 'Medidas'[Media exames TC por pac]
			
			        ),
			        REMOVEFILTERS ( 'Calendario' ),
			        DATESBETWEEN ( 'Calendario'[Data], MesEixo, FimMesEixo )
			    )
			)
			
			```
		displayFolder: METAS
		lineageTag: c0e109ba-323d-4cd8-9c88-4eee8569815b

		formatStringDefinition =
				VAR Idx =
				    SELECTEDVALUE ( 'Param metas de volumes'[Param metas de volumes Pedido] )
				
				VAR EhMedia =
				    Idx IN { 2, 5, 14 }   -- 2 = Media medicacoes por pac, 5 = Media exames lab por pac, 14 = Media de Exames de Tc por Pac
				
				RETURN
				    IF(
				        EhMedia,
				        "#,0.00",
				        "0.00%"
				    )

	measure 'Media medicacoes por pac' = ```
			
			AVERAGEX(
			    VALUES(Vias_medicamentos[NR_ATENDIMENTO]),
			    CALCULATE(
			        COUNTROWS(
			            SUMMARIZE(
			                Vias_medicamentos,
			                Vias_medicamentos[NR_PRESCRICAO],
			                Vias_medicamentos[CD_MATERIAL]
			            )
			        ), 
			       NOT ( Vias_medicamentos[CD_MATERIAL] IN { 84278, 84288, 84153, 84271 }) -- Não considera: Cloreto De Sodio 0,9% (10ml), Soro Fisiologico (100ml e 250ml),  Agua Para Injecao (10ml)
			       
			    )
			)
			
			
			```
		displayFolder: MEDICACOES
		lineageTag: 9d8a4eea-0702-42b3-8198-30d5c0c72f29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media exames lab por pac' =
			
			AVERAGEX(
			    VALUES(laboratorio[NR_ATENDIMENTO]),
			    CALCULATE(COUNTROWS(laboratorio))
			)
		displayFolder: LABORATORIO
		lineageTag: e9616f50-d5d8-4588-ae20-b4038cb43cc5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta qtd (P25 entre unidades)' = ```
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),  
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.25
			)
			```
		displayFolder: METAS
		lineageTag: c78ab724-16f4-45a2-bd07-27c831a3b311

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta qtd (P50 entre unidades)' = ```
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),  
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.50
			)
			```
		displayFolder: METAS
		lineageTag: 68406af3-ee8a-444d-9351-b917cadc9494

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta qtd (P75 entre unidades)' = ```
			
			VAR T =
			    ADDCOLUMNS(
			        VALUES( fluxo[UNIDADE] ),  
			        "__v", [KPI Valor (por unidade)]
			    )
			RETURN
			PERCENTILEX.INC(
			    FILTER( T, NOT ISBLANK( [__v] ) ),               -- ignora unidades sem valor
			    [__v],
			    0.75
			)
			```
		displayFolder: METAS
		lineageTag: 940b93f2-aeb9-4f4e-8252-060d748e94da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'media meta volume lab por pac (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[Media exames lab por pac] / 'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac]
		displayFolder: LABORATORIO
		lineageTag: 9ed9365d-7995-432e-a528-f6d7bbd0d378

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% desfecho do médico do atend. (0)' = ```
			
			VAR Numerador =
			    [Qtd desfecho do médico do atend.]
			VAR Denominador =
			    DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			RETURN
			    IF (
			        Denominador = 0 || ISBLANK ( Denominador ),
			        BLANK (),
			        DIVIDE ( Numerador, Denominador, 0 ) + 0
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ALTA
		lineageTag: d3941a5f-9d78-476a-ad78-8473dca717de

	measure 'Qtd desfecho do médico do atend.' =
			
			CALCULATE (
			    DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] ),
			    NOT ISBLANK ( fluxo[DT_DESFECHO] ),
			    fluxo[MEDICO_DESFECHO] = fluxo[MEDICO_ATENDIMENTO]
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: ac50a253-4b88-49fd-9087-767194dc8aa7

	measure '% meta volume de desfecho do médico do atend. (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[% desfecho do médico do atend. (0)] / 'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.]
		displayFolder: ALTA
		lineageTag: 622dfa8d-1751-4736-94f3-9ea9c34afa79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Direção meta volume selecionada' =
			
			SWITCH (
			    SELECTEDVALUE ( 'Param metas de volumes'[Param metas de volumes Pedido], -1 ),
			    0, "< melhor",
			    1, "< melhor",
			    2, "< melhor",
			  --  3, "< melhor",
			    4, "< melhor",
			    5, "< melhor",
			    6, "< melhor",
			    7, "< melhor",
			    8, "< melhor",
			    9, "< melhor",
			    10, "< melhor",
			    11, "< melhor",
			    12, "< melhor",
			    13, "> melhor",
			    14, "< melhor",
			    BLANK()
			)
		displayFolder: METAS
		lineageTag: 1a44f551-2ab2-4a84-b6ba-26b59045ff50

	measure 'Qtd desfechos' =
			
			CALCULATE (
			    DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] ),
			    NOT ISBLANK ( fluxo[DT_DESFECHO] )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 12b96479-fed2-481d-95c1-a27b6071456e

	measure 'Qtd desfechos (Médico desfecho)' =
			
			VAR _PorMedico =
			    CALCULATE (
			        DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] ),
			        NOT ISBLANK ( fluxo[DT_DESFECHO] ),
			
			        -- DATA: usar DATA_DESFECHO no lugar da data do atendimento
			        CROSSFILTER ( Calendario[Data], fluxo[DATA], NONE ),
			        USERELATIONSHIP ( Calendario[Data], fluxo[DATA_DESFECHO] ),
			
			        -- Médico: usar MEDICO_DESFECHO
			        CROSSFILTER ( DimMedico[Medico], fluxo[MEDICO_ATENDIMENTO], NONE ),
			        USERELATIONSHIP ( DimMedico[Medico], fluxo[MEDICO_DESFECHO] ),
			
			        -- Turno: usar TURNO_DESFECHO
			        CROSSFILTER ( DimTurno[Turno], fluxo[TURNO_ATENDIMENTO], NONE ),
			        USERELATIONSHIP ( DimTurno[Turno], fluxo[TURNO_DESFECHO] )
			    )
			VAR _Total =
			    CALCULATE (
			        DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] ),
			        NOT ISBLANK ( fluxo[DT_DESFECHO] ),
			        REMOVEFILTERS ( DimMedico ),
			
			        -- DATA: usar DATA_DESFECHO também no total
			        CROSSFILTER ( Calendario[Data], fluxo[DATA], NONE ),
			        USERELATIONSHIP ( Calendario[Data], fluxo[DATA_DESFECHO] ),
			
			        -- Turno: usar TURNO_DESFECHO
			        CROSSFILTER ( DimTurno[Turno], fluxo[TURNO_ATENDIMENTO], NONE ),
			        USERELATIONSHIP ( DimTurno[Turno], fluxo[TURNO_DESFECHO] )
			    )
			RETURN
			IF ( ISINSCOPE ( DimMedico[Medico] ), _PorMedico, _Total ) + 0
		formatString: 0
		displayFolder: ALTA
		lineageTag: 8afcd801-117a-4b6b-90ec-0a898ba10ad2

	measure 'media meta volume medicações por pac (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[Media medicacoes por pac] / 'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac]
		displayFolder: MEDICACOES
		lineageTag: c9d29439-91f9-4603-b008-63e027d4083f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% desfecho do médico do atend.' =
			
			DIVIDE (
			    [Qtd desfecho do médico do atend.],
			    DISTINCTCOUNT ( fluxo[NR_ATENDIMENTO] )
			)
		displayFolder: ALTA
		lineageTag: 1c7213bd-01f5-4343-89ab-ff7dea22432e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variação Absoluta Mês' =
			
			VAR MedidaSelecionada =
			    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Campos])
			
			VAR ValorAtual =
			    SWITCH(
			        TRUE(),
			        MedidaSelecionada = NAMEOF('Medidas'[% conversao (0)]), [% conversao (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes medicados]), [% pacientes medicados],
			        MedidaSelecionada = NAMEOF('Medidas'[Media medicacoes por pac]), [Media medicacoes por pac],
			      --  MedidaSelecionada = NAMEOF('Medidas'[% laboratorio (0)]), [% laboratorio (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes com laborat. (0)]), [% pacientes com laborat. (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[Media exames lab por pac]), [Media exames lab por pac],
			      --  MedidaSelecionada = NAMEOF('Medidas'[% TC (0)]), [% TC (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes com TC (0)]), [% pacientes com TC (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo triagem (0)]), [% Atend > Tempo triagem (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo consulta (0)]), [% Atend > Tempo consulta (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo medicacao (0)]), [% Atend > Tempo medicacao (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo reavaliacao (0)]), [% Atend > Tempo reavaliacao (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo alta (0)]), [% Atend > Tempo alta (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[% desfecho do médico do atend. (0)]), [% desfecho do médico do atend. (0)],
			        MedidaSelecionada = NAMEOF('Medidas'[Média diária desfechos (10-16)]), [Média diária desfechos (10-16)],
			        MedidaSelecionada = NAMEOF('Medidas'[Media exames TC por pac]), [Media exames TC por pac],
			        BLANK()
			    )
			
			VAR ValorMesAnterior = [Valor Meta Mês Anterior]
			
			RETURN
			    IF(
			        ISBLANK(ValorAtual) || ISBLANK(ValorMesAnterior),
			        BLANK(),
			        ValorAtual - ValorMesAnterior
			    )
		displayFolder: METAS
		lineageTag: 7932bd02-fc92-493d-9c7b-aa762ba2755b

		formatStringDefinition =
				VAR MedidaSelecionada =
				    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Campos])
				
				VAR EhMedia =
				    MedidaSelecionada IN {
				        NAMEOF('Medidas'[Media medicacoes por pac]),
				        NAMEOF('Medidas'[Media exames lab por pac]),
				        NAMEOF('Medidas'[Media exames TC por pac]),
				        NAMEOF('Medidas'[Média diária desfechos (10-16)])
				    }
				
				RETURN
				    IF(
				        EhMedia,
				        "+#,0.00;-#,0.00;0.00",
				        "+0.00%;-0.00%;0.00%"
				    )

	measure 'Valor Meta Mês Anterior' = ```
			VAR MedidaSelecionada = 
			    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Campos])
			
			VAR Resultado = 
			    SWITCH(
			        TRUE(),
			        MedidaSelecionada = NAMEOF('Medidas'[% conversao (0)]),
			            CALCULATE(
			                [% conversao (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes medicados]),
			            CALCULATE(
			                [% pacientes medicados],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[Media medicacoes por pac]),
			            CALCULATE(
			                [Media medicacoes por pac],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			     --   MedidaSelecionada = NAMEOF('Medidas'[% laboratorio (0)]),
			     --       CALCULATE(
			     --           [% laboratorio (0)],
			     --           DATEADD('Calendario'[Data], -1, MONTH)
			     --       ),
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes com laborat. (0)]),
			            CALCULATE(
			                [% pacientes com laborat. (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[Media exames lab por pac]),
			            CALCULATE(
			                [Media exames lab por pac],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			     --   MedidaSelecionada = NAMEOF('Medidas'[% TC (0)]),
			     --       CALCULATE(
			     --           [% TC (0)],
			     --           DATEADD('Calendario'[Data], -1, MONTH)
			     --       ),
			        MedidaSelecionada = NAMEOF('Medidas'[% pacientes com TC (0)]),
			            CALCULATE(
			                [% pacientes com TC (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo triagem (0)]),
			            CALCULATE(
			                [% Atend > Tempo triagem (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo consulta (0)]),
			            CALCULATE(
			                [% Atend > Tempo consulta (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo medicacao (0)]),
			            CALCULATE(
			                [% Atend > Tempo medicacao (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo reavaliacao (0)]),
			            CALCULATE(
			                [% Atend > Tempo reavaliacao (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% Atend > Tempo alta (0)]),
			            CALCULATE(
			                [% Atend > Tempo alta (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[% desfecho do médico do atend. (0)]),
			            CALCULATE(
			                [% desfecho do médico do atend. (0)],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			        MedidaSelecionada = NAMEOF('Medidas'[Media exames TC por pac]),
			            CALCULATE(
			                [Media exames TC por pac],
			                DATEADD('Calendario'[Data], -1, MONTH)
			            ),
			
			        BLANK()
			    )
			
			RETURN
			    Resultado
			```
		displayFolder: METAS
		lineageTag: c1cba250-cfa4-470c-bfba-407a0c859ccb

		formatStringDefinition =
				VAR MedidaSelecionada =
				    SELECTEDVALUE('Param metas de volumes'[Param metas de volumes Campos])
				
				VAR EhMedia =
				    MedidaSelecionada IN {
				        NAMEOF('Medidas'[Media medicacoes por pac]),
				        NAMEOF('Medidas'[Media exames lab por pac]),
				        NAMEOF('Medidas'[Media exames TC por pac])
				    }
				
				RETURN
				    IF(
				        EhMedia,
				        "#,0.00",     -- número (média)
				        "0.00%"      -- percentual
				    )

	measure 'Direção meta (num)' = ```
			
			VAR d = [Direção meta volume selecionada]
			RETURN
			    SWITCH(
			        TRUE(),
			        d = "> melhor",  1,   -- aumentar é melhor
			        d = "< melhor", -1,   -- reduzir é melhor
			        BLANK()
			    )
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: 99ce0c63-7014-476f-8cf5-0b9bb89182df

	measure 'Ícone Var Abs (código)' = ```
			
			VAR v   = [Variação Absoluta Mês]
			VAR dir = [Direção meta (num)]         -- 1 = ↑ é bom | -1 = ↓ é bom
			VAR s   = SIGN(v)                       -- 1 = ↑ | -1 = ↓ | 0 = igual
			VAR bom = (s = dir)
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(v) || ISBLANK(dir), BLANK(),
			        v = 0, 0,                       -- neutro
			        v > 0 && bom,  2,               -- ↑ verde
			        v < 0 && bom,  1,               -- ↓ verde
			        v > 0 && NOT bom, -1,           -- ↑ vermelho
			        v < 0 && NOT bom, -2            -- ↓ vermelho
			    )
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: 9829549b-0d25-4c61-bf36-6dead097b132

	measure 'Qtd Metas Consideradas (Últimos 12M)' = ```
			
			VAR DataFim =
			    MAXX ( ALLSELECTED ( 'Calendario'[Data] ), 'Calendario'[Data] )
			VAR MesFim =
			    DATE ( YEAR ( DataFim ), MONTH ( DataFim ), 1 )
			VAR MesIni =
			    EDATE ( MesFim, -11 )
			
			VAR MesEixo =
			    SELECTEDVALUE ( 'EixoMes'[InicioMes] )
			VAR FimMesEixo =
			    MIN ( EOMONTH ( MesEixo, 0 ), DataFim )
			
			RETURN
			IF (
			    ISBLANK ( DataFim )
			        || ISBLANK ( MesEixo )
			        || MesEixo < MesIni
			        || MesEixo > MesFim,
			    BLANK (),
			    CALCULATE (
			        [Qtd Metas Consideradas],
			        REMOVEFILTERS ( 'Calendario' ),
			        DATESBETWEEN ( 'Calendario'[Data], MesEixo, FimMesEixo )
			    )
			)
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: e8446c11-a919-46a9-97d4-ddf549f0f7fb

	measure 'Tooltip Metas Batidas (Últimos 12M)' = ```
			
			VAR b = [Qtd Metas Batidas (Últimos 12M)]
			VAR t = [Qtd Metas Consideradas (Últimos 12M)]
			RETURN
			IF (
			    ISBLANK ( b ) && ISBLANK ( t ),
			    BLANK (),
			    FORMAT ( COALESCE ( b, 0 ), "0" ) & " de " & FORMAT ( COALESCE ( t, 0 ), "0" )
			)
			
			```
		displayFolder: METAS
		lineageTag: 562f1d6a-1212-4478-abc6-dd9dec5e086b

	measure '%Metas Batidas (Últimos 12M)' = ```
			
			VAR DataFim =
			    MAXX ( ALLSELECTED ( 'Calendario'[Data] ), 'Calendario'[Data] )
			VAR MesFim =
			    DATE ( YEAR ( DataFim ), MONTH ( DataFim ), 1 )
			VAR MesIni =
			    EDATE ( MesFim, -11 )
			
			VAR MesEixo =
			    SELECTEDVALUE ( 'EixoMes'[InicioMes] )
			VAR FimMesEixo =
			    MIN ( EOMONTH ( MesEixo, 0 ), DataFim )
			
			-- garante que só desenha mês com movimento (senão dá 100% falso)
			VAR TemDadosNoMes =
			    CALCULATE (
			        COUNTROWS ( 'fluxo' ),
			        REMOVEFILTERS ( 'Calendario' ),
			        DATESBETWEEN ( 'Calendario'[Data], MesEixo, FimMesEixo )
			    )
			
			RETURN
			IF (
			    ISBLANK ( DataFim )
			        || ISBLANK ( MesEixo )
			        || MesEixo < MesIni
			        || MesEixo > MesFim
			        || TemDadosNoMes = 0,
			    BLANK (),
			    CALCULATE (
			        [%Metas Batidas],
			        REMOVEFILTERS ( 'Calendario' ),
			        DATESBETWEEN ( 'Calendario'[Data], MesEixo, FimMesEixo )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: METAS
		lineageTag: 00a1a360-9b7c-4c22-b46f-08ce52df94e0

	measure 'Qtd Metas Batidas (Últimos 12M)' = ```
			
			VAR DataFim =
			    MAXX ( ALLSELECTED ( 'Calendario'[Data] ), 'Calendario'[Data] )
			VAR MesFim =
			    DATE ( YEAR ( DataFim ), MONTH ( DataFim ), 1 )
			VAR MesIni =
			    EDATE ( MesFim, -11 )
			
			VAR MesEixo =
			    SELECTEDVALUE ( 'EixoMes'[InicioMes] )
			VAR FimMesEixo =
			    MIN ( EOMONTH ( MesEixo, 0 ), DataFim )
			
			RETURN
			IF (
			    ISBLANK ( DataFim )
			        || ISBLANK ( MesEixo )
			        || MesEixo < MesIni
			        || MesEixo > MesFim,
			    BLANK (),
			    CALCULATE (
			        [Qtd Metas Batidas],
			        REMOVEFILTERS ( 'Calendario' ),
			        DATESBETWEEN ( 'Calendario'[Data], MesEixo, FimMesEixo )
			    )
			)
			
			```
		formatString: 0
		displayFolder: METAS
		lineageTag: 17fb8aa7-5ae3-4f62-af2a-b913fccb599d

	measure 'Qtd desfechos (10-16 | dt_desfecho)' = ```
			
			CALCULATE (
			    [Qtd desfechos],  -- DISTINCTCOUNT NR_ATENDIMENTO com DT_DESFECHO preenchida
			
			    -- Hora 10–16 (desfecho)
			    USERELATIONSHIP ( fluxo[HR_DESFECHO], Horas[HORAS] ),
			    Horas[Plantao_6h(10h-16h)] = 1,
			
			    -- Data do desfecho (em vez da data do atendimento)
			    CROSSFILTER ( Calendario[Data], fluxo[DATA], NONE ),
			    USERELATIONSHIP ( Calendario[Data], fluxo[DATA_DESFECHO] )
			)
			
			```
		formatString: 0
		displayFolder: ALTA
		lineageTag: e13dba12-3c4a-4c1b-b9c3-68abb38b3c7b

	measure 'Média diária desfechos (10-16)' = ```
			
			IF(
			    ISINSCOPE(DimMedico[Medico]),
			    [Média diária desfechos do médico (10-16)],
			    AVERAGEX(
			        FILTER(
			            ALLSELECTED(DimMedico[Medico]),
			            CALCULATE([Qtd Desfechos (10-16 | Médico desfecho)]) > 0
			        ),
			        CALCULATE([Média diária desfechos do médico (10-16)])
			    )
			)
			
			```
		displayFolder: ALTA
		lineageTag: 3e3e88b4-9a31-497d-82b7-019f8436925f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total desfechos (10-16) por médico' =
			
			CALCULATE (
			    [Qtd desfechos (10-16 | dt_desfecho)],
			    CROSSFILTER ( DimMedico[Medico], fluxo[MEDICO_ATENDIMENTO], NONE ),
			    USERELATIONSHIP ( DimMedico[Medico], fluxo[MEDICO_DESFECHO] )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 49ac6a6d-286a-4349-a1b9-3401633d83bd

	measure 'Dias com desfecho (10-16 | Médico desfecho)' =
			
			CALCULATE (
			    DISTINCTCOUNT ( fluxo[DATA_DESFECHO] ),
			
			    USERELATIONSHIP ( fluxo[HR_DESFECHO], Horas[HORAS] ),
			    Horas[Plantao_6h(10h-16h)] = 1,
			
			    CROSSFILTER ( Calendario[Data], fluxo[DATA], NONE ),
			    USERELATIONSHIP ( Calendario[Data], fluxo[DATA_DESFECHO] ),
			
			    CROSSFILTER ( DimMedico[Medico], fluxo[MEDICO_ATENDIMENTO], NONE ),
			    USERELATIONSHIP ( DimMedico[Medico], fluxo[MEDICO_DESFECHO] )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 9458fd8f-b5c9-47e6-8a68-908cbffb7535

	measure 'Dias com desfecho (10-16 | Total)' =
			
			CALCULATE (
			    DISTINCTCOUNT ( fluxo[DATA_DESFECHO] ),
			
			    USERELATIONSHIP ( fluxo[HR_DESFECHO], Horas[HORAS] ),
			    Horas[Plantao_6h(10h-16h)] = 1,
			
			    CROSSFILTER ( Calendario[Data], fluxo[DATA], NONE ),
			    USERELATIONSHIP ( Calendario[Data], fluxo[DATA_DESFECHO] ),
			
			    REMOVEFILTERS ( DimMedico )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 1c74a684-188d-4d85-b7f0-b9e31bdd0e1f

	measure 'Qtd desfechos (10-16 | Médico desfecho)' =
			
			CALCULATE (
			    [Qtd Desfechos (10-16 | dt_desfecho)],
			
			    -- Médico: usar MEDICO_DESFECHO
			    CROSSFILTER ( DimMedico[Medico], fluxo[MEDICO_ATENDIMENTO], NONE ),
			    USERELATIONSHIP ( DimMedico[Medico], fluxo[MEDICO_DESFECHO] )
			)
		formatString: 0
		displayFolder: ALTA
		lineageTag: 8088d1e7-fe3c-4125-b3de-3d913b60080f

	measure 'Média diária desfechos do médico (10-16)' =
			
			DIVIDE(
			    [Qtd Desfechos (10-16 | Médico desfecho)],
			    [Dias com desfecho (10-16 | Médico desfecho)]
			)
		displayFolder: ALTA
		lineageTag: a97fafa4-eefc-40b7-954d-4f8d5cf708a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'media meta volume desfechos 10h-16h (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[Média diária desfechos (10-16)] / 'Meta dinâm volume media desfechos 10-16h'[Valor Meta dinâm volume media desfechos 10-16h]
		displayFolder: ALTA
		lineageTag: 7a1e0675-100a-4a87-8277-3721ad7fea25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd Atend > Tempo RX (check)' =
			
			CALCULATE(
			    [Qtd Atend > Tempo RX_ECG (check)],
			    KEEPFILTERS( 'RX e ECG'[tipo] = "RX" )
			)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: c5031c68-f705-4049-903a-8f1a8ebecccd

	measure 'Qtd Atend > Tempo ECG (check)' =
			
			CALCULATE(
			    [Qtd Atend > Tempo RX_ECG (check)],
			    KEEPFILTERS( 'RX e ECG'[tipo] = "ECG" )
			)
		formatString: 0
		displayFolder: RX/ECG
		lineageTag: 050574f8-e724-4414-be94-29c9f2eff283

	measure '% Atend > Tempo ECG (check)' =
			
			CALCULATE(
			    [% Atend > Tempo RX_ECG (check)],
			    KEEPFILTERS( 'RX e ECG'[tipo] = "ECG" )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 752083fc-5491-4026-9799-83030d73d85c

	measure '% Atend > Tempo RX (check)' =
			
			CALCULATE(
			    [% Atend > Tempo RX_ECG (check)],
			    KEEPFILTERS( 'RX e ECG'[tipo] = "RX" )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RX/ECG
		lineageTag: 6f1890ce-3889-4d17-949b-4e63a0f0ff54

	measure '% Atend > tempo TC (solic/check x laudo)' =
			
			CALCULATE(
			    [% Atend > tempo tc3],
			    KEEPFILTERS( 'TC e US'[tipo] = "TC" )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: 424b82e4-4764-4889-9b16-1d5947ab853f

	measure '% Atend > tempo US (solic/check x laudo)' =
			
			CALCULATE(
			    [% Atend > tempo tc3],
			    KEEPFILTERS( 'TC e US'[tipo] = "US" )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TC/US
		lineageTag: c7ee677d-beaf-412e-8901-99fa5e9af23b

	measure '_Ind Vol - Maior é melhor' =
			
			SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] ) = "Desfecho do médico do atend."
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 04f2dd49-502b-4d3c-8185-164323910871

	measure 'Valor Indicador Volume' = ```
			
			SWITCH(
			    SELECTEDVALUE('Dim Indicadores Volume'[Indicador]),
			    "Conversão", [% conversao (0)],
			    "Pacs medicados", [% pacientes medicados],
			    "Medicações por paciente", [Media medicacoes por pac],
			    "Pacs c/ exames laboratoriais", [% pacientes com laborat. (0)],
			    "Laboratório por paciente", [Media exames lab por pac],
			    "Pacs c/ exames de TC", [% pacientes com TC (0)],
			    "TCs por paciente", [Media exames TC por pac],
			    "Triagem acima da meta", [% Atend > Tempo triagem (0)],
			    "Consulta acima da meta", [% Atend > Tempo consulta (0)],
			    "Medicação acima da meta", [% Atend > Tempo medicacao (0)],
			    "Reavaliação acima da meta", [% Atend > Tempo reavaliacao (0)],
			    "Permanência acima da meta", [% Atend > Tempo alta (0)],
			    "Desfecho do médico do atend.", [% desfecho do médico do atend. (0)]
			)
			
			```
		lineageTag: 92dc7da9-46d3-4718-b7b8-ce5f12f750f6

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente", "#,##0.00",
				        _Ind = "Medicações por paciente", "#,##0.00",
				        _Ind = "TCs por paciente", "#,##0.00",
				        "0.00%"
				    )
				
				```

	measure 'Meta Indicador Volume' = ```
			
			SWITCH(
			    SELECTEDVALUE('Dim Indicadores Volume'[Indicador]),
			    "Conversão", [Valor Meta dinâmica volume conversão],
			    "Pacs medicados", [Valor Meta dinâm volume pacs medicados],
			    "Medicações por paciente", [Valor Meta dinâm volume medicações por pac],
			    "Pacs c/ exames laboratoriais", [Valor Meta dinâm volume pacs lab],
			    "Laboratório por paciente", [Valor Meta dinâm volume laboratorio por pac],
			    "Pacs c/ exames de TC", [Valor Meta dinâm volume pacs TC],
			    "TCs por paciente", [Valor Valor Meta dinâm volume TC por pac],
			    "Triagem acima da meta", [Valor Meta dinâm volume triagem > meta],
			    "Consulta acima da meta", [Valor Meta dinâm volume consulta > meta],
			    "Medicação acima da meta", [Valor Meta dinâm volume medicação> meta],
			    "Reavaliação acima da meta", [Valor Meta dinâm volume reavaliação > meta],
			    "Permanência acima da meta", [Valor Meta dinâm volume permanência > meta],
			    "Desfecho do médico do atend.", [Valor Meta dinâm volume desfecho do médico do atend.]
			)
			
			```
		lineageTag: a5df0acf-384b-44ac-853f-12ed7f73c171

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Ind Vol - Direção num (por indicador)' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			RETURN
			    SWITCH (
			        _Ind,
			        "Desfecho do médico do atend.", 1,
			        -1
			    )
		formatString: 0
		lineageTag: 5588db0a-5eeb-4f05-b2e4-f6d5c8426298

	measure '_Ind Vol - Dentro meta' =
			
			VAR _V = [Valor Indicador Volume]
			VAR _M = [Meta Indicador Volume]
			VAR _Dir = [_Ind Vol - Direção num (por indicador)]
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _M ) || ISBLANK ( _Dir ),
			        BLANK (),
			        IF ( _Dir = 1, _V >= _M, _V <= _M )
			    )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 532b4203-94b9-40a6-9d2c-40f58035b68f

	measure '_Ind Vol - Valor período anterior' = ```
			
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			RETURN
			    IF (
			        _EhColunaTotal,
			        [_Ind Vol - Valor período anterior (cálculo)],
			        BLANK ()
			    )
			
			```
		lineageTag: 9d34d039-a149-4073-b495-338d9ec0ea40

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente" || _Ind = "Medicações por paciente" || _Ind = "TCs por paciente",
				            "(#,##0.00);(#,##0.00);(#,##0.00)",
				        "(0.00%);(0.00%);(0.00%)"
				    )
				
				```

	measure '_Ind Vol - Var absoluta vs período ant' =
			
			VAR _V = [Valor Indicador Volume]
			VAR _Vp = [_Ind Vol - Valor período anterior]
			RETURN
			    IF ( ISBLANK ( _V ) || ISBLANK ( _Vp ), BLANK (), _V - _Vp )
		lineageTag: 8448d245-8f1a-4a79-bd6a-d60df9d21af1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Ind Vol - Var % vs período ant' =
			
			VAR _V = [Valor Indicador Volume]
			VAR _Vp = [_Ind Vol - Valor período anterior]
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _Vp ) || _Vp = 0,
			        BLANK (),
			        DIVIDE ( _V - _Vp, ABS ( _Vp ) )
			    )
		lineageTag: 8665d17f-2ecb-4447-8c7a-d13cd51b95ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Ind Vol - YTD diff pp (só última coluna)' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _IsWeek = ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _MostrarYtd = _EhColunaTotal
			VAR _Ano = YEAR ( MAX ( 'Calendario'[Data] ) )
			VAR _CalVis =
			    SUMMARIZE (
			        ALLSELECTED ( 'Calendario' ),
			        'Calendario'[Ano Mes Num],
			        'Calendario'[AnoSemana],
			        'Calendario'[Semana Início],
			        'Calendario'[Data]
			    )
			VAR _MaxMes =
			    MAXX (
			        FILTER ( _CalVis, INT ( 'Calendario'[Ano Mes Num] / 100 ) = _Ano ),
			        'Calendario'[Ano Mes Num]
			    )
			VAR _MaxSem =
			    MAXX (
			        FILTER ( _CalVis, YEAR ( 'Calendario'[Semana Início] ) = _Ano ),
			        'Calendario'[AnoSemana]
			    )
			VAR _CurrMes = MAX ( 'Calendario'[Ano Mes Num] )
			VAR _CurrSem = MAX ( 'Calendario'[AnoSemana] )
			VAR _IsLastCol =
			    IF ( _IsWeek, _CurrSem = _MaxSem, _CurrMes = _MaxMes )
			VAR _MinMes =
			    MINX (
			        FILTER ( _CalVis, INT ( 'Calendario'[Ano Mes Num] / 100 ) = _Ano ),
			        'Calendario'[Ano Mes Num]
			    )
			VAR _MinSem =
			    MINX (
			        FILTER ( _CalVis, YEAR ( 'Calendario'[Semana Início] ) = _Ano ),
			        'Calendario'[AnoSemana]
			    )
			VAR _NumSemanasNoRecorte =
			    COUNTROWS (
			        SUMMARIZE (
			            FILTER ( _CalVis, YEAR ( 'Calendario'[Semana Início] ) = _Ano ),
			            'Calendario'[AnoSemana]
			        )
			    )
			VAR _UmMesSo = _MinMes = _MaxMes
			VAR _VBruto = [Valor Indicador Volume]
			VAR _V =
			    IF (
			        _MostrarYtd && _UmMesSo && _NumSemanasNoRecorte > 1,
			        CALCULATE (
			            [Valor Indicador Volume],
			            'Calendario'[Ano Mes Num] = _MaxMes,
			            REMOVEFILTERS ( 'Calendario'[Semana (rótulo)] )
			        ),
			        _VBruto
			    )
			VAR _IniPrimeiraSem =
			    MINX (
			        FILTER ( _CalVis, 'Calendario'[AnoSemana] = _MinSem ),
			        'Calendario'[Semana Início]
			    )
			VAR _VIniSem =
			    CALCULATE (
			        [Valor Indicador Volume],
			        TREATAS ( { _IniPrimeiraSem }, 'Calendario'[Semana Início] ),
			        REMOVEFILTERS (
			            'Calendario'[Semana (rótulo)],
			            'Calendario'[Mes e Ano],
			            'Calendario'[Ano Mes Num]
			        )
			    )
			VAR _MesJaneiroAno = _Ano * 100 + 1
			VAR _VIniMes =
			    CALCULATE (
			        [Valor Indicador Volume],
			        TREATAS ( { _MesJaneiroAno }, 'Calendario'[Ano Mes Num] ),
			        REMOVEFILTERS (
			            'Calendario'[Semana (rótulo)],
			            'Calendario'[Mes e Ano],
			            'Calendario'[Data]
			        )
			    )
			VAR _VIni = _VIniMes
			RETURN
			    IF (
			        NOT _MostrarYtd
			            || ISBLANK ( _Ind )
			            || NOT _IsLastCol
			            || ISBLANK ( _V )
			            || ISBLANK ( _VIni ),
			        BLANK (),
			        _V - _VIni
			    )
		lineageTag: fa8a9f95-e53c-4516-a765-1a15849fa116

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente" || _Ind = "Medicações por paciente" || _Ind = "TCs por paciente",
				            """YTD "" +#,##0.00;""YTD "" -#,##0.00;""YTD "" 0.00",
				        """YTD "" +0.00%;""YTD "" -0.00%;""YTD "" 0.00%"
				    )
				
				```

	measure 'Txt Ind Volume - Valor' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _V = [Valor Indicador Volume]
			VAR _Fmt =
			    SWITCH (
			        _Ind,
			        "Laboratório por paciente", "#,##0.00",
			        "Medicações por paciente", "#,##0.00",
			        "0.00%"
			    )
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || ISBLANK ( _V ),
			        BLANK (),
			        SUBSTITUTE ( FORMAT ( _V, _Fmt ), ".", "," )
			    )
		lineageTag: 75940484-1c26-4ef6-8ab0-5b7db01a60aa

	measure 'Txt Ind Volume - (mês anterior)' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			
			// Total da matriz no eixo colunas (funciona com 1 mês no slicer)
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _FmtValor =
			    SWITCH (
			        TRUE (),
			        _Ind = "Laboratório por paciente" || _Ind = "Medicações por paciente", "#,##0.00",
			        "0.00%"
			    )
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || NOT _EhColunaTotal,
			        BLANK (),
			        VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			        VAR _Y = INT ( _Ym / 100 )
			        VAR _M = MOD ( _Ym, 100 )
			        VAR _PrevYm = IF ( _M = 1, ( _Y - 1 ) * 100 + 12, _Ym - 1 )
			        VAR _VPrevMes =
			            CALCULATE (
			                [Valor Indicador Volume],
			                TREATAS ( { _PrevYm }, 'Calendario'[Ano Mes Num] ),
			                REMOVEFILTERS (
			                    'Calendario'[Mes e Ano],
			                    'Calendario'[Data],
			                    'Calendario'[Semana (rótulo)]
			                )
			            )
			        RETURN
			            IF (
			                ISBLANK ( _VPrevMes ),
			                BLANK (),
			                "(" & SUBSTITUTE ( FORMAT ( _VPrevMes, _FmtValor ), ".", "," ) & ")"
			            )
			    )
		lineageTag: d506a978-6be0-4f68-9b99-972840df52fc

	measure 'Txt Ind Volume - Var' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _V = [Valor Indicador Volume]
			VAR _Vp = [_Ind Vol - Valor período anterior]
			VAR _Dif = _V - _Vp
			VAR _Fmt =
			    SWITCH (
			        _Ind,
			        "Laboratório por paciente", "+#,##0.00;-#,##0.00;0,00",
			        "Medicações por paciente", "+#,##0.00;-#,##0.00;0,00",
			        "+0.00%;-0.00%;0,00%"
			    )
			VAR _Seta = IF ( _Dif > 0, "↑", IF ( _Dif < 0, "↓", "→" ) )
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || ISBLANK ( _V ) || ISBLANK ( _Vp ),
			        BLANK (),
			        _Seta & " " & SUBSTITUTE ( FORMAT ( _Dif, _Fmt ), ".", "," )
			    )
		lineageTag: 1ab73dd4-9469-4f8d-ba55-719c3cbd6555

	measure 'Txt Ind Volume - YTD' =
			
			VAR _YtdPP = [_Ind Vol - YTD diff pp (só última coluna)]
			RETURN
			    IF (
			        ISBLANK ( _YtdPP ),
			        BLANK (),
			        IF (
			            ISBLANK ( [Valor Indicador Volume] ),
			            BLANK (),
			            "YTD Δ "
			                & SUBSTITUTE ( FORMAT ( _YtdPP, "+0.00%;-0.00%" ), ".", "," )
			        )
			    )
		lineageTag: 92628dbc-17b0-4117-ac3d-3a928003170a

	measure 'Cor Txt Ind Volume - Var' = ```
			
			VAR _V = [Valor Indicador Volume]
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Vp = [_Ind Vol - Valor período anterior (cálculo)]
			VAR _Delta = _V - _Vp
			VAR _EhDesfecho = _Ind = "Desfecho do médico do atend."
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _Vp ) || ISBLANK ( _Delta ),
			        BLANK (),
			        IF (
			            _EhDesfecho,
			            SWITCH (
			                TRUE (),
			                _Delta > 0, "#5FAE7B",
			                _Delta < 0, "#D96C6C",
			                "#6B7280"
			            ),
			            SWITCH (
			                TRUE (),
			                _Delta < 0, "#5FAE7B",
			                _Delta > 0, "#D96C6C",
			                "#6B7280"
			            )
			        )
			    )
			
			```
		lineageTag: 0918a486-8b35-4af2-ab74-854443046402

	measure 'Cor Txt Ind Volume - (mês anterior)' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || NOT _EhColunaTotal,
			        BLANK (),
			        VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			        VAR _Y = INT ( _Ym / 100 )
			        VAR _MesNum = MOD ( _Ym, 100 )
			        VAR _PrevYm =
			            IF ( _MesNum = 1, ( _Y - 1 ) * 100 + 12, _Ym - 1 )
			        VAR _DentroMesAnterior =
			            CALCULATE (
			                [_Ind Vol - Dentro meta],
			                TREATAS ( { _PrevYm }, 'Calendario'[Ano Mes Num] ),
			                REMOVEFILTERS (
			                    'Calendario'[Mes e Ano],
			                    'Calendario'[Data],
			                    'Calendario'[Semana (rótulo)]
			                )
			            )
			        RETURN
			            SWITCH (
			                TRUE (),
			                ISBLANK ( _DentroMesAnterior ), "#6B7280",
			                _DentroMesAnterior, "#49A455",
			                "#FF0000"
			            )
			    )
		lineageTag: 817ac4b6-d568-4f6f-8035-ab759f86251a

	measure 'Cor Txt Ind Volume - YTD' = ```
			
			VAR _YtdPP = [_Ind Vol - YTD diff pp (só última coluna)]
			RETURN
			    IF (
			        ISBLANK ( _YtdPP ),
			        BLANK (),
			        IF (
			            ISBLANK ( [Valor Indicador Volume] ),
			            BLANK (),
			            VAR _Inv =
			                SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] ) = "Desfecho do médico do atend."
			            VAR _S = SIGN ( _YtdPP )
			            RETURN
			                IF (
			                    _S = 0,
			                    "#7A7A7A",
			                    IF (
			                        _Inv,
			                        IF ( _S > 0, "#5FAE7B", "#D96C6C" ),
			                        IF ( _S > 0, "#D96C6C", "#5FAE7B" )
			                    )
			                )
			        )
			    )
			
			```
		lineageTag: 6852ed86-9bec-4233-b5ad-d2162c183150

	measure 'Cor Ind Volume - Var' =
			
			VAR _Vp = [_Ind Vol - Valor período anterior]
			VAR _Delta = [Valor Indicador Volume] - _Vp
			
			RETURN
			IF(
			    ISBLANK(_Vp),
			    BLANK(),
			    SWITCH(
			        TRUE(),
			        _Delta > 0, "#1A7F37",   -- verde
			        _Delta < 0, "#C62828",   -- vermelho
			        "#6B7280"                -- cinza
			    )
			)
		lineageTag: 87eb6ba9-cd14-4d67-9094-b794ded9d536

	measure 'Ind Vol - Código ícone meta' =
			
			IF (
			    ISBLANK ( [Valor Indicador Volume] ),
			    BLANK (),
			    IF ( [_Ind Vol - Dentro meta], 1, 0 )
			)
		formatString: 0
		lineageTag: 285d2f73-ee4f-4a43-a700-88df21be46f0

	measure 'Ind Vol - Bandeira min max 12m' = ```
			
			BLANK ()
			
			```
		formatString: 0
		lineageTag: 7c263e13-fa1d-4071-b5e2-1cfdf79e7be6

	measure 'Ind Vol - Var absoluta (número)' = ```
			
			VAR _Ind =
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _V =
			    [Valor Indicador Volume]
			VAR _Vp =
			    [_Ind Vol - Valor período anterior (cálculo)]
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || ISBLANK ( _V ) || ISBLANK ( _Vp ),
			        BLANK (),
			        _V - _Vp
			    )
			
			```
		lineageTag: b5042eeb-7a00-44e7-8b50-cfce121199f2

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente" || _Ind = "Medicações por paciente" || _Ind = "TCs por paciente",
				            "+#,##0.00;-#,##0.00;0.00",
				        "+0.00%;-0.00%;0.00%"
				    )
				
				```

	measure 'Valor Ind Volume - exibe %' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _EhMedia =
			    _Ind = "Laboratório por paciente"
			    || _Ind = "Medicações por paciente"
			    || _Ind = "TCs por paciente"
			    
			RETURN
			    IF ( _EhMedia, BLANK (), [Valor Indicador Volume] )
			
			```
		lineageTag: 1d25bf63-c031-48a9-83ec-e1702e0b79d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Valor Ind Volume - exibe número' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _EhMedia =
			    _Ind = "Laboratório por paciente"
			    || _Ind = "Medicações por paciente"
			    || _Ind = "TCs por paciente"
			RETURN
			    IF ( _EhMedia, [Valor Indicador Volume], BLANK () )
			
			```
		lineageTag: 90bd9331-8bec-47a8-97ea-7fe65a4b7031

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Txt Ind Volume célula (valor+meta+var+YTD)' =
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _V = [Valor Indicador Volume]
			VAR _Dentro = [_Ind Vol - Dentro meta]
			VAR _Vp = [_Ind Vol - Valor período anterior]
			VAR _VarPct = [_Ind Vol - Var absoluta vs período ant]
			VAR _YtdPP = [_Ind Vol - YTD diff pp (só última coluna)]
			VAR _FmtNum =
			    SWITCH (
			        TRUE (),
			        _Ind = "Laboratório por paciente" || _Ind = "Medicações por paciente",
			            "#,##0.00",
			        "0.00%"
			    )
			VAR _TxtVal =
			    IF ( ISBLANK ( _V ), "-", SUBSTITUTE ( FORMAT ( _V, _FmtNum ), ".", "," ) )
			VAR _IconMeta = IF ( _Dentro, "🟢", "🔴" )
			VAR _Delta = _V - _Vp
			VAR _Seta =
			    IF ( ISBLANK ( _Vp ), "", IF ( _Delta > 0, "↑", IF ( _Delta < 0, "↓", "→" ) ) )
			VAR _Sinal = IF ( _Delta > 0, "+", "" )
			VAR _VarTxt =
			    IF (
			        ISBLANK ( _VarPct ),
			        "",
			        " | " & _Seta & " " & _Sinal
			            & SUBSTITUTE ( FORMAT ( _VarPct, "0.00%" ), ".", "," )
			    )
			VAR _YtdTxt =
			    IF (
			        ISBLANK ( _YtdPP ),
			        "",
			        " | YTD Δ "
			            & SUBSTITUTE ( FORMAT ( _YtdPP, "+0.00%;-0.00%" ), ".", "," )
			    )
			RETURN
			    IF ( ISBLANK ( _Ind ), BLANK (), _IconMeta & " " & _TxtVal & _VarTxt & _YtdTxt )
		lineageTag: a2a878be-dc9a-4e6b-85ff-68864085802e

	measure Medida
		lineageTag: 6cdc9f1c-7a2a-4dc1-9535-50e379e52b19

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Meta volume (tooltip por linha)' =
			
			VAR Ind =
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			RETURN
			    SWITCH (
			        Ind,
			        "Conversão",
			            'Meta dinâm volume conversão'[Valor Meta dinâmica volume conversão] * 100,
			        "Pacs medicados",
			            'Meta dinâm volume pacs medicados'[Valor Meta dinâm volume pacs medicados] * 100,
			        "Medicações por paciente",
			            'Meta dinâm volume medicações por pac'[Valor Meta dinâm volume medicações por pac],
			        "Pacs c/ exames laboratoriais",
			            'Meta dinâm volume pacs lab'[Valor Meta dinâm volume pacs lab] * 100,
			        "Laboratório por paciente",
			            'Meta dinâm volume laboratorio por pac'[Valor Meta dinâm volume laboratorio por pac],
			            "TCs por paciente",
			            'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac],
			        "Exames de TC",
			            'Meta dinâm volume TC'[Valor Meta dinâm volume TC] * 100,
			        "Pacs c/ exames de TC",
			            'Meta dinâm volume pacs TC'[Valor Meta dinâm volume pacs TC] * 100,
			        "Triagem acima da meta",
			            'Meta dinâm volume triagem > meta'[Valor Meta dinâm volume triagem > meta] * 100,
			        "Consulta acima da meta",
			            'Meta dinâm volume consulta > meta'[Valor Meta dinâm volume consulta > meta] * 100,
			        "Medicação acima da meta",
			            'Meta dinâm volume medicação > meta'[Valor Meta dinâm volume medicação> meta] * 100,
			        "Reavaliação acima da meta",
			            'Meta dinâm volume reavaliação > meta'[Valor Meta dinâm volume reavaliação > meta] * 100,
			        "Permanência acima da meta",
			            'Meta dinâm volume permanência > meta'[Valor Meta dinâm volume permanência > meta] * 100,
			        "Desfecho do médico do atend.",
			            'Meta dinâm volume desfecho do médico do atend.'[Valor Meta dinâm volume desfecho do médico do atend.] * 100,
			        BLANK ()
			    )
		lineageTag: f38669fe-c93c-42ea-b560-850fe8b5604c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Ind Vol - Valor período anterior (cálculo)' = ```
			
			VAR _Ind =
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			
			VAR _EhColunaTotal =
			    ( NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] ) )
			        || ( NOT HASONEVALUE ( 'Calendario'[Mes e Ano] )
			            && NOT HASONEVALUE ( 'Calendario'[Semana (rótulo)] ) )
			
			VAR _IsWeek =
			    ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _UmMesSo =
			    ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT _IsWeek
			
			VAR _IniSem =
			    MAX ( 'Calendario'[Semana Início] )
			
			VAR _PrevIni =
			    _IniSem - 7
			
			VAR _VPrevSem =
			    CALCULATE (
			        [Valor Indicador Volume],
			        REMOVEFILTERS ( 'Calendario' ),
			        TREATAS ( { _PrevIni }, 'Calendario'[Semana Início] )
			    )
			
			VAR _Ym =
			    MAX ( 'Calendario'[Ano Mes Num] )
			
			VAR _Y =
			    INT ( _Ym / 100 )
			
			VAR _M =
			    MOD ( _Ym, 100 )
			
			VAR _PrevYm =
			    IF ( _M = 1, ( _Y - 1 ) * 100 + 12, _Ym - 1 )
			
			VAR _VPrevMes =
			    CALCULATE (
			        [Valor Indicador Volume],
			        REMOVEFILTERS ( 'Calendario' ),
			        TREATAS ( { _PrevYm }, 'Calendario'[Ano Mes Num] )
			    )
			
			VAR _EndYmVis =
			    MAX ( 'Calendario'[Ano Mes Num] )
			
			VAR _YTot =
			    INT ( _EndYmVis / 100 )
			
			VAR _MTot =
			    MOD ( _EndYmVis, 100 )
			
			VAR _PrevYmTot =
			    IF ( _MTot = 1, ( _YTot - 1 ) * 100 + 12, _EndYmVis - 1 )
			
			VAR _VPrevColunaTotal =
			    CALCULATE (
			        [Valor Indicador Volume],
			        REMOVEFILTERS ( 'Calendario' ),
			        TREATAS ( { _PrevYmTot }, 'Calendario'[Ano Mes Num] )
			    )
			
			RETURN
			    IF (
			        ISBLANK ( _Ind ),
			        BLANK (),
			        IF (
			            _EhColunaTotal,
			            IF ( ISBLANK ( _EndYmVis ), BLANK (), _VPrevColunaTotal ),
			            IF ( _IsWeek, _VPrevSem, IF ( _UmMesSo, _VPrevMes, BLANK () ) )
			        )
			    )
			
			```
		lineageTag: 33660124-d607-43c3-af84-0b7c7085568e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ind Vol - Alerta estatístico var' = ```
			
			VAR _Ind =
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			
			VAR _DeltaAtual =
			    [Ind Vol - Var absoluta (número)]
			
			VAR _EhTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _EhDesfecho =
			    _Ind = "Desfecho do médico do atend."
			
			VAR _DirecaoMelhor =
			    IF ( _EhDesfecho, 1, -1 )
			
			VAR _Z =
			    [Ind Vol - ZScore Var]
			
			VAR _LimiteSigma =
			    COALESCE (
			        SELECTEDVALUE ( 'Alerta Desv Pad'[Alerta Desv. Pad.] ),
			        2.0
			    )
			
			VAR _Melhora =
			    _DeltaAtual * _DirecaoMelhor > 0
			
			RETURN
			    IF (
			        ISBLANK ( _Ind )
			            || ISBLANK ( _DeltaAtual )
			            || _EhTotal
			            || ISBLANK ( _Z ),
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            ABS ( _Z ) < _LimiteSigma, 0,
			            _Melhora, 1,
			            -1
			        )
			    )
			
			```
		formatString: 0
		lineageTag: 89a5f030-550d-49ad-aee6-1c6251efb795

	measure 'Ind Vol - ZScore Var' = ```
			
			VAR _Ind =
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			
			VAR _DeltaAtual =
			    [Ind Vol - Var absoluta (número)]
			
			VAR _EhTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _EhSemana =
			    ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _EhMes =
			    ISINSCOPE ( 'Calendario'[Mes e Ano] ) && NOT _EhSemana
			
			VAR _SemanaAtual =
			    MAX ( 'Calendario'[Semana Início] )
			
			VAR _FimHistSem =
			    _SemanaAtual - 1
			
			VAR _InicioHistSem =
			    EDATE ( _FimHistSem, -12 ) + 1
			
			VAR _HistoricoSemanas =
			    ADDCOLUMNS (
			        SUMMARIZE (
			            FILTER (
			                ALL ( 'Calendario' ),
			                'Calendario'[Semana Início] >= _InicioHistSem
			                    && 'Calendario'[Semana Início] <= _FimHistSem
			            ),
			            'Calendario'[Semana Início]
			        ),
			        "__Delta",
			            VAR _Sem = 'Calendario'[Semana Início]
			            RETURN
			                CALCULATE (
			                    [Ind Vol - Var absoluta (número)],
			                    REMOVEFILTERS ( 'Calendario' ),
			                    TREATAS ( { _Sem }, 'Calendario'[Semana Início] )
			                )
			    )
			
			VAR _HistoricoSemanasValido =
			    FILTER ( _HistoricoSemanas, NOT ISBLANK ( [__Delta] ) )
			
			VAR _MediaSem =
			    AVERAGEX ( _HistoricoSemanasValido, [__Delta] )
			
			VAR _DpSem =
			    STDEVX.S ( _HistoricoSemanasValido, [__Delta] )
			
			VAR _YmAtual =
			    MAX ( 'Calendario'[Ano Mes Num] )
			
			VAR _AnoAtual =
			    INT ( _YmAtual / 100 )
			
			VAR _MesAtual =
			    MOD ( _YmAtual, 100 )
			
			VAR _YmFimHist =
			    IF ( _MesAtual = 1, ( _AnoAtual - 1 ) * 100 + 12, _YmAtual - 1 )
			
			VAR _NumFimHist =
			    INT ( _YmFimHist / 100 ) * 12 + MOD ( _YmFimHist, 100 )
			
			VAR _NumInicioHist =
			    _NumFimHist - 11
			
			VAR _YmInicioHist =
			    INT ( ( _NumInicioHist - 1 ) / 12 ) * 100 + MOD ( _NumInicioHist - 1, 12 ) + 1
			
			VAR _HistoricoMeses =
			    ADDCOLUMNS (
			        SUMMARIZE (
			            FILTER (
			                ALL ( 'Calendario' ),
			                'Calendario'[Ano Mes Num] >= _YmInicioHist
			                    && 'Calendario'[Ano Mes Num] <= _YmFimHist
			            ),
			            'Calendario'[Ano Mes Num]
			        ),
			        "__Delta",
			            VAR _Ym = 'Calendario'[Ano Mes Num]
			            RETURN
			                CALCULATE (
			                    [Ind Vol - Var absoluta (número)],
			                    REMOVEFILTERS ( 'Calendario' ),
			                    TREATAS ( { _Ym }, 'Calendario'[Ano Mes Num] )
			                )
			    )
			
			VAR _HistoricoMesesValido =
			    FILTER ( _HistoricoMeses, NOT ISBLANK ( [__Delta] ) )
			
			VAR _MediaMes =
			    AVERAGEX ( _HistoricoMesesValido, [__Delta] )
			
			VAR _DpMes =
			    STDEVX.S ( _HistoricoMesesValido, [__Delta] )
			
			VAR _MediaRef =
			    IF ( _EhSemana, _MediaSem, IF ( _EhMes, _MediaMes ) )
			
			VAR _DpRef =
			    IF ( _EhSemana, _DpSem, IF ( _EhMes, _DpMes ) )
			
			RETURN
			    IF (
			        ISBLANK ( _Ind )
			            || ISBLANK ( _DeltaAtual )
			            || _EhTotal
			            || ISBLANK ( _MediaRef )
			            || ISBLANK ( _DpRef )
			            || _DpRef = 0,
			        BLANK (),
			        DIVIDE ( _DeltaAtual - _MediaRef, _DpRef )
			    )
			
			```
		lineageTag: 149d00c2-de03-4417-910e-ea2ad37f3f89

		formatStringDefinition = ```
				"0.00;-0.00;0.00"
				
				```

	measure 'Media exames TC por pac' = ```
			
			AVERAGEX (
			    VALUES ( 'TC e US'[NR_ATENDIMENTO] ),
			    CALCULATE (
			        COUNTROWS ( 'TC e US' ),
			        'TC e US'[tipo] = "TC"
			    )
			)
			
			```
		lineageTag: 08e44795-c898-42fc-8ed9-e7310bda5d40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'media meta volume TCs por paciente (condic)' =
			-- usado para fazer as condicional das metas por volumes no Resumo Gerencial
			[Media exames TC por pac] / 'Valor Meta dinâm volume TC por pac'[Valor Valor Meta dinâm volume TC por pac]
		displayFolder: TC/US
		lineageTag: 8f2eb43a-f8fc-48c8-9fde-010eed4f065e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Medida 2'
		lineageTag: a721558d-bd62-4ee7-9643-c94b3889570f

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Valor Indicador Volume RG' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _EhSemana = ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _EhMes = ISINSCOPE ( 'Calendario'[Mes e Ano] ) && NOT _EhSemana
			VAR _EhTotalCol = NOT _EhMes && NOT _EhSemana
			VAR _Sem = MAX ( 'Calendario'[Semana Início] )
			VAR _SemanaFim = MAX ( 'Calendario'[Semana Fim] )
			VAR _UsaAoVivoSemana =
			    _EhSemana && _SemanaFim >= [Data última atualização]
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			VAR _ValorSem =
			    LOOKUPVALUE (
			        'RG Cache Semana Unidade'[Valor],
			        'RG Cache Semana Unidade'[Indicador], _Ind,
			        'RG Cache Semana Unidade'[Unidade], _Un,
			        'RG Cache Semana Unidade'[SemanaInicio], _Sem
			    )
			VAR _ValorMes =
			    LOOKUPVALUE (
			        'RG Cache Mes Unidade'[Valor],
			        'RG Cache Mes Unidade'[Indicador], _Ind,
			        'RG Cache Mes Unidade'[Unidade], _Un,
			        'RG Cache Mes Unidade'[AnoMesNum], _Ym
			    )
			RETURN
			    IF (
			        ISBLANK ( _Ind ),
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            _EhTotalCol, [Valor Indicador Volume RG Base],
			            _UsaAoVivoSemana, [Valor Indicador Volume RG Base],
			            _EhSemana, _ValorSem,
			            _EhMes, _ValorMes,
			            [Valor Indicador Volume RG Base]
			        )
			    )
			
			```
		lineageTag: 4fc30480-c88a-4884-983f-313bb2af7da1

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente", "#,##0.00",
				        _Ind = "Medicações por paciente", "#,##0.00",
				        _Ind = "TCs por paciente", "#,##0.00",
				        "0.00%"
				    )
				
				```

	measure '_Ind Vol - Valor período anterior RG (cálculo)' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _EhSemana = ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _Sem = MAX ( 'Calendario'[Semana Início] )
			VAR _SemPrev = _Sem - 7
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			RETURN
			    IF (
			        ISBLANK ( _Ind ),
			        BLANK (),
			        IF (
			            _EhSemana,
			            LOOKUPVALUE (
			                'RG Cache Semana Unidade'[Valor],
			                'RG Cache Semana Unidade'[Indicador], _Ind,
			                'RG Cache Semana Unidade'[Unidade], _Un,
			                'RG Cache Semana Unidade'[SemanaInicio], _SemPrev
			            ),
			            LOOKUPVALUE (
			                'RG Cache Mes Unidade'[ValorAnterior],
			                'RG Cache Mes Unidade'[Indicador], _Ind,
			                'RG Cache Mes Unidade'[Unidade], _Un,
			                'RG Cache Mes Unidade'[AnoMesNum], _Ym
			            )
			        )
			    )
			
			```
		lineageTag: 3f5cb1a5-5138-4708-9d1e-373d8843579d

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente"
				            || _Ind = "Medicações por paciente"
				            || _Ind = "TCs por paciente",
				            "(#,##0.00);(#,##0.00);(#,##0.00)",
				        "(0.00%);(0.00%);(0.00%)"
				    )
				
				```

	measure '_Ind Vol - Valor período anterior RG' = ```
			
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			VAR _Y = INT ( _Ym / 100 )
			VAR _M = MOD ( _Ym, 100 )
			VAR _YmPrev = IF ( _M = 1, ( _Y - 1 ) * 100 + 12, _Ym - 1 )
			RETURN
			    IF (
			        NOT _EhColunaTotal,
			        BLANK (),
			        CALCULATE (
			            [Valor Indicador Volume RG Base],
			            TREATAS ( { _YmPrev }, 'Calendario'[Ano Mes Num] ),
			            REMOVEFILTERS (
			                'Calendario'[Mes e Ano],
			                'Calendario'[Data],
			                'Calendario'[Semana (rótulo)]
			            )
			        )
			    )
			
			```
		lineageTag: 9155a705-1f6a-41c9-9863-9356b4e128bc

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente"
				            || _Ind = "Medicações por paciente"
				            || _Ind = "TCs por paciente",
				            "(#,##0.00);(#,##0.00);(#,##0.00)",
				        "(0.00%);(0.00%);(0.00%)"
				    )
				
				```

	measure 'Ind Vol - Var absoluta (número) RG' = ```
			
			VAR _V = [Valor Indicador Volume RG]
			VAR _Vp = [_Ind Vol - Valor período anterior RG (cálculo)]
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _Vp ),
			        BLANK (),
			        _V - _Vp
			    )
			
			```
		lineageTag: 71ef8878-d7a7-49f0-a1bf-62c408db1066

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente"
				            || _Ind = "Medicações por paciente"
				            || _Ind = "TCs por paciente",
				            "+#,##0.00;-#,##0.00;0.00",
				        "+0.00%;-0.00%;0.00%"
				    )
				
				```

	measure '_Ind Vol - YTD diff pp RG' = ```
			
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			RETURN
			    IF (
			        NOT _EhColunaTotal || ISBLANK ( _Ind ),
			        BLANK (),
			        LOOKUPVALUE (
			            'RG Cache Mes Unidade'[YTD],
			            'RG Cache Mes Unidade'[Indicador], _Ind,
			            'RG Cache Mes Unidade'[Unidade], _Un,
			            'RG Cache Mes Unidade'[AnoMesNum], _Ym
			        )
			    )
			
			```
		lineageTag: c8117310-e509-41e2-b109-015aa1fc6b76

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente"
				            || _Ind = "Medicações por paciente"
				            || _Ind = "TCs por paciente",
				            """YTD "" +#,##0.00;""YTD "" -#,##0.00;""YTD "" 0.00",
				        """YTD "" +0.00%;""YTD "" -0.00%;""YTD "" 0.00%"
				    )
				
				```

	measure 'Cor Txt Ind Volume - Var RG' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _EhSemana = ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _EhMes = ISINSCOPE ( 'Calendario'[Mes e Ano] ) && NOT _EhSemana
			VAR _EhTotal = NOT _EhSemana && NOT _EhMes
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			VAR _Sem = MAX ( 'Calendario'[Semana Início] )
			VAR _AlertaMes =
			    LOOKUPVALUE (
			        'RG Cache Mes Unidade Alertas'[AlertaVar],
			        'RG Cache Mes Unidade Alertas'[Indicador], _Ind,
			        'RG Cache Mes Unidade Alertas'[Unidade], _Un,
			        'RG Cache Mes Unidade Alertas'[AnoMesNum], _Ym
			    )
			VAR _AlertaSem =
			    LOOKUPVALUE (
			        'RG Cache Semana Unidade Alertas'[AlertaVar],
			        'RG Cache Semana Unidade Alertas'[Indicador], _Ind,
			        'RG Cache Semana Unidade Alertas'[Unidade], _Un,
			        'RG Cache Semana Unidade Alertas'[SemanaInicio], _Sem
			    )
			VAR _Alerta =
			    IF ( _EhSemana, _AlertaSem, IF ( _EhMes, _AlertaMes ) )
			RETURN
			    IF (
			        _EhTotal || ISBLANK ( _Ind ),
			        "#6B7280",
			        SWITCH (
			            _Alerta,
			            1, "#5FAE7B",
			            -1, "#D96C6C",
			            "#6B7280"
			        )
			    )
			
			```
		lineageTag: a34f5605-e6ef-4c65-a4c9-46fa87e15ecd

	measure 'Cor Txt Ind Volume - YTD RG' = ```
			
			VAR _YtdPP = [_Ind Vol - YTD diff pp RG]
			RETURN
			    IF (
			        ISBLANK ( _YtdPP ),
			        BLANK (),
			        IF (
			            ISBLANK ( [Valor Indicador Volume RG] ),
			            BLANK (),
			            VAR _Inv =
			                SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] ) = "Desfecho do médico do atend."
			            VAR _S = SIGN ( _YtdPP )
			            RETURN
			                IF (
			                    _S = 0,
			                    "#7A7A7A",
			                    IF (
			                        _Inv,
			                        IF ( _S > 0, "#5FAE7B", "#D96C6C" ),
			                        IF ( _S > 0, "#D96C6C", "#5FAE7B" )
			                    )
			                )
			        )
			    )
			
			```
		lineageTag: 095b59dc-bde5-481d-b803-9570b484cdf5

	measure 'Meta Indicador Volume RG' = ```
			
			[Meta Indicador Volume]
			
			```
		lineageTag: b16189a1-2f5d-47f8-ae13-6ab32154ae7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Ind Vol - Dentro meta RG' = ```
			
			VAR _V = [Valor Indicador Volume RG]
			VAR _M = [Meta Indicador Volume RG]
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Dir =
			    IF ( _Ind = "Desfecho do médico do atend.", 1, -1 )
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _M ),
			        BLANK (),
			        IF ( _Dir = 1, _V >= _M, _V <= _M )
			    )
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d5ee5825-e4ee-49c0-aeae-a39cb3e473a9

	measure 'Cor Txt Ind Volume - (mês anterior) RG' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _EhColunaTotal =
			    NOT ISINSCOPE ( 'Calendario'[Mes e Ano] )
			        && NOT ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			RETURN
			    IF (
			        ISBLANK ( _Ind ) || NOT _EhColunaTotal,
			        BLANK (),
			        VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			        VAR _Y = INT ( _Ym / 100 )
			        VAR _MesNum = MOD ( _Ym, 100 )
			        VAR _PrevYm =
			            IF ( _MesNum = 1, ( _Y - 1 ) * 100 + 12, _Ym - 1 )
			        VAR _DentroMesAnterior =
			            CALCULATE (
			                [_Ind Vol - Dentro meta RG],
			                TREATAS ( { _PrevYm }, 'Calendario'[Ano Mes Num] ),
			                REMOVEFILTERS (
			                    'Calendario'[Mes e Ano],
			                    'Calendario'[Data],
			                    'Calendario'[Semana (rótulo)]
			                )
			            )
			        RETURN
			            SWITCH (
			                TRUE (),
			                ISBLANK ( _DentroMesAnterior ), "#6B7280",
			                _DentroMesAnterior, "#49A455",
			                "#FF0000"
			            )
			    )
			
			```
		lineageTag: dffd2421-ed07-4aff-8a4a-6b6d18fa26a3

	measure 'Ind Vol - Código ícone meta RG' = ```
			
			IF (
			    ISBLANK ( [Valor Indicador Volume RG] ),
			    BLANK (),
			    IF ( [_Ind Vol - Dentro meta RG], 1, 0 )
			)
			
			```
		formatString: 0
		lineageTag: 658f9b07-6666-469b-814c-820a7684807d

	measure 'Cor Txt Valor Indicador Volume RG' = ```
			
			VAR _V = [Valor Indicador Volume RG]
			VAR _M = [Meta Indicador Volume RG]
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _EhDesfecho = _Ind = "Desfecho do médico do atend."
			RETURN
			    IF (
			        ISBLANK ( _V ) || ISBLANK ( _M ),
			        BLANK (),
			        IF (
			            _EhDesfecho,
			            IF ( _V >= _M, "#49A455", "#FF0000" ),
			            IF ( _V <= _M, "#49A455", "#FF0000" )
			        )
			    )
			
			```
		lineageTag: 66642275-037c-4b08-a8d4-fa8205145f0d

	measure 'Ind Vol - ZScore Var RG' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _EhSemana = ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			VAR _EhMes = ISINSCOPE ( 'Calendario'[Mes e Ano] ) && NOT _EhSemana
			VAR _Ym = MAX ( 'Calendario'[Ano Mes Num] )
			VAR _Sem = MAX ( 'Calendario'[Semana Início] )
			RETURN
			    IF (
			        NOT _EhSemana && NOT _EhMes,
			        BLANK (),
			        IF (
			            _EhSemana,
			            LOOKUPVALUE (
			                'RG Cache Semana Unidade Alertas'[ZScore],
			                'RG Cache Semana Unidade Alertas'[Indicador], _Ind,
			                'RG Cache Semana Unidade Alertas'[Unidade], _Un,
			                'RG Cache Semana Unidade Alertas'[SemanaInicio], _Sem
			            ),
			            LOOKUPVALUE (
			                'RG Cache Mes Unidade Alertas'[ZScore],
			                'RG Cache Mes Unidade Alertas'[Indicador], _Ind,
			                'RG Cache Mes Unidade Alertas'[Unidade], _Un,
			                'RG Cache Mes Unidade Alertas'[AnoMesNum], _Ym
			            )
			        )
			    )
			
			```
		lineageTag: 0b582792-e64f-4f31-8f51-d7bfa7736f11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ind Vol - Bandeira min max 12m RG' = ```
			
			VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
			
			VAR _UsaOriginal =
			    _Ind = "Triagem acima da meta"
			        || _Ind = "Consulta acima da meta"
			        || _Ind = "Medicação acima da meta"
			        || _Ind = "Reavaliação acima da meta"
			        || _Ind = "Permanência acima da meta"
			
			VAR _Un = SELECTEDVALUE ( fluxo[UNIDADE], "__TOTAL__" )
			VAR _Dir = [_Ind Vol - Direção num (por indicador)]
			
			VAR _EhSemana =
			    ISINSCOPE ( 'Calendario'[Semana (rótulo)] )
			
			VAR _EhMes =
			    ISINSCOPE ( 'Calendario'[Mes e Ano] ) && NOT _EhSemana
			
			VAR _EhTotal =
			    NOT _EhSemana && NOT _EhMes
			
			VAR _Tol = 0.0000001
			VAR _VAtual = [Valor Indicador Volume RG]
			VAR _DataRef = [Data última atualização]
			
			RETURN
			    IF (
			        _UsaOriginal,
			        [Ind Vol - Bandeira min max 12m],
			        IF (
			            ISBLANK ( _Ind ) || ISBLANK ( _VAtual ) || _EhTotal || ISBLANK ( _Dir ) || ISBLANK ( _DataRef ),
			            BLANK (),
			            IF (
			                _EhMes,
			                VAR _YmAtual = MAX ( 'Calendario'[Ano Mes Num] )
			
			                VAR _DataFimRef =
			                    EOMONTH ( _DataRef, -1 )
			
			                VAR _YmFim =
			                    YEAR ( _DataFimRef ) * 100 + MONTH ( _DataFimRef )
			
			                VAR _NumFim =
			                    INT ( _YmFim / 100 ) * 12 + MOD ( _YmFim, 100 )
			
			                VAR _NumIni =
			                    _NumFim - 11
			
			                VAR _NumAtual =
			                    INT ( _YmAtual / 100 ) * 12 + MOD ( _YmAtual, 100 )
			
			                VAR _EstaNaJanela =
			                    _NumAtual >= _NumIni && _NumAtual <= _NumFim
			
			                VAR _Base =
			                    FILTER (
			                        'RG Cache Mes Unidade',
			                        'RG Cache Mes Unidade'[Indicador] = _Ind
			                            && 'RG Cache Mes Unidade'[Unidade] = _Un
			                            && INT ( 'RG Cache Mes Unidade'[AnoMesNum] / 100 ) * 12
			                                + MOD ( 'RG Cache Mes Unidade'[AnoMesNum], 100 ) >= _NumIni
			                            && INT ( 'RG Cache Mes Unidade'[AnoMesNum] / 100 ) * 12
			                                + MOD ( 'RG Cache Mes Unidade'[AnoMesNum], 100 ) <= _NumFim
			                            && NOT ISBLANK ( 'RG Cache Mes Unidade'[Valor] )
			                    )
			
			                VAR _MinV =
			                    MINX ( _Base, 'RG Cache Mes Unidade'[Valor] )
			
			                VAR _MaxV =
			                    MAXX ( _Base, 'RG Cache Mes Unidade'[Valor] )
			
			                VAR _YmMin =
			                    MINX (
			                        FILTER ( _Base, ABS ( 'RG Cache Mes Unidade'[Valor] - _MinV ) <= _Tol ),
			                        'RG Cache Mes Unidade'[AnoMesNum]
			                    )
			
			                VAR _YmMax =
			                    MINX (
			                        FILTER ( _Base, ABS ( 'RG Cache Mes Unidade'[Valor] - _MaxV ) <= _Tol ),
			                        'RG Cache Mes Unidade'[AnoMesNum]
			                    )
			
			                VAR _PiorValor =
			                    IF ( _Dir = 1, _MinV, _MaxV )
			
			                VAR _MelhorValor =
			                    IF ( _Dir = 1, _MaxV, _MinV )
			
			                VAR _YmPior =
			                    IF ( _Dir = 1, _YmMin, _YmMax )
			
			                VAR _YmMelhor =
			                    IF ( _Dir = 1, _YmMax, _YmMin )
			
			                RETURN
			                    IF (
			                        NOT _EstaNaJanela
			                            || ISBLANK ( _MinV )
			                            || ISBLANK ( _MaxV )
			                            || ABS ( _MinV - _MaxV ) <= _Tol,
			                        BLANK (),
			                        SWITCH (
			                            TRUE (),
			                            _YmAtual = _YmPior && ABS ( _VAtual - _PiorValor ) <= _Tol, 2,
			                            _YmAtual = _YmMelhor && ABS ( _VAtual - _MelhorValor ) <= _Tol, 1,
			                            BLANK ()
			                        )
			                    ),
			                VAR _SemAtual = MAX ( 'Calendario'[Semana Início] )
			
			                VAR _SemFimRef =
			                    MAXX (
			                        FILTER (
			                            ALL ( 'Calendario' ),
			                            'Calendario'[Semana Fim] < _DataRef
			                        ),
			                        'Calendario'[Semana Início]
			                    )
			
			                VAR _DataIni =
			                    _SemFimRef - 7 * 51
			
			                VAR _EstaNaJanela =
			                    _SemAtual >= _DataIni && _SemAtual <= _SemFimRef
			
			                VAR _Base =
			                    FILTER (
			                        'RG Cache Semana Unidade',
			                        'RG Cache Semana Unidade'[Indicador] = _Ind
			                            && 'RG Cache Semana Unidade'[Unidade] = _Un
			                            && 'RG Cache Semana Unidade'[SemanaInicio] >= _DataIni
			                            && 'RG Cache Semana Unidade'[SemanaInicio] <= _SemFimRef
			                            && NOT ISBLANK ( 'RG Cache Semana Unidade'[Valor] )
			                    )
			
			                VAR _MinV =
			                    MINX ( _Base, 'RG Cache Semana Unidade'[Valor] )
			
			                VAR _MaxV =
			                    MAXX ( _Base, 'RG Cache Semana Unidade'[Valor] )
			
			                VAR _SemMin =
			                    MINX (
			                        FILTER ( _Base, ABS ( 'RG Cache Semana Unidade'[Valor] - _MinV ) <= _Tol ),
			                        'RG Cache Semana Unidade'[SemanaInicio]
			                    )
			
			                VAR _SemMax =
			                    MINX (
			                        FILTER ( _Base, ABS ( 'RG Cache Semana Unidade'[Valor] - _MaxV ) <= _Tol ),
			                        'RG Cache Semana Unidade'[SemanaInicio]
			                    )
			
			                VAR _PiorValor =
			                    IF ( _Dir = 1, _MinV, _MaxV )
			
			                VAR _MelhorValor =
			                    IF ( _Dir = 1, _MaxV, _MinV )
			
			                VAR _SemPior =
			                    IF ( _Dir = 1, _SemMin, _SemMax )
			
			                VAR _SemMelhor =
			                    IF ( _Dir = 1, _SemMax, _SemMin )
			
			                RETURN
			                    IF (
			                        NOT _EstaNaJanela
			                            || ISBLANK ( _SemFimRef )
			                            || ISBLANK ( _MinV )
			                            || ISBLANK ( _MaxV )
			                            || ABS ( _MinV - _MaxV ) <= _Tol,
			                        BLANK (),
			                        SWITCH (
			                            TRUE (),
			                            _SemAtual = _SemPior && ABS ( _VAtual - _PiorValor ) <= _Tol, 2,
			                            _SemAtual = _SemMelhor && ABS ( _VAtual - _MelhorValor ) <= _Tol, 1,
			                            BLANK ()
			                        )
			                    )
			            )
			        )
			    )
			
			```
		formatString: 0
		lineageTag: 4e1d6b5c-c8e4-4261-aabf-390c3e26ea67

	measure '% Atend > Tempo triagem (RG fixo)' = ```
			
			VAR LimiteMinutos = 12
			VAR TotalAtend = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( fluxo[MIN_ENTRADA_X_TRIAGEM] > LimiteMinutos )
			    )
			RETURN
			    IF ( TotalAtend = 0, BLANK (), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0 )
			
			```
		lineageTag: 3b868131-5221-4fc7-999c-f268f240c077

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Atend > Tempo consulta (RG fixo)' = ```
			
			VAR LimiteMinutos = 90
			VAR TotalAtend = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        FILTER ( fluxo, fluxo[MIN_ENTRADA_X_CONSULTA] > LimiteMinutos )
			    )
			RETURN
			    IF (
			        TotalAtend = 0 || ISBLANK ( TotalAtend ),
			        BLANK (),
			        DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0
			    )
			
			```
		lineageTag: 0914ec4d-4d0a-4e90-bd91-1e8485fe2cca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Atend > Tempo medicacao (RG fixo)' = ```
			
			VAR LimiteMinutos = 30
			VAR TotalAtend = COUNT ( medicacao[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( medicacao[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( medicacao[MINUTOS] > LimiteMinutos )
			    )
			RETURN
			    IF ( TotalAtend = 0, BLANK (), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0 )
			
			```
		lineageTag: c5fa96b5-e5bb-4cc2-8330-1213030678fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Atend > Tempo reavaliacao (RG fixo)' = ```
			
			VAR LimiteMinutos = 45
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            VAR DtIni = reavaliacao[DT_SOLIC_REAVALIACAO]
			            VAR DtEvo = reavaliacao[DT_EVO_PRESC]
			            VAR DtFim = reavaliacao[DT_FIM_REAVALIACAO]
			            VAR DtRef =
			                SWITCH (
			                    TRUE (),
			                    ISBLANK ( DtEvo ) && ISBLANK ( DtFim ), BLANK (),
			                    ISBLANK ( DtEvo ), DtFim,
			                    ISBLANK ( DtFim ), DtEvo,
			                    DtEvo <= DtFim, DtEvo,
			                    DtFim
			                )
			            VAR Minutos = DATEDIFF ( DtIni, DtRef, MINUTE )
			            RETURN
			                NOT ISBLANK ( DtIni )
			                    && NOT ISBLANK ( DtRef )
			                    && Minutos > LimiteMinutos
			        )
			    )
			VAR TotalAtend =
			    CALCULATE (
			        COUNT ( reavaliacao[NR_ATENDIMENTO] ),
			        FILTER (
			            reavaliacao,
			            NOT ISBLANK ( reavaliacao[DT_SOLIC_REAVALIACAO] )
			                && (
			                    NOT ISBLANK ( reavaliacao[DT_EVO_PRESC] )
			                        || NOT ISBLANK ( reavaliacao[DT_FIM_REAVALIACAO] )
			                )
			        )
			    )
			RETURN
			    IF (
			        TotalAtend = 0 || ISBLANK ( TotalAtend ),
			        BLANK (),
			        DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0
			    )
			
			```
		lineageTag: 7359f4dd-b872-4e6f-b5c0-492b18a96693

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Atend > Tempo alta (RG fixo)' = ```
			
			VAR LimiteMinutos = 180
			VAR TotalAtend = COUNT ( fluxo[NR_ATENDIMENTO] )
			VAR AtendAcima =
			    CALCULATE (
			        COUNT ( fluxo[NR_ATENDIMENTO] ),
			        KEEPFILTERS ( fluxo[MIN_ENTRADA_X_ALTA] > LimiteMinutos )
			    )
			RETURN
			    IF ( TotalAtend = 0, BLANK (), DIVIDE ( AtendAcima, TotalAtend, 0 ) + 0 )
			
			```
		lineageTag: bd7058b4-f751-41e1-8aa8-aac562f31eae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Valor Indicador Volume RG Base' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] ),
			    "Conversão", [% conversao (0)],
			    "Pacs medicados", [% pacientes medicados],
			    "Medicações por paciente", [Media medicacoes por pac],
			    "Pacs c/ exames laboratoriais", [% pacientes com laborat. (0)],
			    "Laboratório por paciente", [Media exames lab por pac],
			    "Pacs c/ exames de TC", [% pacientes com TC (0)],
			    "TCs por paciente", [Media exames TC por pac],
			    "Triagem acima da meta", [% Atend > Tempo triagem (RG fixo)],
			    "Consulta acima da meta", [% Atend > Tempo consulta (RG fixo)],
			    "Medicação acima da meta", [% Atend > Tempo medicacao (RG fixo)],
			    "Reavaliação acima da meta", [% Atend > Tempo reavaliacao (RG fixo)],
			    "Permanência acima da meta", [% Atend > Tempo alta (RG fixo)],
			    "Desfecho do médico do atend.", [% desfecho do médico do atend. (0)]
			)
			
			```
		lineageTag: ffe75d05-b302-4a95-ac9f-826ef4a920bc

		formatStringDefinition = ```
				VAR _Ind = SELECTEDVALUE ( 'Dim Indicadores Volume'[Indicador] )
				RETURN
				    SWITCH (
				        TRUE (),
				        _Ind = "Laboratório por paciente", "#,##0.00",
				        _Ind = "Medicações por paciente", "#,##0.00",
				        _Ind = "TCs por paciente", "#,##0.00",
				        "0.00%"
				    )
				
				```

	measure 'Medida 3'
		lineageTag: b7dc52cd-8e47-45ae-9838-4b13ba35e2fc

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

