table Meta_procedimento
	lineageTag: 6a61ab90-b325-4abf-9cec-ce8493d951d2

	measure 'Valor Meta_procedimento' = SELECTEDVALUE('Meta_procedimento'[Tempo minutos])
		formatString: 0
		lineageTag: 1daa61ec-23d3-46c7-975a-06814677198d

	column 'Tempo minutos'
		formatString: 0
		lineageTag: f2c21ef1-390f-4d34-a05e-6cab4cc61931
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Meta_procedimento = calculated
		mode: import
		source = GENERATESERIES(0, 120, 1)

	annotation PBI_Id = 5674d25b6df944249d01196f043fd04f

