table procedimento
	lineageTag: 22abadcd-6c1e-4edd-a425-80ea42b18a69

	column UNIDADE
		dataType: string
		lineageTag: 2683be40-a02e-4e42-a244-19cb944645a9
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column CD_ESTABELECIMENTO
		dataType: double
		lineageTag: e09f92be-396f-44a4-974e-8de0df02e493
		summarizeBy: sum
		sourceColumn: CD_ESTABELECIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NR_ATENDIMENTO
		dataType: double
		lineageTag: 53674bd5-fda7-4b0f-b9c6-826bb2101c74
		summarizeBy: none
		sourceColumn: NR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PACIENTE
		dataType: string
		lineageTag: 89d1aad5-b644-4338-a9e7-b5e5fa34713d
		summarizeBy: none
		sourceColumn: PACIENTE

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: da0e5f07-bafe-4408-9ff1-336d0bc84749
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 47e43d19-9c68-4484-aac7-cd61105e457b
			defaultHierarchy: LocalDateTable_13f03cee-ed5f-45bf-bb10-7b66215ceaf0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DT_SOLICITACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: ac836222-5f74-4a06-9e36-98b2523ea6bc
		summarizeBy: none
		sourceColumn: DT_SOLICITACAO

		variation Variation
			isDefault
			relationship: 5312ab83-9263-4ce4-8ab5-36444df42288
			defaultHierarchy: LocalDateTable_7c16547e-86a4-415d-b743-3059f6c68d8d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MINUTOS
		dataType: double
		lineageTag: 09c9687c-dd52-4293-929d-cac0503bb9bd
		summarizeBy: sum
		sourceColumn: MINUTOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HORAS
		dataType: double
		lineageTag: 43b4744b-0d8b-40b4-8578-5417a3d1ac09
		summarizeBy: sum
		sourceColumn: HORAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NR_PRESCRICAO
		dataType: double
		lineageTag: 72453f2b-0707-4b69-b756-b7e6e3c7b73d
		summarizeBy: sum
		sourceColumn: NR_PRESCRICAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STATUS
		dataType: string
		lineageTag: 528427c4-b7f4-46b9-98c3-831da9bfa67d
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column PROCEDIMENTO
		dataType: string
		lineageTag: 1bc41d9e-f26e-4da2-9694-17ce139de784
		summarizeBy: none
		sourceColumn: PROCEDIMENTO

		annotation SummarizationSetBy = Automatic

	column MEDICO
		dataType: string
		lineageTag: 0e6cfc5d-b5eb-46c3-9e51-cf1f160fcec3
		summarizeBy: none
		sourceColumn: MEDICO

		annotation SummarizationSetBy = Automatic

	column DT_EXAME
		dataType: dateTime
		formatString: General Date
		lineageTag: 9fcd2d63-64b8-495b-a1e6-8504cd088b00
		summarizeBy: none
		sourceColumn: DT_EXAME

		variation Variation
			isDefault
			relationship: d63ad6ff-6161-43ec-b9ab-32d6be6e0199
			defaultHierarchy: LocalDateTable_ecaacb9e-0b8d-4f94-ba03-548a0284bd1b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAO
		dataType: string
		lineageTag: 699e1d0b-f890-4f22-818f-293642d830ad
		summarizeBy: none
		sourceColumn: CLASSIFICACAO

		annotation SummarizationSetBy = Automatic

	column Classif_personalizada
		dataType: string
		lineageTag: 743a13c5-c514-48c1-9ab3-af08cb514653
		summarizeBy: none
		sourceColumn: Classif_personalizada

		annotation SummarizationSetBy = Automatic

	column DT_REALIZADO
		dataType: dateTime
		formatString: General Date
		lineageTag: b31cc6aa-2619-45ae-a047-4cd38b319452
		summarizeBy: none
		sourceColumn: DT_REALIZADO

		variation Variation
			isDefault
			relationship: a09d4004-c6b5-4939-83f6-969b0bf8eb20
			defaultHierarchy: LocalDateTable_ababc080-4028-4bbf-acdd-e349a9896612.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition procedimento = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_intern_leitos = Fonte{[Schema="cmc_hospital", Item="tbl_tempos_procedimentos"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(cmc_hospital_intern_leitos,{{"DATA", type date}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Classif_personalizada", each if [CLASSIFICACAO] = "Procedimento Médico - Hospitalar" then "Procedimento médico" else if [CLASSIFICACAO] = "Procedimento Executado - Enfermagem Hospitalar" then "Procedimento enfermagem" else if [CLASSIFICACAO] = "Cardiologicos" then "Cardiológicos" else null)
				in
				    #"Coluna Condicional Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

