table Leitos
	lineageTag: 950fd862-e4c2-4579-8733-f321596734a4

	column CD_ESTABELECIMENTO
		dataType: double
		lineageTag: 8df1efa1-d4b3-4dd1-9ca9-a94f5006e9aa
		summarizeBy: none
		sourceColumn: CD_ESTABELECIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDADE
		dataType: string
		lineageTag: 687d2783-bc55-41f4-abee-a1ed66b0e03d
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column CD_SETOR_ATENDIMENTO
		dataType: double
		lineageTag: a64c55da-6e0f-454e-8eb0-03b8326899a7
		summarizeBy: sum
		sourceColumn: CD_SETOR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DS_SETOR_ATENDIMENTO
		dataType: string
		lineageTag: ad204781-0b9c-4643-b370-20542b819ed5
		summarizeBy: none
		sourceColumn: DS_SETOR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: c946cf07-86c1-458a-aff0-a410bd01b793
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_BASICA
		dataType: string
		lineageTag: 3ee35481-8083-4954-8db2-0047fe5da0bd
		summarizeBy: none
		sourceColumn: CD_UNIDADE_BASICA

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_COMPL
		dataType: string
		lineageTag: 1c141de7-625e-404e-b1f1-3fa7d260cc02
		summarizeBy: none
		sourceColumn: CD_UNIDADE_COMPL

		annotation SummarizationSetBy = Automatic

	column LEITO
		dataType: string
		lineageTag: 5e376826-2dd5-4939-a484-9c656a65e7d2
		summarizeBy: none
		sourceColumn: LEITO

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: string
		lineageTag: 6332b752-d47b-4ffa-a283-7ac2d9eeab0e
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column NM_CURTO
		dataType: string
		lineageTag: 8f390b93-083d-47ed-9948-7ac365fe79cb
		summarizeBy: none
		sourceColumn: NM_CURTO

		annotation SummarizationSetBy = Automatic

	column IE_OCUP_HOSPITALAR
		dataType: string
		lineageTag: 09f80427-6648-4d88-b408-3f95ff87fea3
		summarizeBy: none
		sourceColumn: IE_OCUP_HOSPITALAR

		annotation SummarizationSetBy = Automatic

	column IE_SITUACAO
		dataType: string
		lineageTag: 111e101a-443a-45b4-9e2d-6c9b5e9c11db
		summarizeBy: none
		sourceColumn: IE_SITUACAO

		annotation SummarizationSetBy = Automatic

	column DT_CRIACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: ab4167e5-4359-4740-86a7-6c3c68b130a7
		summarizeBy: none
		sourceColumn: DT_CRIACAO

		variation Variation
			isDefault
			relationship: 5150a2e8-81d8-4838-9c0c-d6820e7f7f81
			defaultHierarchy: LocalDateTable_ba133a2d-89bc-49f5-93de-74a2b398dc76.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DT_ATUALIZACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: 73bd6945-e35f-4ddb-ab6f-2f3b905efbab
		summarizeBy: none
		sourceColumn: DT_ATUALIZACAO

		variation Variation
			isDefault
			relationship: 87cbe572-2705-4e9f-b608-595bbc969014
			defaultHierarchy: LocalDateTable_dec6dce2-b52a-462e-b883-3c32b34deb31.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: db1c3d17-02b6-4122-921f-50f2f7f793d8
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 67a67525-7606-4407-b7c1-9f230c4dc75a
			defaultHierarchy: LocalDateTable_d7a874a3-b4f7-42c6-be4c-d891e6cf772c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CD_LEITO
		dataType: double
		lineageTag: edf72154-7e2c-4b6f-a107-07d4b0ba4ac7
		summarizeBy: none
		sourceColumn: CD_LEITO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Leitos = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_intern_leitos = Fonte{[Schema="cmc_hospital", Item="tbl_intern_leitos"]}[Data],
				    #"Coluna Duplicada" = Table.DuplicateColumn(cmc_hospital_intern_leitos, "DT_CRIACAO", "DT_CRIACAO - Copiar"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Duplicada",{{"DT_CRIACAO - Copiar", "DATA"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"DATA", type date}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","UPC - Unidade Paciente Critico","UPC",Replacer.ReplaceText,{"TIPO"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

