table 'Meta dinâm volume pacs medicados'
	lineageTag: d01cfc10-8a59-463f-ad37-ce027622f706

	measure 'Valor Meta dinâm volume pacs medicados' = SELECTEDVALUE('Meta dinâm volume pacs medicados'[Meta dinâm volume pacs medicados])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fcee536d-d028-49d9-8736-38e8ed4eee43

	column 'Meta dinâm volume pacs medicados'
		lineageTag: 60e8951c-2dc6-4e4f-9b6b-5a863117c342
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Meta dinâm volume pacs medicados' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = 33cb2e1de4cc4bdcac8c7a8faab0a2bc

