table 'Meta dinâm volume conversão'
	lineageTag: ac079f4d-134d-4b53-88c3-30679ae86da8

	measure 'Valor Meta dinâmica volume conversão' = SELECTEDVALUE('Meta dinâm volume conversão'[Meta dinâmica volume conversão])
		formatString: 0%;-0%;0%
		lineageTag: 50cc1eae-9e4f-4c6c-a02a-0b905f19188c

	column 'Meta dinâmica volume conversão'
		formatString: 0%;-0%;0%
		lineageTag: 8215b5c7-bc5c-48a7-9544-7d082249d63e
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta dinâm volume conversão' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = c25e63b8a4be4dd684c7db5a29476a07

