table 'Meta dinâm volume pacs lab'
	lineageTag: 11c6d09d-f701-4d3c-b4b2-7f766b15f083

	measure 'Valor Meta dinâm volume pacs lab' = SELECTEDVALUE('Meta dinâm volume pacs lab'[Meta dinâm volume pacs lab])
		formatString: 0%;-0%;0%
		lineageTag: f9f90a02-f1f7-4e06-82cb-d31ebedbe484

	column 'Meta dinâm volume pacs lab'
		formatString: 0
		lineageTag: 7a0a92bc-a5c7-4b5b-aa77-e80a1f77a441
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta dinâm volume pacs lab' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = 476b6d1dbde44679bd33208f95c67bc5

