table 'Meta dinâm volume TC'
	lineageTag: 32b98629-5423-4ea4-b119-f53c43e64a89

	measure 'Valor Meta dinâm volume TC' = SELECTEDVALUE('Meta dinâm volume TC'[Meta dinâm volume TC])
		lineageTag: 23be9b03-061d-4a04-9680-e48670f672a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta dinâm volume TC'
		lineageTag: 3c4823b7-9e2c-4163-85ca-93e845c34fe4
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Meta dinâm volume TC' = calculated
		mode: import
		source = GENERATESERIES(0, 1.001, 0.001)

	annotation PBI_Id = ab55fbce0ab143aabbdf6bdb33ea89ca

