table Custos
	lineageTag: f1ff5e30-b08a-4198-9da5-85aa8dc4162b

	measure qtd_custo_consult = CALCULATE(sum(Custos[QTD_ATENDIDO]),custos[TIPO] = {"CONSULTAS"})
		formatString: 0
		lineageTag: 16f2c108-9294-4667-ab1f-cf42bb41e83c

	measure Qtd_Custo_Dinamico =
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(Custos[TIPO]) = "CONSULTAS",
			        CALCULATE(SUM(Custos[QTD_ATENDIDO]), Custos[TIPO] = "CONSULTAS"),
			    SELECTEDVALUE(Custos[TIPO]) = "LABORATÓRIO",
			        CALCULATE(SUM(Custos[QTD_ATENDIDO]), Custos[TIPO] = "LABORATÓRIO"),
			    SELECTEDVALUE(Custos[TIPO]) = "IMAGEM",
			        CALCULATE(SUM(Custos[QTD_ATENDIDO]), Custos[TIPO] = "IMAGEM"),
			    SELECTEDVALUE(Custos[TIPO]) = "MEDICAMENTOS",
			        CALCULATE(SUM(Custos[QTD_PRODUTO]), Custos[TIPO] = "MEDICAMENTOS", Custos[QTD_PRODUTO] > 0),
			    SELECTEDVALUE(Custos[TIPO]) = "MATERIAL",
			        CALCULATE(SUM(Custos[QTD_PRODUTO]), Custos[TIPO] = "MATERIAL", Custos[QTD_PRODUTO] > 0),
			    BLANK()
			)
		formatString: 0
		lineageTag: ea10c873-0ad7-4076-b2ae-329ca5b44df5

	measure qtd_custo_imagem = CALCULATE(sum(custos[QTd_ATENDIDO]),custos[TIPO] = {"IMAGEM"})
		formatString: 0
		lineageTag: 63896e02-1b27-47b5-be6b-e13e2df4fa6f

	measure qtd_custo_labor = CALCULATE(SUM(Custos[QTD_ATENDIDO]),Custos[TIPO] = "LABORATÓRIO")
		formatString: 0
		lineageTag: 61c0c7d1-538c-4155-8bbd-8b0107c93d4e

	measure qtd_custo_medic = CALCULATE(sum(Custos[QTD_PRODUTO]),custos[TIPO] in {"MEDICAMENTOS","MATERIAL"},(Custos[QTD_PRODUTO]>0))
		formatString: 0
		lineageTag: 2fcea805-5406-42aa-897b-b3c07f37aa1f

	measure sum_custo_consulta = CALCULATE(sum(Custos[TOTAL]),custos[TIPO] in {"CONSULTAS"})
		lineageTag: 9863fd5c-254b-4dbf-8df9-b5c0ab6c5538

	measure sum_custo_imag = CALCULATE(sum(Custos[TOTAL]),custos[TIPO] in {"IMAGEM"})
		lineageTag: 066b4654-ee7b-44ba-9f53-37fa38fcbdc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure sum_custo_medic = CALCULATE(sum(Custos[TOTAL]),custos[TIPO] in {"MEDICAMENTOS","MATERIAL"})
		lineageTag: 1dda1241-1582-4789-9285-fb6db2b23a55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TicketMedio_geral = DIVIDE(SUM(custos[TOTAL]),DISTINCTCOUNT(custos[ATENDIMENTO]))
		lineageTag: f08e7e00-964f-438b-8d10-ad372864205d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TicketMedio_imag =
			
			DIVIDE(
			    CALCULATE(
			        SUM(Custos[TOTAL]),
			        Custos[Tipo] = "IMAGEM"
			    ),
			    CALCULATE(
			        DISTINCTCOUNT(Custos[Atendimento]),
			        Custos[Tipo] = "IMAGEM"
			    )
			)
		lineageTag: 7d66213d-e56a-40da-ab09-955505bd0d02

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TicketMedio_matmed =
			
			DIVIDE(
			    CALCULATE(
			        SUM(Custos[TOTAL]),
			        Custos[Tipo] in {"MEDICAMENTOS","MATERIAL"},
			        Custos[QTD_PRODUTO] > 0
			    ),
			    CALCULATE(
			        DISTINCTCOUNT(Custos[Atendimento]),
			        Custos[Tipo] IN {"MEDICAMENTOS","MATERIAL"},
			        Custos[QTD_PRODUTO] > 0
			    )
			)
		lineageTag: a5a45d13-f3be-46a2-b042-82d6c7d2bf41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_distinto_contas =
			
			SUMX(
			    VALUES(Custos[ATENDIMENTO]),
			    CALCULATE(SUM(Custos[TOTAL]))
			)
		lineageTag: d231a3e7-07ec-42e3-bee0-c65e5af4d2d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TIPO
		dataType: string
		lineageTag: 9a4d5b91-d87a-44c0-95a7-eb6405dbb40e
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column ATENDIMENTO
		dataType: int64
		formatString: 0
		lineageTag: c36670ec-293f-41b4-9512-d6772fb66999
		summarizeBy: none
		sourceColumn: ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DS_MATERIAL
		dataType: string
		lineageTag: 30842b3d-6b8e-48e9-bed9-f206854ecff8
		summarizeBy: none
		sourceColumn: DS_MATERIAL

		annotation SummarizationSetBy = Automatic

	column QTD_PRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 6a9eb08e-0869-4512-a10a-e5dec9a7cb40
		summarizeBy: sum
		sourceColumn: QTD_PRODUTO

		annotation SummarizationSetBy = Automatic

	column QTD_ATENDIDO
		dataType: int64
		formatString: 0
		lineageTag: e9860f70-cd54-4c9b-811d-94810a602687
		summarizeBy: sum
		sourceColumn: QTD_ATENDIDO

		annotation SummarizationSetBy = Automatic

	column VL_UNITARIO
		dataType: double
		lineageTag: eea16299-e262-4f22-8e83-355964718333
		summarizeBy: sum
		sourceColumn: VL_UNITARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column JUSTIFICATIVA
		dataType: string
		lineageTag: a92b67c1-f4d2-4751-be92-acb684c52c60
		summarizeBy: none
		sourceColumn: JUSTIFICATIVA

		annotation SummarizationSetBy = Automatic

	column PADRONIZADO
		dataType: string
		lineageTag: cbbd5ec3-5475-4ba4-8459-aae85f560f5a
		summarizeBy: none
		sourceColumn: PADRONIZADO

		annotation SummarizationSetBy = Automatic

	column CLASSIF_CUSTO
		dataType: string
		lineageTag: d6f9f925-0272-4fb2-9fff-53ae33323406
		summarizeBy: none
		sourceColumn: CLASSIF_CUSTO

		annotation SummarizationSetBy = Automatic

	column TOTAL = ```
			
			SWITCH(
			    TRUE(),
			    Custos[TIPO] IN {"MEDICAMENTOS","MATERIAL"}, 
			        Custos[QTD_PRODUTO] * Custos[VL_UNITARIO],
			    Custos[TIPO] IN {"IMAGEM","CONSULTAS"}, 
			        Custos[QTD_ATENDIDO] * Custos[VL_UNITARIO],
			    BLANK()
			)
			
			```
		lineageTag: 229b9b7b-74c2-4cd6-aa41-58109e4cf5e3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValorContas = ```
			
			VAR ContaAtual = Custos[ATENDIMENTO]
			VAR Resultado = 
			CALCULATE (
			    SUM ( Custos[TOTAL] ),
			    FILTER ( Custos, Custos[atendimento] = ContaAtual )
			)
			RETURN
			Resultado *1.0
			```
		lineageTag: bddb2d93-0807-4bdd-904a-a37acbcee6ea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ordem_faixas = ```
			
			SWITCH(
			    TRUE(),
			    Custos[ValorContas] <= 200, 1,
			    Custos[ValorContas] <= 400, 2,
			    Custos[ValorContas] <= 600, 3,
			    Custos[ValorContas] <= 1000, 4,
			    Custos[ValorContas] <= 1600, 5,
			    Custos[ValorContas] <= 2200, 6,
			    Custos[ValorContas] <= 3000, 7,
			    Custos[ValorContas] <= 3600, 8,
			    Custos[ValorContas] <= 4200, 9,
			    Custos[ValorContas] <= 7000, 10,
			    Custos[ValorContas] <= 10000, 11,
			    Custos[ValorContas] <= 15000, 12,
			    Custos[ValorContas] <= 20000, 13,
			    14
			)
			
			```
		formatString: 0
		lineageTag: 2b5f95dc-977b-45b5-a6fb-e42968497d01
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Custos_faixas = ```
			
			SWITCH(
			    TRUE(),
			    Custos[ValorContas] <= 200, "0 - 200",
			    Custos[ValorContas] <= 400, "200 - 400",
			    Custos[ValorContas] <= 600, "400 - 600",
			    Custos[ValorContas] <= 1000, "600 - 1.000",
			    Custos[ValorContas] <= 1600, "1.000 - 1.600",
			    Custos[ValorContas] <= 2200, "1.600 - 2.200",
			    Custos[ValorContas] <= 3000, "2.200 - 3.000",
			    Custos[ValorContas] <= 3600, "3.000 - 3.600",
			    Custos[ValorContas] <= 4200, "3.600 - 4.200",
			    Custos[ValorContas] <= 7000, "4.200 - 7.000",
			    Custos[ValorContas] <= 10000, "7.000 - 10.000",
			    Custos[ValorContas] <= 15000, "10.000 - 15.000",
			    Custos[ValorContas] <= 20000, "15.000 - 20.000",
			    "> 20.000"
			)
			
			```
		lineageTag: 82101ef7-72b3-426c-ba11-3aa59dc97d96
		summarizeBy: none
		sortByColumn: Ordem_faixas

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Custos = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("10.250.50.151:6433", "db"),
				    cmc_hospital_tbl_custo_pac_ps = Fonte{[Schema="cmc_hospital",Item="tbl_custo_pac_ps"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"cmc_hospital_tbl_custo_pac_ps",{{"TIPO", type text}, {"ATENDIMENTO", Int64.Type}, {"DS_MATERIAL", type text}, {"QTD_PRODUTO", Int64.Type}, {"QTD_ATENDIDO", Int64.Type}, {"VL_UNITARIO", type number}, {"JUSTIFICATIVA", type any}, {"PADRONIZADO", type any}, {"CLASSIF_CUSTO", type any}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

