table 'Meta dinâm volume medicação > meta'
	lineageTag: 9cf8d5ef-eba7-4652-b1ed-3304704fa3d4

	measure 'Valor Meta dinâm volume medicação> meta' = SELECTEDVALUE('Meta dinâm volume medicação > meta'[Meta dinâm volume medicação > meta])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aa1c7c51-d892-4f7a-8748-113ecf33e64d

	column 'Meta dinâm volume medicação > meta'
		lineageTag: 0b28d1b5-203f-4e71-87f3-00b10ded3981
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Meta dinâm volume medicação > meta' = calculated
		mode: import
		source = GENERATESERIES(0, 1.01, 0.001)

	annotation PBI_Id = 50a3fc9f029343dca308a15798e2711e

