table 'Meta TC_US_imagem'
	lineageTag: dfb67abf-6092-497f-8da8-9c1f9fd73788

	measure 'Valor Meta TC_US_imagem' = SELECTEDVALUE('Meta TC_US_imagem'[Meta TC_US_imagem])
		formatString: 0
		lineageTag: 0536bad2-519b-4e0d-9b25-ce1e56cb0919

	column 'Meta TC_US_imagem'
		formatString: 0
		lineageTag: 1dfcf04a-d052-4698-bd62-0d5820bd1bff
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Meta TC_US_imagem' = calculated
		mode: import
		source = GENERATESERIES(0, 300, 1)

	annotation PBI_Id = 6e4f6701e93940de852951a306f99039

