table 'Meta dinâm volume laboratorio por pac'
	lineageTag: 33c9817a-ad25-4d63-9cc9-8f726392b1cd

	measure 'Valor Meta dinâm volume laboratorio por pac' = SELECTEDVALUE('Meta dinâm volume laboratorio por pac'[Meta dinâm volume laboratorio por pac])
		lineageTag: a6e140a3-3ce2-4bb7-83ff-26ff4f54199c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meta dinâm volume laboratorio por pac'
		lineageTag: 361fa45c-6d08-4b0d-b2a7-d6b886fc3fd7
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Meta dinâm volume laboratorio por pac' = calculated
		mode: import
		source = GENERATESERIES(1, 5.01, 0.001)

	annotation PBI_Id = 6f7f407976964f6ba4e9c2a62ed04be6

