table 'Valor Meta dinâm volume TC por pac'
	lineageTag: 3d35e939-641e-415d-ab74-1ea16b749d28

	measure 'Valor Valor Meta dinâm volume TC por pac' = SELECTEDVALUE('Valor Meta dinâm volume TC por pac'[Valor Meta dinâm volume TC por pac])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: d9b82a38-0dbb-4674-829a-3dbb6f989a73

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Valor Meta dinâm volume TC por pac'
		lineageTag: 73d00f82-68ae-416b-a6b3-ddc259fe92db
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Valor Meta dinâm volume TC por pac' = calculated
		mode: import
		source = GENERATESERIES(1, 5.01, 0.01)

	annotation PBI_Id = 13ee71adf3484a97866c0fea74b87ab5

